### ISSUE TITLE
这版本什么时候能发布正式版啊？

### ISSUE THREAD

**Issue by mylovefly001** [top-think/think#10]
这版本什么时候能发布正式版啊？感觉好久没动静了。。

**Comment by dotku** [comment]
今年 4 月份的时候好像更新了一下，12 月份有比较多的更新...
貌似都是流年老大更新的 ...?!

**Comment by liu21st** [comment]
年前会争取发布一个RC版本 看测试的情况，现在项目社区有一起在参与的
