### ISSUE TITLE
composer安装tp5.2报错

### ISSUE THREAD

**Issue by Maskhe** [top-think/think#1002]
composer create-project topthink/think tp5 5.2.*-dev
在ubuntu上运行结果如下：

![屏幕截图_352](https://user-images.githubusercontent.com/30264078/69957972-c7a73080-153e-11ea-83d4-935fc4a4a56a.png)
能否解答一下，弄了好久没解决

**Comment by liu21st** [comment]
没有5.2版本的

**Comment by Maskhe** [comment]
好的
