### ISSUE TITLE
composer 安装TP 6框架，自动加载文件[autoload_static.php]访问了私有属性

### ISSUE THREAD

**Issue by ysp198910** [top-think/think#1009]
下面的方法访问了【ClassLoader】类的私有属性
`public static function getInitializer(ClassLoader $loader)`
搞得我编辑器报错！

**Comment by liu21st** [comment]
这个和框架没有关系

**Comment by ysp198910** [comment]
那个composer 的配置安装文件，不是你们写的么？在composer.json的 【scripts】下执行的命令【@php think service:discover】

**Comment by ysp198910** [comment]
> 这个和框架没有关系

那个composer 的配置安装文件，不是你们写的么？在composer.json的 【scripts】下执行的命令【@php think service:discover】
