### ISSUE TITLE
php think optimize:schema 报错

### ISSUE THREAD

**Issue by Ya-hui** [top-think/think#1010]
运行 php think optimize:schema 报错
![image](https://user-images.githubusercontent.com/13138164/71520846-23c06300-28f9-11ea-8dcc-9979d6df3a5e.png)
![image](https://user-images.githubusercontent.com/13138164/71520866-405c9b00-28f9-11ea-8fd5-39cf9f2361f6.png)
![image](https://user-images.githubusercontent.com/13138164/71520884-58ccb580-28f9-11ea-912a-aa8e7f2d8084.png)
网上搜没搜到 怀疑是我自己的原因然后我改成 return $this->connection ? $this->connection : ''; 还是不行 打印$this->connection 是null

**Comment by liu21st** [comment]
已经修正
