### ISSUE TITLE
thinkphp6 全局查询范围不支持驼峰

### ISSUE THREAD

**Issue by xaake** [top-think/think#1012]
目前thinkphp6的全局查询范围的写法：

> /**
     * 定义全局搜索条件
     * @var array
     */
    protected $globalScope = ['is_delete'];

    /**
     * 定义全局搜索条件
     * 软删除
     * @param $query
     */
    public function scopeIs_delete($query)
    {
        $query->where('is_delete', 0);
    }

如果支持驼峰的话，那么应该写成

`scopeIsDelete($query)
 {
     $query->where('is_delete',0);
 }`

建议支持驼峰

**Comment by liu21st** [comment]
怎么不支持？
