### ISSUE TITLE
组件版本建议

### ISSUE THREAD

**Issue by xcorp1986** [top-think/think#1020]
如topthink/think-worker、topthink/think-migration里面的1.*、2.*分别对应5.0、5.1，对于刚使用框架的人不是那么友好，并且不方便对后续的维护，建议与主框架版本持平

**Comment by liu21st** [comment]
这个似乎不可避免，毕竟除了官方扩展之外，还有很多第三方的扩展 你能统一这样约束？况且，有版本依赖不至于有啥影响
