### ISSUE TITLE
是否有计划出一个User或者Auth扩展

### ISSUE THREAD

**Issue by mydzoo** [top-think/think#1021]
类似于Yii的Yii::$app->user组件 和 laravel的Auth:user()功能

**Comment by liu21st** [comment]
官方扩展旨在抛砖引玉，第三方扩展可以做的更好的

**Comment by mydzoo** [comment]
无论在web时代，还是现在的前后端分离Api趋势下。Auth组件(User组件)始终贯穿着整个项目，作为必不可少的构成部分。如何去实现一个高质量，高解耦，易扩展的代码，TP作为一个快速、简单、高效的PHP框架，希望官方可以考虑以扩展形式融入User组件。希望官方可以考虑

**Comment by liu21st** [comment]
每个组件都很重要 看不同的项目需求 百花齐放才能有更好的选择 其实Auth扩展已经有很多了 参考 https://github.com/top-think/think-awesome

**Comment by mydzoo** [comment]
这些扩展要么是针对Web端，要么是针对API端的。并没有一个比较通用的Auth扩展（或者是我没发现？），类似于laravel的Auth::user()之类的通过修改`config/auth.php`文件的`guards`即可。
而无论是在控制器或者模型，我只需要调用`Auth::user()`就可以得到当前登陆的用户，通过`Auth::user()->id`就可以得到当前登陆者的ID。
