### ISSUE TITLE
tp5.1模型构造方法不能进行初始化操作嘛？这样就找不到数据

### ISSUE THREAD

**Issue by github583442736** [top-think/think#1028]
public function __construct($applicationId)
    {
        $this->applicationId = $applicationId;
        parent::__construct($data = []);
    }

**Comment by github583442736** [comment]
重载的问题

**Comment by github583442736** [comment]
如果我想在模型里面配置表名的话？可以怎么处理

**Comment by liu21st** [comment]
不要这么操作模型 还不如用Db类这样
