### ISSUE TITLE
所有中间件 不使用 也会运行？？？

### ISSUE THREAD

**Issue by YLJIOS** [top-think/think#1031]
Thinkphp 6.0.2
PHP 7.3.4

定义的所有中间件 在不使用的情况下 会默认全部执行一遍？当被调用时 会再执行一次。
如果我定义的中间件很多的话，是不是很费时间
具体如下图定义：

![image](https://user-images.githubusercontent.com/13409767/77139658-c8de7800-6ab1-11ea-8c3c-10557379f0f5.png)
![image](https://user-images.githubusercontent.com/13409767/77139668-d693fd80-6ab1-11ea-8f8d-e933f7976342.png)
![image](https://user-images.githubusercontent.com/13409767/77139675-e1e72900-6ab1-11ea-841f-df811a8e6840.png)
![image](https://user-images.githubusercontent.com/13409767/77139685-e9a6cd80-6ab1-11ea-906c-5a091d0d1ce0.png)
![image](https://user-images.githubusercontent.com/13409767/77139701-f5928f80-6ab1-11ea-8ea2-754c6c88e5df.png)
![image](https://user-images.githubusercontent.com/13409767/77139735-1e1a8980-6ab2-11ea-8757-b45cd2d16777.png)
![image](https://user-images.githubusercontent.com/13409767/77139742-2672c480-6ab2-11ea-8204-3077a0e21768.png)

**Comment by momoca** [comment]
因为你在全局中间件中定义了呀.
你估计需要看一下:https://www.kancloud.cn/manual/thinkphp6_0/1075414
搜索:中间件,看看吧.
