### ISSUE TITLE
App.php 文件中获取框架根目录，可以直接这样写。

### ISSUE THREAD

**Issue by twomiao** [top-think/think#1033]
/**
     * 获取应用根目录
     * @access protected
     * @return string
     */
    protected function getDefaultRootPath(): string
    {
       # $path = dirname(dirname(dirname(dirname($this->thinkPath))));
       #建议修改使用这种方式。
       $path = dirname($this->thinkPath, 4);

        return $path . DIRECTORY_SEPARATOR;
    }

**Comment by liu21st** [comment]
感谢提醒 已改进
