### ISSUE TITLE
think\file\UploadedFile::move方法有bug，代码行数：65，69

### ISSUE THREAD

**Issue by twomiao** [top-think/think#1034]
#### 复现代码：    

```
$file = request()->file('photo');
$file->move( app()->getRootPath() . 'public/photo', 'ipx.jpg');
```
#### 报错信息：
 - Error：move_uploaded_file() expects parameter 2 to be a valid path, object given

#### 框架错误代码：
1.  $target = $this->getTargetFile($directory, $name); # 该方法得到 File 实例
2.  $moved = move_uploaded_file($this->getPathname(), $target); # 错误代码
3.  @chmod($target, 0666 & ~umask());  # 错误代码

**Comment by liu21st** [comment]
这个地方已经修正过的哦
