### ISSUE TITLE
linux下关于route目录下任何文件都会加载的问题

### ISSUE THREAD

**Issue by suryluk** [top-think/think#1036]
编辑文件 route.php 时, 会生成 .route.php.swp 文件, 然后这个文件被加载了, 导致整个网站都出现这个文件内容的明文代码, 排查了半天还以为是被注入了...
这种情况虽然比较少见, 但是出了问题真的好难排查

**Comment by lshaocheng** [comment]
这就是你自己的问题了

**Comment by lshaocheng** [comment]
> 编辑文件 route.php 时, 会生成 .route.php.swp 文件, 然后这个文件被加载了, 导致整个网站都出现这个文件内容的明文代码, 排查了半天还以为是被注入了...
> 这种情况虽然比较少见, 但是出了问题真的好难排查

这是你自己造成的
