### ISSUE TITLE
关闭 env里的app_debug还是显示错误信息

### ISSUE THREAD

**Issue by bingheyiomiao** [top-think/think#1065]
.env  里面的设置为false
![image](https://user-images.githubusercontent.com/33817514/96150814-56495400-0f3d-11eb-9f4f-05ed951aa610.png)

 然后代码里这样写
![image](https://user-images.githubusercontent.com/33817514/96150897-6c571480-0f3d-11eb-90ce-864683463d0d.png)

关闭后访问，还是显示错误信息和行数了
![image](https://user-images.githubusercontent.com/33817514/96150995-8690f280-0f3d-11eb-8320-773a23f3e6a6.png)

**Comment by khongshao** [comment]
用0或1代替true和false。 如果还是不行，全局搜索是否有
$this->app->debug

**Comment by liu21st** [comment]
已经修正了
