### ISSUE TITLE
think-swoole在TP6开启多应用模式首次访问异常会导致路由失效

### ISSUE THREAD

**Issue by etjson** [top-think/think#1068]
think-swoole在TP6开启多应用模式下如果某个路由没有访问过一次，那么其他报错，哪怕是404控制器不存在也会导致没有访问过的路由直接失效。

目前很挫的方法就是在重启后或者启动后第一时间访问每一个路由，使其路由生效，然后其他报错就不会导致路由失效。

**Comment by wushd** [comment]
请问这个问题解决了吗

**Comment by etjson** [comment]
#121 看这个，作者直接说think-swoole不支持多应用。

**Comment by etjson** [comment]
> 请问这个问题解决了吗

[#121 (comment)](https://github.com/top-think/think-swoole/issues/121#issuecomment-597222363)
看这个，作者直接说think-swoole不支持多应用。

**Comment by wushd** [comment]
那这样的话用到think-swoole就只能单应用了吗，这不是限制很大

**Comment by wushd** [comment]
有什么其他解决方案吗

**Comment by etjson** [comment]
> 有什么其他解决方案吗

最好的方法就是自己改一个插件，目前只能这样。

**Comment by wushd** [comment]
有没有代码可以发给我参考下吗

**Comment by etjson** [comment]
> 有没有代码可以发给我参考下吗

TP6的我还没改好，TP5的我改了一个composer require jsonet/think-swoole

**Comment by wushd** [comment]
多谢大佬，我去看看

**Comment by etjson** [comment]
TP6的解决方案：
app应用根目录下创建Http类并继承\think\Http,空类
然后在provider.php中think\swoole\Http绑定到自己创建的Http即可。
