### ISSUE TITLE
V6.0.9 使用composer安装不上

### ISSUE THREAD

**Issue by 956569011** [top-think/think#1085]
composer create-project --prefer-dist topthink/think=v6.0.9 下载后,不能下载成功,只能下载到 v6.0.8版本

**Comment by liu21st** [comment]
检查下php版本 6.0.9版本由于依赖更新的问题 需要PHP7.2.5+

**Comment by 956569011** [comment]
我用composer安装的时候php版本是 **php7.3** ,composer调用的php也是**php7.3**,
无论是从composer update 更新框架到v6.0.9 ,还是重装到最新v6.0.9都只能下载到v6.0.8
