### ISSUE TITLE
php think optimize:schema

### ISSUE THREAD

**Issue by 956569011** [top-think/think#1086]
这个在多模块下执行不会生成数据库缓存字段文件

**Comment by liu21st** [comment]
多应用模式下 需要指定应用生成字段缓存

**Comment by 956569011** [comment]
安装了多应用的支持
composer require topthink/think-multi-app
也创建了admin应用,
执行这个命令,命令行提示成功,
但执行后**不会**自动在runtime/schema目录下面按照数据表生成字段缓存文件
php think optimize:schema admin
