### ISSUE TITLE
服务器端500错误，但前端不会显示任何错误信息

### ISSUE THREAD

**Issue by 490626721** [top-think/think#1101]
服务器端500错误，但是接口不会显示任何错误信息,好像跟返回的数据格式有关；
服务器nginx日志：
`Stack trace:
#0 E:\phpstudy_pro\WWW\c.com\vendor\topthink\framework\src\think\Response.php(385): think\response\Json->output(false)
#1 E:\phpstudy_pro\WWW\c.com\vendor\topthink\framework\src\think\Response.php(131): think\Response->getContent()
#2 E:\phpstudy_pro\WWW\c.com\vendor\topthink\framework\src\think\initializer\Error.php(58): think\Response->send()
#3 E:\phpstudy_pro\WWW\c.com\vendor\topthink\framework\src\think\initializer\Error.php(91): think\initializer\Error->appException(Object(think\exception\ErrorException))
#4 [internal function]: think\initializer\Error->appShutdown()
#5 {main}
  **thrown in E:\phpstudy_pro\WWW\c.com\vendor\topthink\framework\src\think\response\Json.php on line 50" while reading response header from upstream, client: 127.0.0.1, server: c.com, request: "POST /admin/panorama-add-hots HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "c.com", referrer: "https://192.168.1.36:8080/**"`

**Comment by zcenet** [comment]
邮箱已收到，谢谢你的支持，祝你生活愉快~~=================================杨怀桂手机:13698971401

**Comment by zaj966** [comment]
把调试关闭打开试下
