### ISSUE TITLE
标签扩展怎么使用，文档的demo无效

### ISSUE THREAD

**Issue by mkinit** [top-think/think#1103]
https://www.kancloud.cn/manual/think-template/1286424
按这个demo做的完全没用，标签原样输出了。

**Comment by zcenet** [comment]
邮箱已收到，谢谢你的支持，祝你生活愉快~~=================================杨怀桂手机:13698971401

**Comment by mkinit** [comment]
发现是缓存问题，如果刚开始有错误的话，修改后要删除runtime/temp这个缓存目录的文件，再刷新页面。
