### ISSUE TITLE
TP5怎么访问静态文件

### ISSUE THREAD

**Issue by pwf0112** [top-think/think#111]
新版本怎么访问public/static目录下的静态文件。
http://域名/static/1.jpg这种方式访问不了。

**Comment by kinosang** [comment]
TP不存在此问题，请检查web server（如apache、nginx）设置

**Comment by pwf0112** [comment]
TP3.2.3中隐藏入口文件(index.php)后，开启URL重写模式，可以通过http://域名/public/1.jpg方式访问Public目录下的静态文件。
我想了解下TP5中在隐藏入口文件(index.php)的情况下怎么访问public/static目录下的静态文件。需要做些什么配置？

**Comment by kinosang** [comment]
配置url重写时请注意添加忽略存在的文件和文件夹的项目

**Comment by pwf0112** [comment]
TP5怎么配置URL重写，配置后怎么访问public/static下静态文件。能给个例子吗？

**Comment by kinosang** [comment]
@pwf0112 什么web server呢？

**Comment by pwf0112** [comment]
IIS7

**Comment by kinosang** [comment]
@pwf0112 这个不清楚。你可以用TP3.2的配置试试。注意TP5的网站根目录是 public

**Comment by pwf0112** [comment]
@kinosang 好像不行了。TP5找不到URL_MODEL这个配置项了。那我在研究研究。
提示这个错误：[ 10005 ] module [ static ] not exists 明显是当成模块处理了。
一直没搞明白TP3.2是怎么实现在隐藏入口文件的情况下没有把public当成模块名处理的。

**Comment by kinosang** [comment]
@pwf0112 静态文件不应该交给TP来处理，你需要在url重写规则中忽略真实存在的文件的url

**Comment by pwf0112** [comment]
@kinosang 恩 谢谢。 我在研究下。 IIS还不太熟悉。

**Comment by fengwuxin** [comment]
来来来，请帮忙看下我的nginx配置

![image](https://cloud.githubusercontent.com/assets/5679152/25882750/4e327096-3578-11e7-9a2e-7057bfe3188e.png)
