### ISSUE TITLE
为什么thinkphp5版本的zip里面没有thinkphp这个文件目录呢

### ISSUE THREAD

**Issue by BreakALegCml** [top-think/think#1112]
![image](https://user-images.githubusercontent.com/73064965/178890091-804b9abe-8754-4474-9076-801f1704f9b3.png)

问题如题，为什么这里面没有thinkphp这个目录呢

**Comment by xinn-net** [comment]
多看看文档, 分为两个仓库了
![微信截图_20220804141447](https://user-images.githubusercontent.com/40051896/182776400-4641fef1-3b5f-43a9-821f-cae9c1a4015e.png)

**Comment by shirne** [comment]
有执行过 `composer i` 了 ?

**Comment by BreakALegCml** [comment]
> 有执行过 `composer i` 了 ?

感谢！解决问题了

**Comment by BreakALegCml** [comment]
> 多看看文档, 分为两个仓库了 ![微信截图_20220804141447](https://user-images.githubusercontent.com/40051896/182776400-4641fef1-3b5f-43a9-821f-cae9c1a4015e.png)

感谢大佬！！！
