### ISSUE TITLE
路由解析变量问题

### ISSUE THREAD

**Issue by QiiSyhx** [top-think/think#113]
路由：\Think\Route::get('test', 'index/index/test', ['ext' => 'html'], ['id' => '/\d+/']);
链接：/test/id/34534.html
使用：return I('get.id');
结果：34534.html
正确的结果应该是：34534

**Comment by Lofanmi** [comment]
@QiiSyhx  你拉去最新版了吗？

**Comment by pwf0112** [comment]
我测试过了，最新版本不存在这个问题了，最初的Beta版本中存在。

**Comment by QiiSyhx** [comment]
get的问题不存在，不过post依然存在问题：
HTML
<form method="post"><input name="a[]" value="this a"><input name="a[]" value="this a2"><input type="submit" value="SUBMIT"></form>

dump(I('post.')):
array(1) {
  ["a"] => array(2) {
    [0] => string(6) "this a"
    [1] => string(7) "this a2"
  }
}
dump(I('post.a')):
string(5) "Array"
二维数组取值时存在问题。

**Comment by liu21st** [comment]
@QiiSyhx  这是新版I函数的机制 默认都是/s 变量修饰符 如果是数组必须手动加上 /a
