### ISSUE TITLE
README.md 文件渲染后，好像存在编码问题，请复查

### ISSUE THREAD

**Issue by dingdayu** [top-think/think#114]
在github的手机端查看时，README文件，渲染后存在编码问题，渲染前可以正常查看，请电脑方便的同学，复查。

**Comment by Lofanmi** [comment]
@dingdayu 我的正常哦 你是访问哪个链接

**Comment by cnzin** [comment]
这样的问题lz最好截个图,详细地描述下能够使他人能最快还原问题。

**Comment by kinosang** [comment]
未能复现相同问题，请检查手机浏览器编码设置。

**Comment by dingdayu** [comment]
十分抱歉，上周因为赶一个项目，很少上来，这个确实不是项目文件的问题，应该是APP的问题，十分抱歉。
