### ISSUE TITLE
$_REQUEST问题

### ISSUE THREAD

**Issue by QiiSyhx** [top-think/think#132]
request并没有得到get及post变量。
测试：
/test.php?a=1&b=2&c=3
var_dump($_REQUEST);//array(3) { ["a"]=> string(1) "1" ["b"]=> string(1) "2" ["c"]=> string(1) "3" }
说明环境配置没有问题..

在tp下：
/admin/system/menu/mid/3/op/post.html
dump(I('get.mid'));//3
dump(I('request.mid'));//0
dump($_GET);
//array(2) {
  ["mid"] => string(1) "3"
  ["op"] => string(4) "post"
}
dump($_REQUEST);//array(0){}

**Comment by liu21st** [comment]
没有合并 request是一个有安全隐患的全局变量 也不建议
