### ISSUE TITLE
模型自动添加数据

### ISSUE THREAD

**Issue by QiiSyhx** [top-think/think#134]
protected $auto  = ['field',1];
我想要的auto是这样的：
字段field为可选字段，用户可填写或不填写。当用户不填写时，使用auto配置自动完成,当用户填写时，使用用户填写的值，而不自动填充。
比如：排序字段，性别等。
现在的auto是全部填充，只适用于create_time,update_time,ip等这样的字段

**Comment by liu21st** [comment]
自动填充的规则和方法完全是由你自己定义的啊~
