### ISSUE TITLE
where($map)->select() 出错

### ISSUE THREAD

**Issue by dotku** [top-think/think#135]
我在测试使用 5.0 Beta 中来读取 wordpress 中的 posts 发现 select 出错

    public function getBlog_bug(){
        $model = D('posts');
        $map_post['post_status'] = 'publish';
        $model->where($map_post)->select();
    }

以下是错误报告

        Fatal error: Call to a member function quote() on a non-object in C:\wamp\www\lab\thinkphp\thinkphp_5.0.0_beta\thinkphp\library\think\db\driver.php on line 1132
        Call Stack
        #	Time	Memory	Function	Location
        1	0.0012	140512	{main}( )	..\index.php:0
        2	0.0022	151504	require_once( 'C:\wamp\www\lab\thinkphp\thinkphp_5.0.0_beta\thinkphp\start.php' )	..\index.php:6
        3	0.0186	434096	think\App::run( )	..\start.php:51
        4	0.0313	696456	invoke ( )	..\app.php:109
        5	0.0313	696504	index\controller\Index->getBlog_bug( )	..\app.php:109
        6	0.0380	1200616	think\Model->select( )	..\index.php:21
        7	0.0385	1207392	think\db\Driver->select( )	..\model.php:467
        8	0.0385	1207408	think\db\Driver->buildSelectSql( )	..\driver.php:1040
        9	0.0385	1207536	think\db\Driver->parseSql( )	..\driver.php:1061
        10	0.0386	1209808	think\db\Driver->parseWhere( )	..\driver.php:1080
        11	0.0386	1210464	think\db\Driver->parseWhereItem( )	..\driver.php:582
        12	0.0387	1211056	think\db\Driver->parseValue( )	..\driver.php:664
        13	0.0387	1211080	think\db\Driver->escapeString( )	..\driver.php:457

目前我只好先写成这样了，可以成功运行

    $output['data'] = $model->where('post_status = "publish"')->select();

**Comment by liu21st** [comment]
我想问下是用的github最新版本测试的么？

**Comment by dotku** [comment]
我是用官网的测试的；另外 github 版本 build.php 无效哟...

**Comment by dotku** [comment]
@liu21st github 版本没有这个问题，我刚刚测试了:)

**Comment by dotku** [comment]
把 github 版本中的这几个文件，替换掉官网的就好了

\thinkphp\library\think\db.php
\thinkphp\library\think\debug.php
\thinkphp\library\think\db\driver.php

**Comment by liu21st** [comment]
build.php 无效是加上了开关了

**Comment by dotku** [comment]
@liu21st 在哪里开启呢？
其实可以考虑在源码中把使用说明都加进去...

**Comment by liu21st** [comment]
@dotku 你的build文件是不是没有放入application目录

**Comment by dotku** [comment]
@liu21st 有的，我还做了一个 testThink5 的 git https://github.com/dotku/testThink5

**Comment by liu21st** [comment]
@dotku  我测试自动生成没有发现问题啊 你的常量APP_AUTO_BUILD没有定义 不是定义配置参数

**Comment by dotku** [comment]
@liu21st 手册内容要更新一下了 http://www.kancloud.cn/thinkphp/thinkphp5-guide/90123 其实也可以考虑手册众包编写，不一定都要官方来编写~

**Comment by liu21st** [comment]
@dotku  看云的文档本来就支持团队和文档成员的 届时欢迎大家加入编写小组
