### ISSUE TITLE
org模块移到哪里去了，肿么不见了

### ISSUE THREAD

**Issue by uubos** [top-think/think#139]

**Comment by liu21st** [comment]
现在org等扩展类库有两个地方可以选择
1 放入LIB_PATH
2 放入EXTEND_PATH
并且不会改变原有的命名空间定义 都支持自动加载

**Comment by uubos** [comment]
还是麻烦把org模块里的类库先放到这两个目录中的其中一个去，我现在有用到，再做测试~

**Comment by liu21st** [comment]
自己放就行了啊 类库都在thinkphp-extend 项目仓库
