### ISSUE TITLE
D方法依然很难在IDE中提示自定义的方法啊

### ISSUE THREAD

**Issue by Fallsleep** [top-think/think#14]
看了下D方法，发现是用的Loader::model()，底层的实现没有太大的差别，依然是new $class($name);或者new Model($name);，这样在Zend Studio之类的IDE里面，很难提示自定义的方法，好痛苦啊。
为什么不在Model中写个获取实例的方法啊。

**Comment by zhbitcxy** [comment]
我觉得直接使用new好，不过代码需要改动

![image](https://cloud.githubusercontent.com/assets/7466548/13372513/e08a7fde-dd80-11e5-8c31-6364ec07ac1a.png)
