### ISSUE TITLE
最新版的模板引擎解析有误

### ISSUE THREAD

**Issue by benaheng** [top-think/think#141]
{$vo.name} 会被解析成$vo->name;

解析后的代码:<?php echo !empty(is_array($vo)) ? $vo['name']:$vo->name; ?>

$vo是数组 也不等于空 按说是$vo['name']才对  但问题就出在了!empty上

**Comment by benaheng** [comment]
extend标签也失效了

**Comment by kinosang** [comment]
是否是github最新版？

**Comment by benaheng** [comment]
是github最新版 你可以试试嘛

**Comment by liu21st** [comment]
@benaheng 可以重新测试下最新的更新
