### ISSUE TITLE
模板继承 绝对路径的话就无效了

### ISSUE THREAD

**Issue by benaheng** [top-think/think#148]
{extend name="apps/admin/view/common/main.html"/}

上面这块代码在3.2上可以成功解析 但是在5.0上就解析不了了
经过排查 是正则没匹配到

**Comment by liu21st** [comment]
你这个不是绝对路径吧 使用文件名定义的话 要完整路径。要注意的是 5.0的入口文件和3.2的入口文件的位置区别 所以相对入口文件的路径是不同的。不建议用这样的方式 继承

**Comment by benaheng** [comment]
@liu21st  可在3.2下这个是可以被正常解析的  另外 5.0的入口文件和3.2的入口文件不都是index.php么

**Comment by liu21st** [comment]
@benaheng 入口文件的路径相对于应用目录是不同的

**Comment by benaheng** [comment]
@liu21st  没明白 
我试过 {extend name="./apps/admin/view/common/main.html"/}和{extend name=APP_PATH."/admin/view/common/main.html"/}

都不行, 难道非要写上完整的物理路径?  我现在想调用其他应用下某个目录的模板文件该怎么操作?

**Comment by liu21st** [comment]
@benaheng 最新的更新 再测试下看看
