### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by taozhipeng1990** [top-think/think#154]
希望操作数据库能使用Doctrine2那样的模式
都是在操作类。
Doctrine2 的那个关联模式用起来感觉比Tp3.2的好用很多

**Comment by liu21st** [comment]
个人觉得如果说 TP要照搬Doctrine的话 就没有意义了 TP的ORM也并非没有自己的特点，我们也会坚持完善，何况ORM本来就是可以自己选择的，框架也没强制你用 TP5各个模块的依赖已经非常小了

**Comment by taozhipeng1990** [comment]
TP其实做的很好。用了许多框架。还是感觉TP好用。
但是关于在数据库的关联操作上还是有很大的可以完善的空间。
只是菜鸟的一些见解。
希望在TP5中能看到更完美的TP。
关于onethink的项目，感觉也很不错。
我个人是比较喜欢用onethink的。
只是onethink将bootstrap样式自定义了，感觉做起来不是很爽。希望还是原样的好。
祝THINKPHP越来越好

**Comment by slince** [comment]
@liu21st  tp目前所有的核心类都放在同一个目录下、一个大C方法遍布全局怎么能说依赖非常小呢；
解决高耦合的唯一办法就是采用分包，废弃自定义的全局方法；然后这两点一开始就是tp的标记；尤其是tp引以为傲的单字母函数；还有orm，orm在表关联以及复杂的查询条件的构建上的解决方法真的很另类

**Comment by liu21st** [comment]
@slince 核心不依赖大C函数的 那是新版提供的助手函数（帮助3.2用户而已） ORM关联需要改进
