### ISSUE TITLE
mac下 怎么注释了代码 程序执行的时候还是之前的缓存？

### ISSUE THREAD

**Issue by hee93** [top-think/think#170]
<?php
namespace app\index\controller;
use think\Controller;
class Index extends Controller
{
    public function index()
    {
    	//echo 2;
    	$data = M("Admin")->select();
    	dump($data);
    	echo 1;
    	//return $this->fetch();
    }
}

是不是要配置点什么

**Comment by kinosang** [comment]
开了opcache？多刷新几次试试

**Comment by hee93** [comment]
对喔 刚发现 谢谢
