### ISSUE TITLE
路由解析问题

### ISSUE THREAD

**Issue by QiiSyhx** [top-think/think#171]
\think\Route::group('admin', [
	'index' => ['admin/index/index', ['method' => 'get'], []],
	'login' => ['admin/index/login', ['method' => 'get'], []],
]);
定义路由之后，U函数生成的URL就有问题，
U('index/index') =》 admin/index/index
U('index/login') => admin/index/login
但是admin/index/login这个路由是没有定义的。因此会产生错误。
U('/admin/login')=>admin/login.html，如此路由才对的上。
这样存在的问题就是，两种方式不兼容。如果选定了一种方式，以后就不能切换了。

**Comment by liu21st** [comment]
现在的Url生成类已经完美解决了
