### ISSUE TITLE
路由直接使用Route类定义，个人感觉更好些

### ISSUE THREAD

**Issue by pwf0112** [top-think/think#174]
APP_PATH路径下的route.php中直接使用Route类定义应用路由，个人感觉比用路由配置文件定义要方便很多，而且更容易理解。
另外我有个疑问，恳请官方解答一下：
Route::get('user/:id', 'index/user/get');
Route::post('user/:id', 'index/user/post');
如果用配置文件定义，该怎么写？
[
    'user/:id' => ['index/user/get',  ['method' => 'get']],
    'user/:id' => ['index/user/post',  ['method' => 'post']],
]
这样写肯定不行，键名会被覆盖。

**Comment by liu21st** [comment]
[
 ['user/:id','index/user/get', ['method' => 'get']],
 ['user/:id','index/user/post', ['method' => 'post']],
]

**Comment by liu21st** [comment]
而且你完全可以在route文件里面用route类注册定义路由的

**Comment by pwf0112** [comment]
@liu21st 恩 是这样的。看来我还是太年青了，要好好研究才行。
'[blog]'     => [
        ':id'   => ['Blog/read', ['method' => 'get'], ['id' => '/\d+/']],
        ':name' => ['Blog/read', ['method' => 'post']],
    ],
写成：
'[blog]'     => [
        [':id' ,'Blog/read', ['method' => 'get'], ['id' => '/\d+/']],
        [':name' , 'Blog/read', ['method' => 'post']],
 ],
应该也是可以的吧。

**Comment by liu21st** [comment]
@pwf0112 可以的

**Comment by pwf0112** [comment]
@liu21st 好。知道了，谢谢。
