### ISSUE TITLE
F()方法取消了吗?

### ISSUE THREAD

**Issue by momoca** [top-think/think#178]
F()方法取消了吗?为什么在helper里没有?

**Comment by liu21st** [comment]
F方法的功能改由 配置simple类型的缓存驱动来实现了

**Comment by momoca** [comment]
simple,说明文档里并没有休现.能大概说说吗?

**Comment by liu21st** [comment]
只是一个驱动而已 和用其他的缓存驱动一样的用法啊，区别就在于 simple驱动 不支持缓存有效期

**Comment by momoca** [comment]
\think\Cache::connect($options);中的type为simple.对吧.然后使用S()来操作.我理解的对吗?

**Comment by momoca** [comment]
希望有时间更新一下http://www.kancloud.cn/thinkphp/thinkphp5-guide/90119的文档.
