### ISSUE TITLE
 Fatal error: Using $this when not in object context inthinkphp\library\think\log\driver\Socket.php on line 141

### ISSUE THREAD

**Issue by kbitlive** [top-think/think#199]
![image](https://cloud.githubusercontent.com/assets/12296964/12328439/6a3a445e-bb16-11e5-8465-6e920dbd0569.png)
![image](https://cloud.githubusercontent.com/assets/12296964/12328472/7d164604-bb16-11e5-95a0-b794778e714f.png)

static

**Comment by kbitlive** [comment]
[ 10001 ] class [ app\index\controller\Index ] not exists


github 打包下载 出错

**Comment by liu21st** [comment]
@kbitlive 你检查下类文件（严格大小写是否一致）

**Comment by kbitlive** [comment]
恩 好的
