### ISSUE TITLE
支持php7

### ISSUE THREAD

**Issue by w3yyb** [top-think/think#20]
php7快发布了,希望 不要基于php5.4了,直接基于php7

**Comment by kinosang** [comment]
PHP 5.4 5.6 5.6 7.0 之间改进并不很多，只要注意将 spilt 等弃用的函数替换成仍然继续支持的函数就好。

**Comment by w3yyb** [comment]
还 说不多,改动太大了

**Comment by kinosang** [comment]
@w3yyb 事实上，ThinkPHP 3.2可以完美运行在PHP7环境上（亲测）

**Comment by w3yyb** [comment]
那也没有 用新特性啊
