### ISSUE TITLE
 希望tp 开发组 写一个 console 

### ISSUE THREAD

**Issue by parkshinhye** [top-think/think#214]
就是命令 ，
参考 sf laravel。

用途可以有 创建模块 创建model 创建console 创建。。。。

这个用途很多！！！

**Comment by liu21st** [comment]
已经有了的啊~

**Comment by parkshinhye** [comment]
@liu21st  关于数据这块 有没有新功能例如 迁移用的结构表等！！！还有测试用的假数据生成！！！

**Comment by kinosang** [comment]
@parkshinhye 这方面我和 @yunwuxin 以及其他几个人正在做。如果你感兴趣也可以参与进来

**Comment by vus520** [comment]
代码迁移可以直接引入 robmorgan/phinx，功能文档可以查询https://phinx.org/

**Comment by kinosang** [comment]
合并到 #133
