### ISSUE TITLE
我来TP5提问了。。

### ISSUE THREAD

**Issue by hulang** [top-think/think#223]
1、只能通过：public访问首页是吗？

xxxxxxx/public/

**Comment by kinosang** [comment]
请将 public 设置为网站根目录

**Comment by hulang** [comment]
那他没有权限访问上级目录啊。。。。。。。。。。。。。

**Comment by kinosang** [comment]
为什么要访问上级目录？所有可供访客访问的文件都应该放到 `public` 目录下，框架、appliaction等文件属于敏感文件，不应当允许访客访问

**Comment by hulang** [comment]
老大。我的意思是。public 目录下的index.php。
都设置public为根目录了。。他还有访问上级目录的权限吗？

**Comment by kinosang** [comment]
有的。
php 的文件访问权限跟 web 根目录的设置无关，如果要限制 php 的访问范围，需要用 `php.ini` 或者 `.user.ini` 中专门设置。
