### ISSUE TITLE
项目格式化代码工具是什么？

### ISSUE THREAD

**Issue by muxiaokun** [top-think/think#234]
RT

**Comment by kinosang** [comment]
代码格式化标准：PSR2
自动加载和命名规范标准：PSR4

代码格式化工具：phpfmt

参数：

```json
{
	"enable_auto_align": true,
	"indent_with_space": true,
	"psr1_naming": true,
	"psr2": true,
	"version": 1
}
```

**Comment by muxiaokun** [comment]
谢谢
期待新的thinkphp5
ps:能把这个工具说明放到贡献方法中就好了

**Comment by muxiaokun** [comment]
@kinosang 我找到了一个更方便的格式化方法，因为我不用sublime
https://github.com/FriendsOfPHP/PHP-CS-Fixer.git
这个项目可以在命令行下执行扫面现在的整个thinkphp5项目只要25s,命令如下
php php-cs-fixer.phar fix --fixers=concat_with_spaces,align_equals think
结果和你给我的一样，但是可以跨平台下个1.3MB的脚本即可

**Comment by muxiaokun** [comment]
--fixers=concat_with_spaces,align_equals,align_double_arrow
