### ISSUE TITLE
这段代码是不是有点不妥

### ISSUE THREAD

**Issue by benaheng** [top-think/think#235]
// 开启调试模式Win环境严格区分大小写
            // 模板不存在 抛出异常
            if (!is_file($template) || (APP_DEBUG && IS_WIN && realpath($template) != $template)) {
                echo $template."<br>";
                echo realpath($template);die;
                throw new Exception('template file not exists:' . $template, 10700);
            }

这样虽然是为了严格区分大小写 但是没考虑到 在Win下 的路径符号的问题吧

上面的代码会在win下会抛出异常是因为 :
E:\upupw\htdocs\cms/app/common/view/common/jump.html
E:\upupw\htdocs\cms\app\common\view\common\jump.html

**Comment by benaheng** [comment]
如果仅仅是严格限制文件名大小写 是不是该再用basename处理下

但是我觉得后面判断根本没必要  因为is_file不就可以判断文件存不存在了 
在linux下 如果有大小写 它该抛出异常还是抛出啊   所以有点不明白为什么要这么做 
请指教一下

**Comment by liu21st** [comment]
你的情况应该是 指定了完整的模板文件 我改了下
