### ISSUE TITLE
模型验证最后一个参数未设置默认值

### ISSUE THREAD

**Issue by benaheng** [top-think/think#236]
今天发现之前写的验证都失效了,经过排查,原来不知道从什么时候起 最后一个参数必须写明 没写的话就验证不了了

**Comment by 1459416736** [comment]
就是啊，不设置默认值，整个项目都不能运行了，晕得要死

**Comment by kinosang** [comment]
链接到 #273

**Comment by 1459416736** [comment]
哎，第4个参数是不是要求必须写啊，这样项目中有太多没有写的了，都不能运行啊，什么时候修复下啊

**Comment by kinosang** [comment]
这个问题是由于之前一个“错误忽略”设置相关改进造成的，默认notice和warning会直接抛出错误中断程序，你可以设置`exception_ignore_type`来忽略这些报错（参见 #265 ）。

现在正在处理程序默认值相关问题。
