### ISSUE TITLE
设置路由为强制模式，依然要设置首页的路由，不然会报错。

### ISSUE THREAD

**Issue by DarthPestilane** [top-think/think#237]
![image](https://cloud.githubusercontent.com/assets/15375753/12605944/696dcfbc-c504-11e5-9a11-e428eacdd0dc.png)
上面是手册里的

这里依然要设置首页的路由。不然会报route not define的错误。

**Comment by liu21st** [comment]
最新的版本 首页也需要设置路由了的~

**Comment by liu21st** [comment]
手册的细节尚未更新到位，抱歉

**Comment by DarthPestilane** [comment]
感谢Owner的及时回复。
