### ISSUE TITLE
很多函数声明和doc备注不对应

### ISSUE THREAD

**Issue by justmd5** [top-think/think#24]
很多函数声明和doc备注不对应，比如这个：/**
     \* 发送HTTP请求方法，目前只支持CURL发送请求
     \* @param  string $url    请求URL
     \* @param  array  $params 请求参数
     \* @param  string $method 请求方法GET/POST
     \* @return array  $data   响应数据
     */
    protected function http($url, $params, $method = 'GET', $header = [], $multi = false)

**Comment by kideny** [comment]
欢迎提交commit

**Comment by XiaoXuanBing** [comment]
@kinosang 这里需要改吗？ #392  
这个不是注释问题

**Comment by kinosang** [comment]
@XiaoXuanBing #392 上的指向已经删掉，但是这边的没法删除
