### ISSUE TITLE
关于模板地址解析这里 还是有点bug

### ISSUE THREAD

**Issue by benaheng** [top-think/think#253]
因为要跨模块调用模板 我直接用$this->fetch(APP_PATH.'admin/view/common/test.html')

当这个模板不存在的时候 框架的报错地址是:/www/web/tp5/app/process/view//www/web/tp5/app/weixin/view/common/test.html.html

实际上 当这个模板存在的时候 解析的路径是对的 就是不存在的时候 报错路径不对

应该是/www/web/tp5/app/weixin/view/common/test.html 才对

**Comment by liu21st** [comment]
顺便说下 跨模块可以使用 fetch('admin@common/test')
