### ISSUE TITLE
rc1 开启API模式 出现bug

### ISSUE THREAD

**Issue by hee93** [top-think/think#256]
我在配置文件里头 添加 default_return_type 然后 刷新页面 它就返回带有json 跟 带有 showPageTrace的相关html代码
return [
    'default_return_type'=>'json',
    'url_route_on' => true,
    'log'          => [
        'type'             => 'trace', // 支持 socket trace file
        // 以下为socket类型配置
        'host'             => '111.202.76.133',
        //日志强制记录到配置的client_id
        'force_client_ids' => [],
        //限制允许读取日志的client_id
        'allow_client_ids' => [],
    ],

];

**Comment by liu21st** [comment]
api模式下面不要配置trace日志类型

**Comment by hee93** [comment]
ok
