### ISSUE TITLE
一个用配置设计不合理之处

### ISSUE THREAD

**Issue by benaheng** [top-think/think#259]
应用总目录(application)下有个config.php  这个配置文件 有个二级配置 并且配置选项非常多

总目录下的admin应用下有个config.php  这个配置仅仅修改了总配置文件中二级配置里面的一项

可是这样 用\think\Config::load载入后  其他的二级配置全没了  我不可能为了修改这一个配置 而把其他配置选项也都写出来吧   所以这块是不是考虑载入后用array_merge合并下

**Comment by liu21st** [comment]
改进了下~

**Comment by benaheng** [comment]
真速度  赞一个!!
