### ISSUE TITLE
RC1版本在使用URL路由闭包支持时报异常

### ISSUE THREAD

**Issue by 5ini99** [top-think/think#261]
**ErrorException in Url.php line 264**
strpos() expects parameter 1 to be string, object given
>                        $route = strstr($route, '?', true);
                    }
                    $var             = self::parseVar($rule . '/' . $key);
                    $alias[$route][] = [$rule . '/' . $key, $var];
                }
            } else {
                $route = $val['route'];
                if (is_array($route)) {
                    $route = implode('\\', $route);
                } elseif (strpos($route, '?')) {  // 该句有问题
                    $route = strstr($route, '?', true);
                }
                $var             = self::parseVar($rule);
                $alias[$route][] = [$rule, $var];
            }
        }
        Cache::set('think_route_alias', $alias);
        return $alias;
    }

**Comment by liu21st** [comment]
已经修正
