### ISSUE TITLE
随便报一个exception异常，日志会记录两条

### ISSUE THREAD

**Issue by hugtale** [top-think/think#269]
我本地日志用file记录。报路由未定义异常或者E()函数随便报一个异常，都会记录两条日志，如下是调用E(‘aaaa')报的异常：

[ 2016-02-02T10:01:47+08:00 ] 127.0.0.1 127.0.0.1 /
[log] think.tale.com/ [运行时间：0.018001s] [吞吐率：55.55req/s] [内存消耗：902.80kb] [文件加载：19]
[error] [0]aaaa[D:\PHPWeb\think\thinkphp\helper.php:172]

[ 2016-02-02T10:01:47+08:00 ] 127.0.0.1 127.0.0.1 /
[log] think.tale.com/ [运行时间：0.025002s] [吞吐率：40.00req/s] [内存消耗：880.45kb] [文件加载：20]
[info] [ CONFIG ] D:\PHPWeb\think\thinkphp\convention.php
[info] [ CONFIG ] D:\PHPWeb\think\application\config.php
[info] [ CONFIG ] D:\PHPWeb\think\application\database.php
[info] [ CONFIG ] D:\PHPWeb\think\application\route.php
.....

顺便问一下，日志中会有两个127.0.0.1是问题吗？

**Comment by kinosang** [comment]
使用单字母助手函数确实会产生两条记录

**Comment by hugtale** [comment]
这是开启  'url_route_must'=> true  后报的异常，也是两条日志记录：

[ 2016-02-02T11:05:04+08:00 ] 127.0.0.1 127.0.0.1 /
[log] think.tale.com/ [运行时间：0.018002s] [吞吐率：55.55req/s] [内存消耗：879.98kb] [文件加载：18]
[error] [0]route not define [D:\PHPWeb\think\thinkphp\library\think\App.php:388]

[ 2016-02-02T11:05:04+08:00 ] 127.0.0.1 127.0.0.1 /
[log] think.tale.com/ [运行时间：0.023002s] [吞吐率：43.47req/s] [内存消耗：865.11kb] [文件加载：19]
[info] [ CONFIG ] D:\PHPWeb\think\thinkphp\convention.php
[info] [ CONFIG ] D:\PHPWeb\think\application\config.php
[info] [ CONFIG ] D:\PHPWeb\think\application\database.php
[info] [ CONFIG ] D:\PHPWeb\think\application\route.php

**Comment by liu21st** [comment]
这块改进了下

**Comment by hugtale** [comment]
E函数能优化一下吗？支持自定义的异常类型，还可以传参数
