### ISSUE TITLE
自动创建字段数据会报错啊

### ISSUE THREAD

**Issue by 1459416736** [top-think/think#271]
$this->auto= array(array('create_time', NOW_TIME, self::MODEL_INSERT));
上面是自动创建字段数据的代码
ErrorException in Auto.php line 192
Undefined offset: 3

**Comment by 1459416736** [comment]
不设置默认值，整个项目都不能运行了，晕得要死

**Comment by kinosang** [comment]
设置忽略warning

**Comment by liu21st** [comment]
修正了

**Comment by 1459416736** [comment]
我刚刚更新了最新的包，还是一样报错啊，第四个参数没有默认值啊

**Comment by Aoiujz** [comment]
要是吓折腾，欢迎折腾然后报告问题， 如果是实际项目，建议你设置忽略 Notice 基本的错误 ， 看来TP 核心中还有很多不规范的代码啊啊啊啊。。。

**Comment by kinosang** [comment]
@Aoiujz 确实，经常可见notice和warning级别报错。

**Comment by kinosang** [comment]
链接到 #273
