### ISSUE TITLE
new 一个不存在的类，所显示的异常信息是3个php自带的异常信息。而不是显示 think_exception.tpl

### ISSUE THREAD

**Issue by hugtale** [top-think/think#275]
随便 new aaaa;好了。就会报3个异常信息。当前设的exception_ignore_type 是 0

Fatal error: Class 'app\index\controller\aaaa' not found in D:\PHPWeb\think\application\index\controller\Index.php on line 8

Fatal error: Uncaught exception 'think\exception\ErrorException' with message 'Missing argument 5 for think\exception\ErrorException::__construct(), called in D:\PHPWeb\think\thinkphp\library\think\Error.php on line 121 and defined' in D:\PHPWeb\think\thinkphp\library\think\exception\ErrorException.php on line 38

 think\exception\ErrorException: Missing argument 5 for think\exception\ErrorException::__construct(), called in D:\PHPWeb\think\thinkphp\library\think\Error.php on line 121 and defined in D:\PHPWeb\think\thinkphp\library\think\exception\ErrorException.php on line 38

**Comment by liu21st** [comment]
已经修正

**Comment by hugtale** [comment]
不能完全隐藏掉php自带的错误提示吗？下面这句提示还是存在：

Fatal error: Class 'app\index\controller\aaaa' not found in D:\PHPWeb\think\application\index\controller\Index.php on line 8
