### ISSUE TITLE
关于自定义标签库这里  

### ISSUE THREAD

**Issue by benaheng** [top-think/think#277]
我自定义了个 list 标签 

 {list catid="0"}
                <li>testtest</li>
{/list}

解析的时候 我写的是 

  public function _list($tag,$content){
        $catid  = intval($tag['catid']);
        if(!$catid){
            $content='list标签缺少catid参数';
            return $content;
        }
}

不知道是哪里的原因 这里并没有得到我想要的结果 而是直接忽略了解析

把标签直接显示出来了

另外 标签这里必须得写一个attr 感觉不太好吧  有时候即使用户没填写 全都用默认的 
比如 {list} test{/list} 这样的话就直接报错了

**Comment by oldrind** [comment]
自定义标签库除非声明成内置标签，不然在使用标签时需要以'类名:'为前缀。定义标签时也设置成不需要属性的，可参考Cx类中一些标签的定义方法。
