### ISSUE TITLE
include进的文件中如果有block标签，不会被解析

### ISSUE THREAD

**Issue by hugtale** [top-think/think#281]
include进的文件中如果有block标签，不会被解析。想问一下这算不算问题，还是有其他途径？

**Comment by hugtale** [comment]
这问题在官网问了好几遍了，一直没得到答复。所以来这问问^_^

**Comment by kinosang** [comment]
是否是 git 最新版？

**Comment by hugtale** [comment]
是的！

**Comment by oldrind** [comment]
extend标签和block标签配合可以进行多级继承，但并不支持在include进来的文件中再使用extend和block标签。什么样的需求让你想要这样来组织标签？

**Comment by hugtale** [comment]
我这可是学的onethink啊！

**Comment by kinosang** [comment]
onethink似乎也没有这种组织方式

**Comment by hugtale** [comment]
有的，onethink的默认Home模块下的模板就是这样组织的

**Comment by oldrind** [comment]
说一下你是想达到什么样的效果。用extend和block不能解决？现在并不支持在include标签中再用block。

**Comment by hugtale** [comment]
smarty引擎也是支持这样的写法的。。。我的目的是为了封装而封装。。。好笑不？囧rz

**Comment by kinosang** [comment]
@hugtale 你可以自行封装一个 Smarty 的 view，并不困难

**Comment by hugtale** [comment]
smarty易用性没你们的好！

**Comment by oldrind** [comment]
在我看来include中支持再套block标签作用不大，还要多增加一次解析过程，所以设计上并不支持这样的用法。你这么用了，所以我想弄清哪种情况让你有这种需求，看看用别的标签能不能解决问题。只是你既不说明你的应用情况，却只是在强调别的系统是支持这样用的，这要如何沟通呢？

**Comment by hugtale** [comment]
哦，不好意思让你困惑了。目前没有实际的应用场景，最主要原因还是从onethink那套代码学来的，后来用了smarty，发现也可以这么用，所以一直就习惯这么用了。但现在tp5居然不能这样用了，所以我就提问了。暂时就关了这问题好了，说不定有了tp5以后我也不这么用了，呵呵

**Comment by FengData** [comment]
需求场景很明确 怎么没有 onethink那套很清晰  base中只有基础的include  include中再加载block  难不成都写到一个大文件中block   再extend
