### ISSUE TITLE
修改模型类中使用addAll方法时，第三个replace参数无效问题

### ISSUE THREAD

**Issue by 5ini99** [top-think/think#284]
解决方案
文件
`thinkphp/library/think/db/Driver.php`
第950行
`$sql = 'INSERT INTO ' . $this->parseTable($options['table']) . ' (' . implode(',', $fields) . ') ' . implode(' UNION ALL ', $values);`
修改为
`$sql = (true === $replace ? 'REPLACE' : 'INSERT') . ' INTO ' . $this->parseTable($options['table']) . ' (' . implode(',', $fields) . ') ' . implode(' UNION ALL ', $values);`

**Comment by kinosang** [comment]
github 是开放的协作平台，你可以直接在github上浏览到该文件并点击右上角的铅笔图标编辑文件，管理组会在review代码后合并你的修改。

因代码修改署名和相关追溯问题，原则上管理组不copy & paste issue中提出的修改

**Comment by 5ini99** [comment]
@kinosang 3Q，已修改
