### ISSUE TITLE
一个改进想法,但是不知道是否应该合并

### ISSUE THREAD

**Issue by zizhilong** [top-think/think#288]
我这里的团队在使用THINKPHP时,遇到过要在单次执行中插入或者修改大量的数据
即便使用addAll,也不太适合.当时的思路是写了3个扩展方法,
插入
$m=M('要插入数据的表');
foreach($datas as $data)
{
       $m->bAdd($data);
}
$m->bUpdate();
更新
$m=M('要插入数据的表');
foreach($datas as $data)
{
       $m->bSave(array('id'=>$data['id
[Uploading Model.class.zip…]()
'],'更新的字段'=>$data['val']);
}
$m->bUpdate();

b指的是bulk
在逻辑内部,插入和修改请求会被缓存起来,当积累到一定程度,执行一次insert或update 
更新使用的是case when
做一次性百万条数据插入这个是我能找到最快的办法.

so 我想说的意思是,这种需求是否适合作为一个model的traits如果适合我可以写写看

**Comment by zizhilong** [comment]
`	private function bSaveUpdate($key,$where)
	{
		//对等于 累计加，累计减做处理
		$row = $key;
		$row =$this->db->parseKey($row);
		$row .='=';
		//如果是加号开始，表示在原字段上累加
		if(strpos($key,'+')!==false)
		{
			$t_row=substr($key,0,strlen($key)-1);
			$row=$this->db->parseKey($t_row);
			$row=$row.'='.$row.'+';
		}
		//如果是减号开始，表示在原字段上减少
		if(strpos($key,'-')!==false)
		{
			$t_row=substr($key,0,strlen($key)-1);
			$row=$this->db->parseKey($t_row);
			$row=$row.'='.$row.'-';
		}
		$datasql='';
		$dataids='';

		
		foreach($this->bSaveData[$key] as $datakey=>$dataval)
		{
			$datasql.=" WHEN " .$datakey." THEN '".$dataval."'";
			$dataids.=$datakey.',';
		}
		unset($this->bSaveData[$key]);
		unset($this->bSaveSize[$key]);
		if(is_array($where))
		{
			throw_exception("在做批量更新时条件不支持数组型");
		}
		if($where != '')
		{
			$where=' and ('.$where.')';
		}
		$this->execute('UPDATE '.$this->trueTableName . ' set '.$row.' CASE '.$this->pk.' '.$datasql.' END where '.$this->pk.' in ('.trim($dataids,',').')'.$where);
	}
	public function bUpdate()
	{
		//处理插入缓存
		if($this->bInsRSql)
		{
			$this->execute($this->bInsLSql.$this->bInsRSql);
			$this->bInsRSql='';
		}
		$this->bInsLSql='';
		//处理批量更新缓存
		$options =  $this->_parseOptions(array());
		foreach($this->bSaveData as $key=>$val)
		{
			$this->bSaveUpdate($key,isset($options['where']) ? $options['where'] : '');
		}
	}`

**Comment by liu21st** [comment]
当然可以 tratis以后都是很灵活扩展的

**Comment by zizhilong** [comment]
我是说作为TP5.0正式版的一部分

**Comment by liu21st** [comment]
@zizhilong 这块等出来后可以在核心群里面讨论下是否纳入核心
