### ISSUE TITLE
当post某个变量是数组的时候，使用I函数拿到的返回值有问题

### ISSUE THREAD

**Issue by qiqizjl** [top-think/think#291]
当我Post到中某个变量是数组的时候。。。使用I函数获取返回是(string)Array 无法获得数组具体内容

如图
Post内容
![image](https://cloud.githubusercontent.com/assets/7540584/12999976/0e0f9676-d190-11e5-9fc3-d983acc26522.png)

 使用I函数获取到的内容是
![image](https://cloud.githubusercontent.com/assets/7540584/12999979/17812e72-d190-11e5-9412-75bc70da7d47.png)

使用$_POST获取到的是
![image](https://cloud.githubusercontent.com/assets/7540584/12999991/2939fe32-d190-11e5-9be6-47547793acbd.png)

**Comment by liu21st** [comment]
这是故意设计的 为了安全起见，必须使用 /a 变量修饰符来获取数组变量

**Comment by 5ini99** [comment]
涨知识啦，昨天也遇到同样的问题
