### ISSUE TITLE
能否写一个重构后的模型自动验证自动完成的例子?

### ISSUE THREAD

**Issue by benaheng** [top-think/think#295]
写个简单的例子就成

**Comment by liu21st** [comment]
$Model = M('User');
$result = $Model->validate([
    // name和age是需要验证的字段名
    'name'=> ['\w{4,32}','用户名不符合规范'],
    'age' => ['\d+','年龄不符合规范'],
])->auto([
    'status'=> 1, // 
    'create_time' => ['time','callback'],
])->create();

if(!$result){
    // 验证失败 返回错误信息
    return $Model->getError();
}else{
    $Model->add();
}

**Comment by liu21st** [comment]
另外 新版的自动验证和自动完成 也同样适用于add和save方法 可以不依赖create方法

**Comment by benaheng** [comment]
谢谢,我看新版的model貌似功能更强大了 期待手册的完善
