### ISSUE TITLE
不知道是bug 还是设计如此

### ISSUE THREAD

**Issue by benaheng** [top-think/think#296]
我定义了一个模型 content  模型里有个方法 setcatid

该方法的代码如下 

    public function setCatid($catid){
        $this->category=D("Category")->find($catid);
        $this->info=D('Models')->find($this->category['mid']);
        $this->tableName=$this->info['app']."_".$this->info['tablename'];
        $this->pk=$this->info['pk'];
        $this->extTableName=C('database.prefix').$this->info['app']."_".$this->info['tablename']."_data";
        $this->extModel=D(ucfirst($this->info['app']).ucfirst($this->info['tablename'])."Data");

    }

一个catid对应一个表  但是多次执行该方法的话 模型的读取操作 永远是第一此执行该方法得到的信息

比如第一次执行后 setCatid(1) 要操作的表是 tp_content_news

第二次执行 setCatid(2)后 操作的表还是上面那个  按说该切换到其他表吧?

**Comment by liu21st** [comment]
你动态改变 tableName是无效的 需要改变的是trueTableName属性
