### ISSUE TITLE
强烈建议TP新增单元测试。

### ISSUE THREAD

**Issue by Lofanmi** [top-think/think#30]
很多时候修改了代码，没有单元测试，会导致意想不到的结果，单元测试可以保证框架的稳定性和健壮性。

**Comment by liu21st** [comment]
单元测试会纳入扩展范畴 暂时不会在核心里面~ 目前首先会强化api开发及调试这块

**Comment by kideny** [comment]
开发人员太少了，为啥不吸引点外援来呢？

**Comment by liu21st** [comment]
@kideny 确实比较少 要不你加入一起来完成这块吧 ^_^

**Comment by kideny** [comment]
@liu21st  哈哈，我要是能做贡献，那真是极好的。

**Comment by yeahTibbers** [comment]
@liu21st 哪部分模块需要外援呢，最近有时间，给thinkphp贡献点代码也是极好的

**Comment by dingyiming** [comment]
好像tp在前端上，不打算做些什么引导的样子，是吧？

**Comment by lloydzhou** [comment]
写好测试用例之后，最好在集成一下travis-ci做一下自动化测试，另外还可以集成一下coverage显示测试代码覆盖率

类似我的一个库https://github.com/bephp/router#router 这里的图标的样子

**Comment by kinosang** [comment]
#82 #101
