### ISSUE TITLE
Response中的success和error方法都对url设了默认值，如果在ajax返回的情况下，体验不好！

### ISSUE THREAD

**Issue by hugtale** [top-think/think#300]
也就是说，每次ajax返回的success或者error数据中，都有url。我是要跳转呢，还是不要跳转呢？并非每次ajax请求都要跳转的吧？比如ajax提交表单并且后台返回error的时候，如果跳转了，那表单数据不就要重新填了？我希望是，在ajax提交的时候，如果我传了url，那后台返回的json数据中也有url，前端会跳转到指定的url；如果没传url，那返回的json数据中url就应该是空的，success时js刷新当前页，error时js不跳转不刷新。

**Comment by liu21st** [comment]
返回数据里面有url 不代表一定要跳转 完全看前端的代码 ajax返回 前端js代码不执行跳转 也不会跳转啊，error错误后的默认跳转就是返回上一页

**Comment by hugtale** [comment]
前端js代码，要不要跳转，我是以有没有非空的url字段为依据的。如果有，则跳转；如果没有，success时刷新当前页，error时不处理。这样的话，我就可以统一封装一个ajax请求的逻辑出来，可控性也相对好一些。不然的话，不知道要不要跳转，类似提交表单页面后的跳转逻辑就不清不楚了

**Comment by liu21st** [comment]
改进了下 可以支持空字符串传入

**Comment by hugtale** [comment]
感谢支持！
