### ISSUE TITLE
新的Model 自动验证自动完成怎么批量执行

### ISSUE THREAD

**Issue by 1459416736** [top-think/think#303]
我项目更新后全部报错

**Comment by liu21st** [comment]
新的自动验证之前的用法有所区别了 批量执行需要改为
~~~
$Model = M('User');
$result = $Model->validate([
    // name和age是需要验证的字段名
    'name'=> ['\w{4,32}','用户名不符合规范'],
    'age' => ['\d+','年龄不符合规范'],
    '__option__'=>['patch'=>true],
])->create();
~~~

**Comment by 1459416736** [comment]
我那个看都不对哦！该方法不是2个参数么，而头一个参数也不是数组啊
/**
     * 设置字段验证
     * @access public
     * @param mixed $field 字段名或者验证规则
     * @param array|null $rule 验证规则
     * @return Model
     */
    public function validate($field, $rule = null)
    {
        if (is_array($field) || is_null($rule)) {
            $this->options['validate'] = $field;
        } else {
            $this->options['validate'][$field] = $rule;
        }
        return $this;
    }

**Comment by liu21st** [comment]
第一个参数可以是数组
