### ISSUE TITLE
session的问题

### ISSUE THREAD

**Issue by freedomlizhigang** [top-think/think#306]
// 是否使用session
    'use_session'    => true,
    'session'        => [
        'id'             => '',
        'var_session_id' => '', // SESSION_ID的提交变量,解决flash上传跨域
        'prefix'         => 'think',
        'type'           => '',
        'auto_start'     => true,
        'expire'         => 7200,
        'path'           => APP_PATH . 'mzsj/session',
    ],

这个设置放在app下的config中起作用，直接放在模块下的config中'path','expire'不起作用，用C方法可以读出配置，但不起作用

查出原因来，是配置的加载顺序问题，
`[ CONFIG ] E:\wamp\www\TPCMS5\public/../app/config.php
[ CONFIG ] E:\wamp\www\TPCMS5\public/../app/database.php
[ CONFIG ] E:\wamp\www\TPCMS5\public/../app/route.php
[ SESSION ] INIT array ( 'id' => '', 'var_session_id' => '', 'prefix' => 'mz_', 'type' => '', 'auto_start' => true, 'expire' => 7200, 'path' => '', )
[ ROUTE ] array ( 'type' => 'module', 'module' => array ( 0 => 'mzsj', 1 => 'common', 2 => 'login', ), )
[ CONFIG ] E:\wamp\www\TPCMS5\public/../app/mzsj\config.php`
session 在模块配置加载进来以前就执行了初始化

**Comment by liu21st** [comment]
可以关闭 use_session 然后在需要的时候 调用session类init方法

**Comment by freedomlizhigang** [comment]
可以了  谢谢大神
总配置里关掉
'use_session'    => false,
用的时候
\think\Session::init(C('session'));
会起作用，如果不初始化直接赋值不起作用，看了下源代码，是session函数中设置方法使用的是session类中的set方法，set方法没有判断是否启动过sesssion了，所以也没有错误提示，但是设置不成功。
