### ISSUE TITLE
模块采用“common”、“public”、“error”等命名，访问时提示“module [ common ] not exists”

### ISSUE THREAD

**Issue by HuberyLee** [top-think/think#315]
模块采用“common”、“public”、“error”等命名，访问时提示
```
Exception in App.php line 202
module [ common ] not exists
```

**Comment by kinosang** [comment]
请不要使用保留关键字作为模块、控制器、model等的命名

**Comment by HuberyLee** [comment]
好的，我是看到手册上公共模块可使用common命名，所以就试了一下。

**Comment by kinosang** [comment]
公共模块是指共享给其他模块用的model、控制器父类等，并不是可以直接作为独立模块使用的。

**Comment by liu21st** [comment]
public是系统关键字，但error是可以作为模块名的应该 另外 common之所以不能访问是因为 系统对common做了特殊处理，主要是作为所有模块的公共类库目录设计用途，因此默认是禁止直接访问
~~~
    // 禁止访问模块
    'deny_module_list'       => [COMMON_MODULE, 'runtime'],
~~~
你需要修改配置才能访问common模块。

**Comment by HuberyLee** [comment]
好的，谢谢你们！
