### ISSUE TITLE
common.php程序文件引用而导致在内存中被重复加载时引发冲突

### ISSUE THREAD

**Issue by 1459416736** [top-think/think#319]
// 加载公共文件
            if (is_file($path . 'common' . EXT)) {
                include $path . 'common' . EXT;
            }
我更新框架就报错；Cannot redeclare  previously declared in

**Comment by hugtale** [comment]
public\index.php 看看是不是和官方的一样？

**Comment by liu21st** [comment]
最新的更新版本 入口文件默认不需要加上 \think\App::run()了
