### ISSUE TITLE
LINUX 部署后报错见图

### ISSUE THREAD

**Issue by 1459416736** [top-think/think#321]
https://workorder.console.aliyun.com/attach/note_attach.do?spm=5176.2020520129.105.6.49KyQz&id=22310149&order=0

**Comment by kinosang** [comment]
这个不是图，是你的控制台，只有你自己登录阿里云账号才能看到。你可以ssh链接后部署复制错误信息，或提供截图

**Comment by 1459416736** [comment]
我把那个路径的点去掉，路径就能找到了start.php了，不过后面就找不到module

**Comment by Lofanmi** [comment]
@1459416736 用户对目录是否没有读的权限?
