### ISSUE TITLE
日志生成问题

### ISSUE THREAD

**Issue by 1459416736** [top-think/think#328]
linux 平台部署后，APP_DEBUG 为true 情况，能生成日志文件
win7 开发平台部署后，APP_DEBUG 为true 情况，就是不能生成日志文件，请问是什么问题，同样的一套代码

**Comment by liu21st** [comment]
看下你的 日志配置是否一样

**Comment by 1459416736** [comment]
日志配置是一样的，同一套代码的嘛

**Comment by 1459416736** [comment]
哎，解决不了啊啊啊啊啊

**Comment by liu21st** [comment]
可以到官网贴下具体的配置代码
