### ISSUE TITLE
attrCase 怎么在配置文件配置值

### ISSUE THREAD

**Issue by 1459416736** [top-think/think#354]
model  类__construct 方法里的代码如下：

if (isset($config['attr_case'])) {
            $this->attrCase = $config['attr_case'];
        }
attrCase 怎么在配置文件配置值

**Comment by kinosang** [comment]
attr_case

**Comment by 1459416736** [comment]
我的问题是怎么在config.php 里配置 attr_case的值，我现在是直接写到每个model 类里的
