### ISSUE TITLE
增加shared memory cache驱动

### ISSUE THREAD

**Issue by lloydzhou** [top-think/think#360]
我看cache/driver目录下面已经有好多种类型的缓存，不过，我觉得还缺少直接使用shared memory的缓存驱动。
1. 和memcached，redis等比较，直接使用shared memory虽然在扩展性方面稍差，但是不用单独启动服服务，部署会比较方便。
2. 和file，db等cache比较，速度会快不少。
3. shm_*系列函数是PHP原生支持的，不需要安装extension。

这里贴一份，我之前写的一个函数，作为参考https://github.com/bephp/utils/blob/master/utils.php#L84
主要使用 shm_put_var，shm_has_var以及shm_get_var这几个API来实现

**Comment by xiaoxintiaoda** [comment]
我觉得你可以提一个pr,如果我感觉基本上提的pr,官方貌似都没有合并，我之前也提过一个memcached的长连接的pr,并没有什么用0_0

**Comment by liu21st** [comment]
@xiaoxintiaoda 现在驱动都不会纳入核心的 所以最好是单独走扩展
