### ISSUE TITLE
\think\Route::bind('module','index');这个配置绑定模块不能使用了吗？

### ISSUE THREAD

**Issue by hinet** [top-think/think#361]
<code>
// 绑定index模块
\think\Route::bind('module','index');
</code>
这个配置绑定模块不能使用了吗？

**Comment by hugtale** [comment]
http://www.kancloud.cn/manual/thinkphp5/118013

看最下面的“区分路由”，按这样绑定

**Comment by hugtale** [comment]
http://www.kancloud.cn/manual/thinkphp5/118003

这个
