### ISSUE TITLE
类方法return 问题

### ISSUE THREAD

**Issue by guoyahao** [top-think/think#363]
# config 配置

> return [
    'url_route_on' => true,
    'default_return_type'=>'html',
    'Template'=> [
    	'tpl_cache' => false
    ]
];

# 问题：

- 控制器：__construct 无法调用 Jump 下 error 方法

- 调用Jump类 执行 error 方法时 必须每次return 

类似：

>    namespace app\index\controller;

use traits\controller\Jump;

class test {
	
	var $is_login;
	
	use Jump;
	
	function __construct()
	{
		$this->is_login = false;
	
	    // 不执行页面跳转
		$this->error('您还没有登录，请先登录！','',U('User/login')); 
		
		// 不执行
		return $this->error('您还没有登录，请先登录！','',U('User/login')); 
	}

	public function index()
	{
		// 不执行页面跳转 仅仅返回HTML
		$this->error('您还没有登录，请先登录！','',U('User/login')); 
		
		// 执行
		return $this->error('您还没有登录，请先登录！','',U('User/login')); 
		
		// 测试 login 方法 
		self::login(); // 不执行
		
		// 测试 login2 方法 
		self::login2(); // 不执行
		return self::login2(); //执行
	} 
	
	/* 用户登录检测 */
	protected function login()
	{
		$this->is_login || $this->error('您还没有登录，请先登录！','',U('User/login')); 
	}
	
	/* 用户登录检测 */
	protected function login2()
	{
		if(!$this->is_login){
			return $this->error('您还没有登录，请先登录！','',U('User/login')); 
		}	
	}
	
}

是我写的问题？还是跳转需要处理的问题？

**Comment by hugtale** [comment]
看起来这个success和error方法很严重啊，不管有没有配置 `'response_auto_output' => false`，效果上和3.1、3.2还是有很大区别的

**Comment by liu21st** [comment]
控制器中使用return返回 然后由Response类统一输出这是新版的机制，但可以关闭自动输出 而由控制器自己输出 这样就不需要return 配置  'response_auto_output'   => false 即可，配置后和3.2的用法是一致的。 error和success方法默认都不会中断 需要自己处理添加exit

**Comment by hugtale** [comment]
@liu21st 要在构造函数中写success和error，是不是只能配置  'response_auto_output' => false 了？

**Comment by liu21st** [comment]
@hugtale 构造函数中要写success和error的话 最好是自己加exit
