### ISSUE TITLE
模板解析问题

### ISSUE THREAD

**Issue by QiiSyhx** [top-think/think#370]
{if condition="empty($info) || $info.status eq 1"} checked{/if}
解析后错误：
<?php if($info['status'](empty($info) ,= 1)): ?> checked<?php endif; ?>
这个函数的解析，可以换成别的字符吧，比如#号

**Comment by oldrind** [comment]
之前条件表达式中支持使用“$info|empty"这样的方式，这和||冲突，所以你那个写法就会出错；现已修改过来，比较标签表达式内能解析||运行算符，但表达式不再支持"|函数"的用法。
