### ISSUE TITLE
一处错误

### ISSUE THREAD

**Issue by XiaoXuanBing** [top-think/think#390]
`think/thinkphp/library/think/Template.php
$blocks[$parent]['content'] = str_replace($blocks[$name]['begin'] . $blocks[$name]['content'] . $blocks[$name]['end'], $replace, $blocks[$parent]['content']);

$blocks[$name] Undefined index
$val or $baseBlocks[$name]`

**Comment by kinosang** [comment]
能否详细描述该错误，或[提交 pr 帮助我们修复](https://github.com/top-think/think/blob/master/CONTRIBUTING.md)

**Comment by XiaoXuanBing** [comment]
block 多层嵌套，定义最外层就会出现Undefined index
$val 或者 $baseBlocks[$name] 替换$blocks[$name]就可以了，应该是笔误

**Comment by XiaoXuanBing** [comment]
@kinosang 好吧，知道了

**Comment by kinosang** [comment]
因为我没有做过block嵌套的应用，也没有关注默认模板的代码，这个问题你也可以等待其他人来处理。

**Comment by oldrind** [comment]
说一下你的标签是怎么用的，最好把代码贴一下

**Comment by XiaoXuanBing** [comment]
@oldrind 多层嵌套，然后再替换父block，$blocks这里面不存在$name ，$baseBlocks这里有

**Comment by oldrind** [comment]
少了$blocks[$name]是否存在的判断，已修复

**Comment by XiaoXuanBing** [comment]
@oldrind 今天又试了下，是不出错了，但是多层嵌套会直接输出父`{block}`
所以我又改回了我之前说的修改

**Comment by XiaoXuanBing** [comment]
@kinosang open
