### ISSUE TITLE
这里需要改吗？

### ISSUE THREAD

**Issue by XiaoXuanBing** [top-think/think#392]
/**
     * 自动定位模板文件
     * @access private
     * @param string $template 模板文件规则
     * @return string
     */
的返回路径修复了 return realpath($path) . DS . $template . $this->config['view_suffix'];
那这里需要改吗？
template.php
    /**
     * 解析模板文件名
     * @access private
     * @param  string $template 文件名
     * @return string|false
     */
    private function parseTemplateFile($template)
.........
$template = str_replace(['/', ':'], $this->config['view_depr'], $template);
$template = $path . $template . $this->config['view_suffix'];

**Comment by kinosang** [comment]
#24

**Comment by XiaoXuanBing** [comment]
这个不是注释错误，你们修复了Template自动定位模板文件路径返回中的/../，还有一个地方需要改！！

**Comment by hugtale** [comment]
@XiaoXuanBing 提交pr试试？

**Comment by kinosang** [comment]
@hugtale 他提交的pr因为同时处理了 #390 ，但是没能通过 CI 测试。

@XiaoXuanBing 如果可以，就这个问题重新提交一次pr可以么？

**Comment by XiaoXuanBing** [comment]
@kinosang block问题看到已经修复，这个我单独提了
