### ISSUE TITLE
没有了ROOT，静态文件路径有留有办法吗？

### ISSUE THREAD

**Issue by XiaoXuanBing** [top-think/think#393]
没了已下，怎么办？
```
if(!IS_CLI) {
    // 当前文件名
    if(!defined('_PHP_FILE_')) {
        if(IS_CGI) {
            //CGI/FASTCGI模式下
            $_temp  = explode('.php',$_SERVER['PHP_SELF']);
            define('_PHP_FILE_',    rtrim(str_replace($_SERVER['HTTP_HOST'],'',$_temp[0].'.php'),'/'));
        }else {
            define('_PHP_FILE_',    rtrim($_SERVER['SCRIPT_NAME'],'/'));
        }
    }
    if(!defined('__ROOT__')) {
        $_root  =   rtrim(dirname(_PHP_FILE_),'/');
        define('__ROOT__',  (($_root=='/' || $_root=='\\')?'':$_root));
    }
}
```

**Comment by kinosang** [comment]
能否详细描述这个问题？

**Comment by XiaoXuanBing** [comment]
'parse_str'=>[
        '__PUBLIC__'=>  __ROOT__ . '',
    ],
HTML head <link href="__PUBLIC__/css.css" rel="stylesheet" type="text/css">
没了以前的__ROOT__ 如何定义__PUBLIC__？
不同模式 ../ 结果不同，以前需要__ROOT__，现在给我们留了什么？

**Comment by kinosang** [comment]
5.0版推荐将 index.php 放在 public 目录中，然后将 public 作为网站根目录。

这样当你使用相对路径的时候，就是以 public 为基础了。

如果将 index.php 放到项目根目录的需求，自行修改 index.php 中对 thinkphp 目录的引用就好。

更多细节请参阅 5.0 文档。

**Comment by XiaoXuanBing** [comment]
放到哪里都没用的
url 
public/index.php/m/c
public/index.php/m/c/
public/m/c
public/m/c/
以上../写法后的路径都是不同的
@kinosang

**Comment by kinosang** [comment]
或者你可以在index.php中

```php
DEFINE('WEBROOT', __DIR__);
```

来定义一个常量

**Comment by XiaoXuanBing** [comment]
__DIR__ 这个是绝对路径吧

**Comment by kinosang** [comment]
你是否是需要生成 url ？生成 url 请使用内置的 `U()` 函数或 `\think\Url::build()` 方法来生成。

若是需要在 PHP 中对文件进行操作，用绝对路径是完全没问题的。

**Comment by XiaoXuanBing** [comment]
一楼的代码是老版本里的，解决的就是我说的问题，新版本没了，不知道提供了什么其他方法

**Comment by kinosang** [comment]
并没能具体理解你的意图。

**Comment by XiaoXuanBing** [comment]
那个方法没找到
我如果想在head调用一个css文件，该如何写呢，相对路径求教
`<link href="__PUBLIC__/admin/Bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css">`

**Comment by kinosang** [comment]
我大概了解你的需求了，解决方案是使用绝对路径。

在public目录是网站根目录的情况下（5.0推荐配置）：

`/admin/Bootstrap/css/bootstrap.css`

在项目根目录是网站根目录的情况下：

`/public/admin/Bootstrap/css/bootstrap.css`

**Comment by XiaoXuanBing** [comment]
如您说说，我得这样写/fan/public/admin
上线后得改为/admin
还是以前`__ROOT__ `好，什么情况都不用改。
我已加了原来方式，谢谢

**Comment by hugtale** [comment]
在配置文件中设置：
~~~
"parse_str" => [

    "__ROOT__" => "/fan/public/admin",    // 上线后改成/admin
    
    // 可以再配其他的...
],
~~~

控制器中 View 对象这样初始化就行（不管是Contoller中或是手动初始化）:
~~~
$view = new \think\View(\think\Config::get());
~~~

静态文件路径都这样写就行：`__ROOT__/base.css`
