### ISSUE TITLE
关于$this->error函数在_initialize中的使用

### ISSUE THREAD

**Issue by pysjp** [top-think/think#395]
function _initialize(){
		if(IS_AJAX && IS_GET) C('DEFAULT_AJAX_RETURN', 'html');
		self::checkLogin();
		self::checkPriv();
		self::operateLog();
		self::cookie();
	}

	private function checkLogin(){
		if(CONTROLLER_NAME =='Index' && in_array(ACTION_NAME, array('login', 'code'))) return true;

		if(!user_info('userid') || !user_info('roleid')){
                      return $this->error('请先登录后台管理', U('Index/login'));	//这个地方无法跳转到登陆页面，而是继续执行了_initialize中后面的方法，请问该如何处理？
		}
	}

**Comment by hugtale** [comment]
在构造函数中和在控制器方法中调用success或error有点区别的。在构造函数中调用success或error时（事实上还是需要交由Response::send()来输出结果，而直接return是做不到的），将返回值直接echo输出再exit就是了；而在控制器方法中success和error可以正常return，因为返回结果就是交由Response::send()输出的。

**Comment by pysjp** [comment]
明白了 感谢！
