### ISSUE TITLE
$this->error()后程序不结束

### ISSUE THREAD

**Issue by yondwell** [top-think/think#409]
$this->error()后程序不结束,在$this->error()后 die 不输出内容.

**Comment by yondwell** [comment]
需要用# ** \think\Response::isExit(true); 这个设置可否移到 config 里面呢?**

**Comment by hugtale** [comment]
@yondwell 
~~~
echo $this->error('xxx');
exit;
~~~

**Comment by XiaoXuanBing** [comment]
我都是 return $this->.....

**Comment by kinosang** [comment]
推荐使用 return
