### ISSUE TITLE
验证问题

### ISSUE THREAD

**Issue by px92000** [top-think/think#411]
<?php
namespace app\admin\validate;
use think\Validate;

class User extends Validate {

```
protected $rule = [
    'username'  =>  'require|unique:user',
];

protected $message = [
    'username.require'  =>  '用户名必须',
    'username.unique'  =>  '用户名已占用',
];
```

}

string '用户名必须,用户名已占用' (length=34)
我表单里没有提交任何值，这里内置的unique应该要做一个不为空的判断才行啊

**Comment by liu21st** [comment]
你的意思是 为空的时候 不检查第二个验证规则？

**Comment by px92000** [comment]
嗯咯
[ SQL ] SELECT * FROM `wx_user` WHERE `username` = '' LIMIT 1 [ RunTime:0.000447s ]
这里其实啥都没查到，但是错误信息还是输出了
顺便问一下验证规则如何设置有输入这个字段的时候做验证？

**Comment by liu21st** [comment]
最新版本改进了下 进行验证的条件
