### ISSUE TITLE
session配置问题

### ISSUE THREAD

**Issue by XiaoXuanBing** [top-think/think#412]
`
    'session'                => [
        // SESSION 前缀
        'prefix'         => 'by',
    ],`
项目配置里只写这些无法保存session
框架默认配置里自动开启是 true
难道设置了项目配置会整体覆盖`session`而不是覆盖`session=>prefix` ??

**Comment by momoca** [comment]
是的,项目config.php的条目,是会覆盖默认convention.php的中条目的.

**Comment by XiaoXuanBing** [comment]
@momoca 您理解错了，部分不应覆盖全部

**Comment by momoca** [comment]
@XiaoXuanBing 我没说全部呀.我是说config.php设置的会覆盖默认的.

**Comment by XiaoXuanBing** [comment]
@momoca 现在是部分会覆盖全部, 如题
