### ISSUE TITLE
验证问题2

### ISSUE THREAD

**Issue by px92000** [top-think/think#414]
// 如果不是require 有数据才会行验证
                    if (0 === strpos($info, 'require') || !empty($value)) {
                        // 验证类型
                        $callback = isset($this->type[$type]) ? $this->type[$type] : [$this, $type];
                        // 验证数据
                        $result = call_user_func_array($callback, [$value, $rule, &$data, $field]);
                    }

我验证规则设置不为require  $value为空的时候  $result 报未定义变量

**Comment by liu21st** [comment]
已经修正
