### ISSUE TITLE
添加的action_begin listener不执行

### ISSUE THREAD

**Issue by leunggamciu** [top-think/think#418]
目前系统只在App::module方法下监听action_begin，所以导致除了使用

> 方式1：路由到模块/控制器    '[模块/控制器/操作]?额外参数1=值1&额外参数2=值2...'

这种方式的路由以外，使用其他方式的路由方法都不会触发action_begin。比如使用

> 方式3：路由到控制器的方法  '@[模块/控制器/]操作'

这种方式。

**Comment by liu21st** [comment]
还有app_begin位置可以用的

**Comment by leunggamciu** [comment]
@liu21st 感谢回复，`app_begin`有点早，我需要拿到action的一些信息，起码要知道是哪个action。不知道你们后续有没有要添加的计划？
