### ISSUE TITLE
TP5无法初始化

### ISSUE THREAD

**Issue by joykuang** [top-think/think#429]
composer.json未定义autoload，故framework无法自加载

**Comment by kinosang** [comment]
framework 已经移动到 top-think/framework ，但是自动加载机制目前还在商讨过程当中，暂时还需要手动加载。

**Comment by hainuo** [comment]
@kinosang 还是建议对于入口文件只引入一个vendor/autoload.php文件的好，使用composer的载入方式

**Comment by liu21st** [comment]
@hainuo 现在有什么问题么？

**Comment by kinosang** [comment]
@hainuo 之前有这方面的尝试，因为对框架改动太多被回滚了。目前 TP 5.0 已经进入 RC 阶段，不适宜太大的变动。在 top-think/thinkng 仓库有更加激进的改动，如果感兴趣可以去看看。

**Comment by hainuo** [comment]
@kinosang   好的
