### ISSUE TITLE
当default module是index时除index controller可以访问外，其它controller无法访问

### ISSUE THREAD

**Issue by zhanghong** [top-think/think#437]
在index module里有一个user controller，当访问user controller里的index action时无论访问地址写成public/index/user/index.html或public/user/index.html都报错，错误如下：
`
Exception in App.php line 211
module [ user ] not exists
            // 模块初始化
            if (MODULE_NAME && !in_array(MODULE_NAME, $config['deny_module_list']) && is_dir(APP_PATH . MODULE_NAME)) {
                APP_HOOK && Hook::listen('app_begin');
                define('MODULE_PATH', APP_PATH . MODULE_NAME . DS);
                define('VIEW_PATH', MODULE_PATH . VIEW_LAYER . DS);
                // 初始化模块
                self::initModule(MODULE_NAME, $config);
            } else {
                throw new Exception('module [ ' . MODULE_NAME . ' ] not exists ', 10005);
            }
        } else {
            // 单一模块部署
            define('MODULE_NAME', '');
            define('MODULE_PATH', APP_PATH);
            define('VIEW_PATH', MODULE_PATH . VIEW_LAYER . DS);
        }

```
    // 获取控制器名
```

`

另外，在项目的config.php设置成default_module='home'，好像也不起作用，

**Comment by zhaomingliang** [comment]
controller 首字母大写，提示不存在 。
