### ISSUE TITLE
为什么不尝试做成composer项目包，通过autoload.php加载。

### ISSUE THREAD

**Issue by lubiao39699492** [top-think/think#44]
希望thinkphp能够有更多的改变，越来越好。

**Comment by liu21st** [comment]
大家一起贡献 才能有更好的发展 很多新东西 自身还有一个稳定的过程

**Comment by kideny** [comment]
一起加油！我最讨厌有些人整天喷，然后去舔歪果仁的臭脚。正儿八经，自己完善自己的系统，才是王道。

**Comment by lloydzhou** [comment]
composer的autoload加载，那么库文件都在vender目录下面，think自己的spl_autoload需要稍微做一点修改应该就好了
