### ISSUE TITLE
建议增加如下依赖

### ISSUE THREAD

**Issue by hainuo** [top-think/think#443]
https://github.com/vlucas/phpdotenv
在项目根目录下创建.env文件，将一些重要的信息比如 数据库用户名密码 地址   七牛等的key放在里面 
使用的时候通过getenv（`key`）来获取。这样比较好
可以防止重要信息的泄露，当然还要在.gitignore中过滤掉.env文件

**Comment by kinosang** [comment]
个人感觉 `config.php` 和 外围配置文件 也能达到同样的效果，你可以在git中忽略这些配置文件，如果需要留样板，可以保留一份空的 `config.simple.php` 文件在git里面

**Comment by liu21st** [comment]
现在已经支持 env文件配置了啊

**Comment by hainuo** [comment]
@kinosang   其实我是想类似这样做  
```
'hostname'    => $_ENV['host']?$_ENV['host']:'localhost',
    // 数据库名
    'database'    => $_ENV['database']?$_ENV['database']:'pp',
    // 数据库用户名
    'username'    => $_ENV['user']?$_ENV['user']:'root',
    // 数据库密码
    'password'    => $_ENV['password']?$_ENV['password']:'root',
```

这样之后 如果存在环境变量则直接读取环境变量 不存在就是默认的，环境变量设置一次后不用变动，而且配置文件，可以随时添加，有个更多地可能  

@liu21st  还真不知道 看来最近没怎么review源码  落后了
