### ISSUE TITLE
关于模板渲染 中is_file 文件名太长

### ISSUE THREAD

**Issue by ucc862** [top-think/think#444]
由于需要使用非文件的字符串进行渲染模板，TP是支持对内容进行渲染的。
但是当渲染的内容很长的时候，在这里使用is_file 会报 文件名太长的BUG。
望修复一下。
![image](https://cloud.githubusercontent.com/assets/4344635/14516834/9c8b0f28-0239-11e6-8398-4c470459c271.png)

**Comment by liu21st** [comment]
新版的改动已经区分成两个不同的方法了 所以is_file判断不需要了
