### ISSUE TITLE
M等函数不再支持了

### ISSUE THREAD

**Issue by maxlcoder** [top-think/think#448]
composer更新了一下 thinkphp5的框架源码，结果就不支持了M函数了 ，这是为什么呢？

**Comment by momoca** [comment]
改名了,你没看更新记录吗?

**Comment by momoca** [comment]
https://github.com/top-think/framework/commits/master

**Comment by maxlcoder** [comment]
@momoca    后面看到了

**Comment by bingzheyuan** [comment]
请问哪里能看下这个改名的原因么？单字母函数确实书写非常方便。

**Comment by momoca** [comment]
@bingzheyuan 可能是为了更好读吧.毕竟单字母可读性不强.

**Comment by bingzheyuan** [comment]
@momoca 这说不过去，M代替model，非常直观，而且字母函数很有$代替JQuery的舒适感

**Comment by liu21st** [comment]
@bingzheyuan  单字母函数是TP历史上争议较大的问题，应该说单字母函数的诞生是有历史原因的，但已经到了退出历史舞台的时候了，可能很多人习惯了单字母函数带来的便捷（虽然同时我们也饱受着某些学院用户的抱怨），基于几个原因：
（1）5.0 核心已经不依赖任何函数 只是对常用的操作封装提供了助手函数
（2）助手函数是可以完全自己定义和修改，并不影响其他的使用 
（3）现在的IDE提示和自动完成功能已经非常强大了，所以用不用助手函数 或者是否需要改成原来的单字母函数 全凭开发者个人意愿 

原因和用法都在这里了 http://www.kancloud.cn/manual/thinkphp5/144731

**Comment by bingzheyuan** [comment]
@liu21st 谢谢
