### ISSUE TITLE
改进的模板引擎，希望能采纳

### ISSUE THREAD

**Issue by oldrind** [top-think/think#45]
看了一下5.0版的模板引擎基本和3.2版的一样。我在3.2版的模板引擎基础上写了一个改进版，自己试用感觉还可以，如果可以的话希望5.0版能用上这个。
下面先只说一下对原引擎改进的一些功能：
1.标签的替换过程和原来有所不同。不再是递归式的把标签及中间的内容传值到方法里进行替换，而是用正则查找出标签后，由后到前（这样才不会影响前面的标签）替换模板中的标签，不管同类标签嵌套多少层，都是在一个循环中完成的，对替换的性能无影响。整体解析速度提升。
2. 兼容原来所有的标签功能和用法，已 对正则进行了优化，标签库和内置的普通标签可以使用一样的边界符，比如都用"{}"，只要不重名不会相互干扰，这样这些标签就可以和html标签区分开。
3.模板支持多级继承。
4.  include标签支持多层嵌套，可以传变量。如：
<include file="Public/nav" selected="{$id}" item="index" />
在Public/nav模板用[selected]得到的是[$id}被解析后的值，而在3.2版中这样的写法是不能正确得到{$id}的值的。
5.增强了.语法的应用范围
{$user.name.$group.name} 解析后是 <?php echo $user['name'].$group['name']; ?>
{:substr($varname.aa, $varname.bb)}  解析后是 <?php echo substr($varname['aa'], $varname['bb']); ?>
.语法在各个标签中都可以使用，$a.b.c这样的形式都能正确解析成$a['b']['c']
6.增加了一些新的语法
{$varname.aa ?? 'xxx'} 表示如果有设置$varname则输出$varname,否则输出'xxx'。 解析后的代码为： <?php echo isset($varname['aa']) ? $varname['aa'] : '默认值'; ?>
{$varname?='xxx'} 表示$varname为真时才输出xxx。 解析后的代码为： <?php if(!empty($name)) echo 'xxx'; ?>
{$varname ?: 'no'} 表示如果$varname为真则输出$varname，否则输出no。解析后的代码为： <?php echo $varname ? $varname : 'no'; ?>
 {$a==$b ? 'yes' : 'no'} 前面的表达式为真输出yes,否则输出no， 条件可以是==、===、!=、!==、>=、<= 
7. 对if标签及foreach也加了一些更简洁的用法

代码是在3.2版上写的，而5.0版结构有变动，我需要整理一下才能用到提交5.0版上来。

**Comment by dingyiming** [comment]
赞一下，好像TP在前端并没有打算做什么东西的样子，但前端肯定会在目录中，倒是要有个推荐目录结构就更好了

**Comment by liu21st** [comment]
TP V5是为API开发而设计 所以模板引擎这块的更新就不多 不过以后是可以更换的扩展的 前端目录结构方面也会给出建议的

**Comment by oldrind** [comment]
因改动的代码太多，我先提交3.2版的代码到thinkphp，官方试用一下看，如果这个改进有意义的话，我再整理成5.0版的。代码写得不好的地方也希望能给予指正。

**Comment by oldrind** [comment]
另外，5.0版是否会加入按路由规则来生成url的功能？正则路由可能无法反向解析，但静态路由和规则路由是可以反向解析出来的。我在3.2版上有重写了dispatcher类和route类，已能按静态路由和规则路由来生成地址。

**Comment by liu21st** [comment]
@oldrind 不错 加油~ 5.0版本引入了路由别名的概念 来快速的根据路由生成 URL，只是需要单独定义（但以后可以通过程序一次性生成）避免每次都要解析的开销
