### ISSUE TITLE
ajax请求问题

### ISSUE THREAD

**Issue by lscho** [top-think/think#461]
就是我从远程地址ajax读取一段div动态替换当前页面，但是这段div被转码了。如果设置'default_ajax_return'="html"可以解决，但是会出现新的问题，就是$this->success和$this->error方法也直接按照default_ajax_return设置的输出了

**Comment by momoca** [comment]
可以在输入前配置'default_ajax_return'="html"使用config

**Comment by eyblog** [comment]
目前我的解决方法是default_ajax_return设置为html，然后重写success和error；

看tp源代码似乎是
```php
$type = IS_AJAX ? Config::get('default_ajax_return') : Config::get('default_return_type');
```
ajax请求下直接读取配置按照'default_ajax_return设置的格式输出，并没有判断数据类型和是否是读取模版。能否在这里做一下判断，如果是return的是模版渲染的话就原样输出，如果return的是数据的话，就按照default_ajax_return格式输出？

**Comment by tryfinding** [comment]
用config 设置一下这个key

**Comment by XiaoXuanBing** [comment]
嘿嘿我也提过了, 套用模板本来就应该默认html, 
而且半年提了好几次的block嵌套block的问题一直没人改, 我都懒得提了
