### ISSUE TITLE
助手函数input获取session数据错误，未开启session_start

### ISSUE THREAD

**Issue by ZoaChou** [top-think/think#463]
代码示例：

    class A{
        public function index(){
            input('session.abc');
        }
    }

错误：
[8] ErrorException in Input.php line 135
Undefined variable: _SESSION

**Comment by ZoaChou** [comment]
关闭issue，改至framework下方便提交修改。

**Comment by momoca** [comment]
这个我之前提过.这不算错误,是session没有初始化所导致的.你可以使用session().或使用\think\Session::init();
