### ISSUE TITLE
根据PSR-2规范，不该 使用下划线作为前缀，来区分属性是 protected 或 private

### ISSUE THREAD

**Issue by jhasheng** [top-think/think#468]
我觉得作为一个资深的国产`PHP`框架，应该遵循`PSR`的大多数标准，除去需要强制遵守`MUST`的以外，类似`SHOULD`、`MAY`、`OPTIONAL`也应该遵守

[PSR-2 4.2. Properties](http://www.php-fig.org/psr/psr-2/)

> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

**Comment by liu21st** [comment]
新版框架已经遵循PSR-2规范，以及PSR-4自动加载规范，可以明确指出来 哪些文件还存在这样的问题 或许还有遗漏之处。

**Comment by jhasheng** [comment]
好吧，我还没有细看，但是你的README没有更新啊

**Comment by liu21st** [comment]
好像是 readme文件一直还是旧的 哈哈~

**Comment by kinosang** [comment]
CI 上面运行的测试，会首先通过 phpcs 检查PSR2标准

**Comment by jhasheng** [comment]
文档一定要同步更新啊，国内很多开源产品都做不到这一点，ThinkPHP 这一点一定要做好啊

**Comment by kinosang** [comment]
毕竟文档挪动到看云去了，结构大家都忘记README了

**Comment by liu21st** [comment]
readme文件已经修正

**Comment by momoca** [comment]
恩恩.我最近发现看云更新的很快.之前在git发现取消input类后,查资料去看云一看...input处竟然也更新了.
不错,真的很棒!!!
