### ISSUE TITLE
为什么控制器不支持驼峰呢？ 

### ISSUE THREAD

**Issue by youwen21** [top-think/think#474]
大写字母转成_小写 这种做法引起的问题 
1 控制使用时 要先去_转大写
2auth验证问题  添加菜单时加的驼峰菜单 ， 生成URL，控制器来回转  验证也得转 不麻烦么

使用驼峰有什么不妥当的地方吗？

**Comment by liu21st** [comment]
从来没有说 控制器不支持驼峰，建议仔细阅读手册URL访问相关章节

**Comment by youwen21** [comment]
恩 看到了  需要配置'url_convert'    =>  false,         我偏向喜欢大小写严格处理

**Comment by phpyii** [comment]
@liu21st @youwen21   驼峰的类名中中间的大写字母自动转换为下划线访问了，如果可以配置就好了，好多网址是：-
