### ISSUE TITLE
url大写写问题。

### ISSUE THREAD

**Issue by wangxing218** [top-think/think#478]
调用方法 url('UserLogin/rememberLoginAction');
得到结果 ： /home/user_login/rememberLoginAction.html；
控制器部可以转换为小写并有下划线，但操作方法并没有按这个规则转换啊！是不是可以改进，或者是我没有配置好参数？

**Comment by liu21st** [comment]
改进了下

**Comment by wangxing218** [comment]
非常 感谢 ，刚才更新了看了下，的确是修改了，但只是换成了小写，驼峰命名并没有像控制器名那样转换成下划线+小写。
如： url(‘UserLogin/rememberLoginAction’)
现版本得到的是：/index/user_login/rememberloginaction.html；
如果是这样的：/index/user_login/remember_login_action.html**；是不是更统一些呢？

**Comment by liu21st** [comment]
这样会导致 操作方法找不到的

**Comment by momoca** [comment]
我今天遇到此问题(url驼峰引起方法找不到).我看了loader源码.了解 @liu21st 的想法真的我同意你们在tp5中的设计!
我建议你 @wangxing218 也看看loader就知道了...
