### ISSUE TITLE
关于模板引用的变量的建议

### ISSUE THREAD

**Issue by dongnaebi** [top-think/think#479]
现在模板include引用文件传的变量只做替换，很不灵活，假如一些字段比如discription我不想每个页面都给传，而是在公共header模板里定义一个默认的，现在就只能通过截取字符串判断实现：
`{include file="public/static" title="标题" usejs="vue" /}`
`<?php if(substr('[description]',0,2)=='[d'): ?>默认的描述<?php else:?>[description]<?php endif;?>`
能否把引用变量当成真正的变量？

**Comment by momoca** [comment]
你直接在view里定义一个description模板或include都 是可以用的呀。当时只定义一次就行了。include 要是都 靠传入变量那不是很。。。
