### ISSUE TITLE
扩展配置文件在指定模块中不生效

### ISSUE THREAD

**Issue by laoha0201** [top-think/think#480]
例设置 'extra_config_list'      => ['database', 'route', 'validate','theme'],在模块admin下的theme.php配置文件未生效

**Comment by momoca** [comment]
是你理解错了，仔细看看手册 吧。模块下只识别指定名的配置文件。像你这theme.php应该放到配置目录（APP_CONFIG）下才会生效。

**Comment by laoha0201** [comment]
> 是你理解错了，仔细看看手册 吧。模块下只识别指定名的配置文件。像你这theme.php应该放到配置目录（APP_CONFIG）下才会生效。
这个有区别吗？系统本身只不过是默认配置目录CONF_PATH为APP_PATH，改一下CONF_PATH有什么用

**Comment by laoha0201** [comment]
原因自己找到了，是自己取值时搞错了，如theme.php文件中设置。须\think\Config::get('theme.变量名')取值，而不是直接\think\Config::get('变量名')取值
