### ISSUE TITLE
以后git更新了，用composer update就可以自动更新到最新版本嘛！

### ISSUE THREAD

**Issue by kideny** [top-think/think#485]
呵呵，我这个问题，是不是有点蠢。

**Comment by momoca** [comment]
当然.那还用问?

**Comment by kideny** [comment]
@momoca  那我修改过的文件呢，会被覆盖嘛？

**Comment by momoca** [comment]
你只要使用git更新你修改的会保留(合并).满不错的.
其实我是一直使用git更新的.使用composer update我想应该也是同理吧.
你自己测试一下.
