### ISSUE TITLE
控制器类后缀解析用问题

### ISSUE THREAD

**Issue by pihc** [top-think/think#486]
为了使控制器避免和model命名冲突，我开启了控制器累后缀解析的配置
`'use_controller_suffix'  => true,`
但是 think下App类 第317行代码
`$instance` = Loader::controller($controller, $config['url_controller_layer'], $config['controller_suffix'], `$config['empty_controller']);`
这里获取配置用问题，导致代码报错，前几天下载的代码，不知道有没有修复这个bug
新手 请多多指教

**Comment by liu21st** [comment]
配置参数都统一过了啊
