### ISSUE TITLE
如何实现58同城信息发布页的路由功能

### ISSUE THREAD

**Issue by shaohao2014** [top-think/think#488]
58同城信息发布页面的路由顺序如下：
1、选择大类页面：http://post.58.com/1 （“/”后面的1代表城市ID，这里代表“北京”）
2、选择小类页面：http://post.58.com/1/1/s2 （“1/”后面的“1”代表大类ID，这里代表“房屋信息”，后面的“s2”代表大类）
3、信息发布页面：http://post.58.com/1/8/s5 （“1/”后面的“8”代表小类ID，这里代表“租房”，后面的“s5”代表小类）
问题：
以上四个路由参数，用Route::domain()或者Route::rule()方法如何实现呢？

**Comment by shaohao2014** [comment]
基本解决了：
这样：\think\Route::rule(':id/:type','post/post/index');
但，
如果地址栏里有非法（或者说不想出现的字符，用户自己敲进去的字符串）字符串信息的话，会显示“该模块找不到” 的错误提示。不完美啊。

**Comment by liu21st** [comment]
你自己要给路由变量添加规则啊

**Comment by shaohao2014** [comment]
@liu21st 明白了！谢刘老板！

**Comment by shaohao2014** [comment]
@liu21st ，可能是我的问题描述的不清楚吧，也可能是58使用java写的，java服务器跑的是url注册，和php的路由有很大差异吧，总之还是个问题。

**Comment by momoca** [comment]
你的意思是语意化url吗?
如果是可以试试url_param_type参数.
http://www.kancloud.cn/manual/thinkphp5/118043

**Comment by shaohao2014** [comment]
@momoca 我们说的不是一回事。

**Comment by liu21st** [comment]
建议你仔细的阅读下 关于路由的部分

**Comment by momoca** [comment]
你要的不就是
http://post.58.com/area/1/id/8/class/s5
从一`key/value`变成
http://post.58.com/1/8/s5
`/value/value/...`这种吗?
```php
// URL参数方式改成顺序解析
'url_param_type'         => 1,
```
而想要解析为`http://domain.com/10/21/23`这种就是叫顺序解析呀.
我理解的不对吗?
@shaohao2014  还是你没有仔细看文档.

**Comment by shaohao2014** [comment]
@momoca 你把http://post.58.com/1/8/s5改为http://post.58.com/fdsjkfjk/1/8/s5，然后是什么结果？
当area=fdsjkfjk的时候，也就是参数超出你的路由范围的时候你想让页面指向哪里？同样，当id和class等于脏数据的时候怎么判断跳转页面？用闭包只能解决一个参数的问题，问题是这里有三个。

**Comment by shaohao2014** [comment]
@liu21st ，仔细看过。当多个参数需要解决值判断的时候，手册里没有提到相关的信息。闭包里的例子只有一个参数的判断。

**Comment by liu21st** [comment]
@shaohao2014 你只会死读书吧 路由只能定义一个参数还叫路由么

**Comment by shaohao2014** [comment]
我这样试了，出错。
\think\Route::get(':area/:id/:type',function($area, $id, $type){
    //数据库查询比对代码略
    if($row){
        return '成功';
    }else{
        return '错误参数值';
    }
});

**Comment by momoca** [comment]
@shaohao2014 我是真的开始明白为什么 @liu21st 让你看文档了.你真的应该好好看看.而且是从头看.
你现在是明显没明白什么是Route和它的作用.
如果tp5的说明看不明白,你再看看3.2.3的关于路由的说明和实例.虽然用法不一样,但是大体的含义你应该先明白和理解.

**Comment by shaohao2014** [comment]
@momoca 好的，我再看看，谢谢
