### ISSUE TITLE
tp5无法对某个模型单独定义表前缀

### ISSUE THREAD

**Issue by shiguangqi5559** [top-think/think#491]
在3.2版本之前的model有个属性protected $tablePrefix = 't_sys_';来个性化定义模型的表前缀。现在think5中如何实现改功能，助手函数model()也没有提供表前缀相关选项。

**Comment by he426100** [comment]
model有个$table可以定义表全名

**Comment by liu21st** [comment]
单独模型定义表前缀 这是个伪需求 模型只有对应数据表和数据库连接的概念 表前缀是数据库类库才有的概念，模型操作就不需要表前缀这个概念
