### ISSUE TITLE
db类insert无法过滤掉post数据中非数据库的字段

### ISSUE THREAD

**Issue by ww380459000** [top-think/think#493]
db类insert无法过滤掉post数据中非数据库的字段，能否加个过滤的方法呢？

**Comment by liu21st** [comment]
不需要 仔细看手册

**Comment by ww380459000** [comment]
看了的呢，提issue之前得看手册或者源码才问，Db::table('think_user')->field('title,email,content')->insert($data);比如有20个字段得把所有的都写到field的里，能否加个field(true)，直接过滤下呢？

**Comment by momoca** [comment]
@liu21st  说了让你看手册.
```php
// 排除id和name变量
Request::instance()->except('id,name');
```
你到手册里查查上面的是什么意思?

**Comment by ww380459000** [comment]
嗯，有么有办法直接过滤掉呢？有的不一定是request方式获取的数据

**Comment by liu21st** [comment]
@ww380459000  到现在还没搞明白呢 手册没去认真看么 快速入门常见问题也有

**Comment by liu21st** [comment]
我说了很清楚了 教程里面都有

**Comment by ww380459000** [comment]
好吧，设置了不严格检查strict，多么痛的领悟
