### ISSUE TITLE
insertAll插入数据异常的问题

### ISSUE THREAD

**Issue by lyongdee** [top-think/think#496]
Builder类的insertAll方法在添加多条数据的时候异常，看了下源码，在第616行的
if (!in_array($key, $fields, true)) {
.....

是不是应该改成
if (!array_key_exists($key, $fields)) {
.......

**Comment by liu21st** [comment]
报什么异常？

**Comment by lyongdee** [comment]
{
"code": 500,
"msg": "array_key_exists() expects exactly 2 parameters, 3 given",
"time": 1470479598
}

**Comment by lyongdee** [comment]
{
"code": 500,
"msg": "fields not exists:[firstname]",
"time": 1470480321
}

**Comment by liu21st** [comment]
你的数据有问题吧

**Comment by liu21st** [comment]
或者检查下字段缓存

**Comment by lyongdee** [comment]
好的，我再看一下。

**Comment by liu21st** [comment]
这个问题修正了下

**Comment by lyongdee** [comment]
好的，谢谢。
