### ISSUE TITLE
withField报错

### ISSUE THREAD

**Issue by jfy3d** [top-think/think#498]
User::field('id,name')->with(['profile'=>function($query){$query->withField('email,phone');}])

withField('email,phone')会被带到where 里？
8月6日版本

**Comment by jfy3d** [comment]
没人回应的，是确定的bug了呢，还是确定不是bug?

**Comment by liu21st** [comment]
其实可以在 定义关联的时候直接使用field指定

**Comment by jfy3d** [comment]
@liu21st   目前也是先这么绕过的，也试了其他几种绕过方案，但都还是有缺陷

withField('email,phone')  方法是最合适的，尤其实际开发对于字段较多附属表
