### ISSUE TITLE
跨库操作查看SQL记录的问题

### ISSUE THREAD

**Issue by lyongdee** [top-think/think#499]
涉及跨库的Model操作，使用 Db::connect('db_admin')......切库后，想输出SQL查看，但是这时候是没有SQL日志的，在跨库时有什么方法可以查看SQL吗？

**Comment by liu21st** [comment]
没有问题的，估计你的另外一个链接没有开启数据库的调试模式而已

**Comment by lyongdee** [comment]
OK了，分别开启不同数据库链接的debug。
