### ISSUE TITLE
在TP5里如何使用new PDO()?

### ISSUE THREAD

**Issue by shaohao2014** [top-think/think#501]
在TP5里如何使用new PDO()呢？出错啊

**Comment by kinosang** [comment]
TP5封装了数据库连接、查询等操作到 DB 类，你可以试试看。

参见手册 [数据库 - 基本使用](http://www.kancloud.cn/manual/thinkphp5/118060)

**Comment by shaohao2014** [comment]
@kinosang 我知道，用着很爽，但，我现在用了datatables前端控件，我必须使用控件提供的数据类

**Comment by kinosang** [comment]
能否贴出具体的报错信息？如果是在命名空间中，你需要使用 `new \PDO();` 来调用根命名空间的类

**Comment by shaohao2014** [comment]
刚试过，加个\就中了！哎
