### ISSUE TITLE
db类execute方法，使用名称参数绑定时，无法多次使用

### ISSUE THREAD

**Issue by ww380459000** [top-think/think#503]
<php>
$sql = 'INSERT INTO table(name,stime,fstime) VALUES (:name,:stime,:stime)';
db()->execute($sql,['name'=>"你好啊",'stime'=>time()]);
<php>
执行不了

**Comment by ww380459000** [comment]
@liu21st 这个问题最新版是否好了呢？

**Comment by liu21st** [comment]
你用了相同的参数绑定了吧

**Comment by ww380459000** [comment]
不能多次使用吗？参数绑定是可以的吧

**Comment by liu21st** [comment]
PDO不支持这种用法的参数绑定的
