### ISSUE TITLE
如何手动关闭一个数据库连接呢

### ISSUE THREAD

**Issue by shaohao2014** [top-think/think#509]
Db::connect([]);之后，怎么手动关闭连接呢？感觉性能不行啊，我在一个页面里用了
三次：
$rs1 = db('user')->select();
$rs2 = db('unit')->select();
$rs3 = db('order')->select();
之后，有时候页面明显刷新很慢。

**Comment by liu21st** [comment]
用Db类直接操作性能要高一些

**Comment by shaohao2014** [comment]
好
