### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by wmwgijol28** [top-think/think#512]
$file->move(ROOT_PATH . 'public' . DS . 'uploads');
Call to a member function move() on string

尝试过use think\File;
但__construct报错

**Comment by Qsnh** [comment]
你看返回的错误信息就知道了，你的$file不是对象而是string,怎么可能成功呢？你也不需要use think\File,直接使用Request $request, $request->file('file')->move()就行了，如果不是注入的话就勇request()->file()函数。
