### ISSUE TITLE
Db::field是不是弃用了？

### ISSUE THREAD

**Issue by shaohao2014** [top-think/think#513]
如题，我直接Db::field->table()->paginate();出错啊。
在Db类里也没有field方法

**Comment by momoca** [comment]
在query里,你用反了.或是使用闭包.

**Comment by shaohao2014** [comment]
我是看的官方例子：Db::field('user.name,role.title')
->table('think_user user,think_role role')
->limit(10)->select();

**Comment by shaohao2014** [comment]
我说的多表联合查询的时候的field问题

**Comment by momoca** [comment]
你是说Merge吗?
