### ISSUE TITLE
input function 获取中文URL参数BUG

### ISSUE THREAD

**Issue by yizenghui** [top-think/think#514]
支持英文

![image](https://cloud.githubusercontent.com/assets/9154198/17922162/35fe7ff8-6a10-11e6-8d52-7dc331ca6050.png)

不支持中文
![image](https://cloud.githubusercontent.com/assets/9154198/17922205/62019ad6-6a10-11e6-857b-893107216527.png)

> 在 laravel 中 `http://laravel.dev/广州` 可以获取 city=广州

**Comment by momoca** [comment]
这是你编码的问题.

**Comment by yizenghui** [comment]
@momoca  首先，很感谢你的回答，虽然并不能帮助我处理好这个问题。
我可以确定我并不会因为编码的原因导致这个错误
以下是我用到的代码片段

```php
# application/route.php
    '[api]'     => [
        'user/:search'   => ['Api/User/search', ['method' => 'get']],
    ],

#application/api/controller/User.php
    public function search(){
        dump(request()->get('search'));
        return 'user search name '.input('search');
    }
```

get `/api/user/搜索?search=易&a=1`
![image](https://cloud.githubusercontent.com/assets/9154198/18024248/12a25bea-6c38-11e6-983e-b91fe46e5b2a.png)

get `/api/user/search?search=易&a=1`
![image](https://cloud.githubusercontent.com/assets/9154198/18024255/26ffb9d4-6c38-11e6-9edf-01e768d5f9fa.png)

>这是你编码的问题.

我并不认可是这个原因导致的

**Comment by momoca** [comment]
```php
//url:http://domain.com/message-index.html?search=%E6%98%93
        echo url('Message/index@center', 'search=易');
        var_dump(input());
        var_dump(input('search'));
```
这个没有问题.
如果正常应该url中的中文应该是以上(%E6%98%93)哪样的.当你使用url函数生成连接时会自动进行转码.

**Comment by yizenghui** [comment]
我知晓像您这样的使用方式是没有问题的，而我出现的问题并非像您说的那样！
我无法通过自定义路由， 直接获取链接 `/user/:search`  上的中文参数而可以获取字符数字等
```
# tp5 route 中文参数例子
//路由中设置 
'user/:search'   => ['User/search', ['method' => 'get']],

get /user/易

// 期待结果
input('search') == '易'

```
我可在 laravel5.2 中实现该功能 而 tp5 不行

> 事实上在 ?s=易这种处理上并无问题

您可以测试一下，十分感谢！

**Comment by yizenghui** [comment]
对于 `/user/zh1` 这样的支持拓展到 `/user/易`
以便实现类似
`/s/搜索内容` 或者 `/t/标签` 这样的功能
@momoca

**Comment by momoca** [comment]
恩,找到问题了.这是我之前提过一个问题.https://github.com/top-think/framework/issues/267
```php
        \think\Route::domain('center', function () {
            \think\Route::get('user/:search', 'User/index');
        });
        echo url('User/index@center', 'search=易');
```
```
view-source:http://center.domain.com/user-%E6%98%93.html
//----
Array
(
    [search] => 易
)
app\center\controller\user::index
```

**Comment by yizenghui** [comment]
事实上 
`get http://tp5.com/user/%E6%98%93.html`
一直都可以获取到值，如您所示
```
Array
(
    [search] => 易
)
```
而其错误的是内容编码不对

我尝试更清楚的弄明白其原因
![image](https://cloud.githubusercontent.com/assets/9154198/18025757/f43dca4e-6c65-11e6-8d76-143922f22e95.png)

结果是惊人的
![image](https://cloud.githubusercontent.com/assets/9154198/18025760/20b04548-6c66-11e6-881d-1d134f971863.png)


> 我无法理解的结果，我必须指定浏览器为GBK编码才能正确的显示他

@momoca

**Comment by yizenghui** [comment]
这是我使用 laravel 获取的中文URL参数
![image](https://cloud.githubusercontent.com/assets/9154198/18025852/e458259a-6c68-11e6-8461-677324550a00.png)

```
# app/Http/routes.php
Route::get('{city?}', 'HomeController@index');

# app/Http/Controllers/HomeController.php
    public function index(Request $request){
        echo($request->city);
        die;
    }
```

**Comment by momoca** [comment]
你去补习一下基本的文件编码知识吧.这个不是tp5的问题.我也已经测试过了.框架本身没有问题.
1.保证您的框架代码是从git下载的.
2.加载的文件都是utf-8的.
3.实在不行就加header.
