### ISSUE TITLE
URL自动转换大小写bug

### ISSUE THREAD

**Issue by ghost** [top-think/think#517]
最新composer update
`'url_convert'=> true`
`request()->controller()`
首字母一直都为大写，`url_convert`不起任何作用

**Comment by liu21st** [comment]
controlller方法获取的控制器名称和控制器类名一致

**Comment by ww380459000** [comment]
url_convert不管设置true，还是false，对controller大小写都没用，对action有用，应该是个bug

**Comment by liu21st** [comment]
影响的只是URL获取 对controller名称的获取没有影响 action因为本身方法名不区分大小写

**Comment by ww380459000** [comment]
这个得说清楚啊，自从这次升级以后很容易晕
