### ISSUE TITLE
去掉insert()方法的replace参数

### ISSUE THREAD

**Issue by ww380459000** [top-think/think#520]
去掉insert()方法的replace参数，只有mysql有replace into，其他的数据库没得，请官方提供其他方法来代替，比如findOrNew？insertOrUpdate?

**Comment by liu21st** [comment]
不需要去掉 由不同的驱动自己实现就好了

**Comment by ww380459000** [comment]
嗯，看到了pgsql是有转化的，replace对于InnoDB自增的字段影响很大，官方能提供其他的方法吗？
