### ISSUE TITLE
tp5模型的静态方法update在使用where的前提下不更新update_time的问题

### ISSUE THREAD

**Issue by KuoKongQingYun** [top-think/think#521]
ArticleModel模型里开启了自动更新创建时间和更新时间。
我在表单里加入了隐藏的id项，所以input()返回的数组里直接有主键，然后使用
`ArticleModel::update(input());`
这个时候会正常更新update_time。
后来我把id从表单中移除，通过url参数来获取$id，为了防止跨用户修改文章，所以还额外加了一个条件。
于是有
`ArticleModel::where(['id'=>$id,'user_id'=>UID])->update(input());`
虽然会更新成功，而且数据也正常更新，但是这个时候update_time就不会自动更新了。
请问是什么原因呢？

**Comment by liu21st** [comment]
自动更新是模型的功能 数据库类没有这个功能 你调用的是数据库类的update方法，可以把条件写到 update方法里面
