### ISSUE TITLE
不支持按模块方式放模板文件吗

### ISSUE THREAD

**Issue by yanjunlin** [top-think/think#522]
配置view_path后自动到对应模块下解析模板文件，module/controller/action这种路径

**Comment by liu21st** [comment]
这个可以自定义当前模块的 模板根目录

**Comment by yanjunlin** [comment]
在模块中定义的话需要重新定义整个template数组吧，还是说可以单独定义模板目录？

**Comment by yanjunlin** [comment]
@liu21st 
还有设置了view_path之后，跨模块渲染模板还是会定位到moduel/view里边
`
// 获取视图根目录
        if (strpos($template, '@')) {
            // 跨模块调用
            list($module, $template) = explode('@', $template);
            $path                    = APP_PATH . $module . DS . 'view' . DS;
        } else {
            // 当前视图目录
            $path = $this->config['view_path'];
        }
`
框架写死的跨模块去模块下的view文件夹找模板文件

**Comment by liu21st** [comment]
最新版本 这个问题有修正的

**Comment by yanjunlin** [comment]
@liu21st 没有改啊git还是这样，跨模块调用的模板路径还是会定位到moduel/view
framework/library/think/view/driver/Think.php
```
// 获取视图根目录
        if (strpos($template, '@')) {
            // 跨模块调用
            list($module, $template) = explode('@', $template);
            $path                    = APP_PATH . $module . DS . 'view' . DS;
        } else {
            // 当前视图目录
            $path = $this->config['view_path'];
        }
```
