### ISSUE TITLE
跨模块调用model，模块配置无法加载

### ISSUE THREAD

**Issue by muunnw** [top-think/think#527]
A和B的表前缀不一样，各自有自己的database.php配置文件。
当A模块调用B模块的model，A模块由于没有加载B模块的配置文件，导致找不到表。

**Comment by liu21st** [comment]
你这种需求就必须使用接口来统一提供调用

**Comment by javiermu** [comment]
B模块就是统一对外提供接口，url请求从B模块来，调用没问题，但是内部的A模块也想调用B模块的这个接口就不可以，我这样算是统一接口吧？
