### ISSUE TITLE
input 助手函数无法获取值

### ISSUE THREAD

**Issue by yazohu** [top-think/think#529]
模板中用 url() 函数生成带参数的地址，比如 edit/id/5.html。input() 函数无法获取$_GET['id']

**Comment by liu21st** [comment]
这是基础问题了 谁告诉你URL里面的变量可以用$_GET获取的 仔细看手册吧还是

**Comment by yazohu** [comment]
@liu21st 你明白我的意思，手册里说可以通过 input('get.id'); 获取。可视我用这种方法是不可以的。只能通过 edit?id=5 才可以

**Comment by liu21st** [comment]
手册说可以通过 input('get.id'); 获取 那前提也是变量是$_GET变量才能获取啊  不要死脑筋

**Comment by yazohu** [comment]
@liu21st 于是所有的 带参数的链接，都得拼接，那要 url() 函数存在的意义是什么，生成伪静态地址，只好看？

**Comment by liu21st** [comment]
有现成的方法获取 你不用 input('id') 非要 input('get.id') 不是自找麻烦么 拜托你仔细看一遍手册再来提问可以么

**Comment by yazohu** [comment]
@liu21st 注：pathinfo地址参数不能通过get方法获取，查看“获取PARAM变量”。不好意思，我没注意到这个。我今天刚从r3 测试版升级上来，以前可以这么用，就没在意那句话。是我疏忽了

**Comment by yazohu** [comment]
@liu21st 谢谢

**Comment by yazohu** [comment]
@liu21st 借这个帖子顺便再问一个问题。用这种方法：
`$user           = new User;
$user->name     = 'thinkphp';
$user->email    = 'thinkphp@qq.com';
$user->save();`
这时的返回值是1，想要获取自增id ，还需要`echo $user->id;`。可是，在r3 测试话时，会直接返回自增id。这次升级，需要改的地方好多。只能这样每一处都改掉么

**Comment by liu21st** [comment]
参考 官方手册的 附录-》升级指导

**Comment by yazohu** [comment]
@liu21st 看到了。谢了
