### ISSUE TITLE
模块配置application/index/config.php中二级变量的问题

### ISSUE THREAD

**Issue by simphp** [top-think/think#531]
application/config.php
`'template'               => [
        // 模板引擎类型 支持 php think 支持扩展
        'type'         => 'Think',
        // 模板路径
        'view_path'    => '',
        // 模板后缀
        'view_suffix'  => 'html',
        // 模板文件名分隔符
        'view_depr'    => DS,
        // 模板引擎普通标签开始标记
        'tpl_begin'    => '{',
        // 模板引擎普通标签结束标记
        'tpl_end'      => '}',
        // 标签库标签开始标记
        'taglib_begin' => '{',
        // 标签库标签结束标记
        'taglib_end'   => '}',
    ],`

application/index/config.php
`'template' => [
        'layout_on' => true,
        'layout_name' => 'layout'
    ]`

config('template')
`array (size=2)
  'layout_on' => boolean true
  'layout_name' => string 'layout' (length=6)`

2016-09-26 从官网下载完整版

**Comment by liu21st** [comment]
不是独立的配置文件的话 都是直接覆盖的二级

**Comment by simphp** [comment]
OK，那还是直接在application/config.php中修改吧
