### ISSUE TITLE
TP5控制器return的问题

### ISSUE THREAD

**Issue by lyongdee** [top-think/think#533]
@liu21st 请教下，转移生产上的API程序从TP3到TP5。之前用TP3的API程序的控制器继承了基类，例Cart extends MobileMember，Cart在基类MobileMember的构造方法会判断用户状态，如果未登陆，MobileMember输出提示信息。现在tp5的控制器都是return数据交由Response输出的，这样的话我之前基类的输出就无效了，TP5有什么可以在基类return数据被Responser抓取输出吗？这样API会更简单。

**Comment by kinosang** [comment]
你是说在类初始化过程？ #395 曾经描述过这个问题

这种情况适合抛出异常，详见开发手册 错误和调试 - [抛出异常](http://www.kancloud.cn/manual/thinkphp5/165105)

**Comment by lyongdee** [comment]
多谢@kinosang。
