### ISSUE TITLE
控制器的构造函数或初始化方法中如何返回响应请求中断程序继续执行？

### ISSUE THREAD

**Issue by djjandyhl** [top-think/think#537]
在控制器的构造函数或者初始化方法中，如何使用Response类直接响应请求不再继续执行访问方法？而不是靠exit();

**Comment by liu21st** [comment]
可以使用 系统提供的abort助手函数 传入response对象实例即可

**Comment by djjandyhl** [comment]
希望官方在文档中对请求响应机制和response类做一些说明介绍，就像Request一样。
