### ISSUE TITLE
model 方法 $name 格式中含有 斜杠（/）会重新实例化模型类

### ISSUE THREAD

**Issue by metooweb** [top-think/think#538]
model 方法 $name 格式中含有 斜杠（/）会重新实例化模型类

**Comment by liu21st** [comment]
能具体一点么？

**Comment by metooweb** [comment]
比如 model('admin/user')  多次使用的话就实例化了多次Model类了

model('admin/user') 调用Model的时候就截取 后面的 usermodel 作为 键名 保存 Model，而判断是否已有该Model的时候 是用 admin/usermodel  作为键名 判断的

还有个不同 模块下的相同名称的 Model 使用 model函数调用会冲突

> public static function model($name = '', $layer = 'model', $appendSuffix = false, $common = 'common')
    {
        if (isset(self::$instance[$name . $layer])) {
            return self::$instance[$name . $layer];
        }
        if (strpos($name, '/')) {
            list($module, $name) = explode('/', $name, 2);
        } else {
            $module = Request::instance()->module();
        }
        $class = self::parseClass($module, $layer, $name, $appendSuffix);
        if (class_exists($class)) {
            $model = new $class();
        } else {
            $class = str_replace('\\' . $module . '\\', '\\' . $common . '\\', $class);
            if (class_exists($class)) {
                $model = new $class();
            } else {
                throw new ClassNotFoundException('class not exists:' . $class, $class);
            }
        }
        self::$instance[$name . $layer] = $model;
        return $model;
    }

**Comment by liu21st** [comment]
已经修正
