### ISSUE TITLE
如果post提交的是数组内容，使用$request->post('id')或报错误

### ISSUE THREAD

**Issue by Qsnh** [top-think/think#540]
表单：
`<input type="checkbox" value="1" name="ids[]"/><input type="checkbox" value="2" name="ids[]"/>`

提交之后，使用Request $request获取ids的值，$request->post('ids')会报错误。

**Comment by lilwil** [comment]
多看手册，/a 读取数组[http://www.kancloud.cn/manual/thinkphp5/118044](url)

**Comment by Qsnh** [comment]
这个怪我，没有仔细文档
