### ISSUE TITLE
whereor 参数为数组时候实现有误

### ISSUE THREAD

**Issue by ct12** [top-think/think#543]
Db::name('notice')
            ->where([
                'cid' =>1,
                'status' =>1
            ])
            ->whereor([
                'cid'=>0,
                'kid'=>1,
                'status'=>1
            ])

框架生成的 sql 语句是：
SELECT \* FROM `tb_notice` WHERE  `cid` = 1  AND `status` = 1 OR `cid` = 0  OR `kid` = 1  OR `status` = 1

按照手册描述，应该生成的是：
select \* from tb_notice where (cid=1 and status =1) or (cid=0 and kid=1 and status=1)

**Comment by liu21st** [comment]
复杂情况使用闭包吧
