### ISSUE TITLE
Query使用paginate分页优化建议

### ISSUE THREAD

**Issue by phpyii** [top-think/think#544]
生成如下sql  能否把统计总数的排序条件移除，这样是不是提高性能呢？  

[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `fc_collection_attention_records` WHERE  `user_id` = 3196  AND `quan_id` = 34  AND `action` = 2 ORDER BY is_top desc,time desc LIMIT 1      [ RunTime:0.001000s ]  

[ sql ] [ SQL ] SELECT `id`,`dynamic_id`,`type` FROM `fc_collection_attention_records` WHERE  `user_id` = 3196  AND `quan_id` = 34  AND `action` = 2 ORDER BY is_top desc,time desc LIMIT 0,15      [ RunTime:0.001000s ]

**Comment by liu21st** [comment]
已经改进了
