### ISSUE TITLE
静态文件无法访问

### ISSUE THREAD

**Issue by AspenLuoQiang** [top-think/think#545]
部署到linux的时候，css等静态文件无法加载！静态文件static目录被解析成一个控制器！导致静态文件404！如下图，望解决！
![_20161026002439](https://cloud.githubusercontent.com/assets/12598256/19694652/c8b5b82e-9b12-11e6-9078-01f702a6fcf6.png)

**Comment by xiasf** [comment]
你的这个静态文件没有找到吧，不然不会这样的，一般文件不存在才会重写到/inddex.php$上去，你检查下你伪静态的配置。

**Comment by AspenLuoQiang** [comment]
你好，这个文件是存在的，而且路径没有错误，为什么框架里面不能实现如果请求的是静态资源则不去实例化模板呢？

**Comment by xiasf** [comment]
这个跟框架没有关系，你检查下是主机url重写是不是不对，如果这样的话，那你现在public下的任何静态文件都访问不了，比如网站ico就看不到吧。

**Comment by AspenLuoQiang** [comment]
ico是有的，我按照手册隐藏了index.php，其他没有做操作，我的意思不是说跟框架有意思！我是想说，如果用户请求的是静态资源的话完全可以不去做类的实例化！

**Comment by xiasf** [comment]
就只有static下的静态文件访问不到，其它public下的ico等其它静态文件可以访问到是吗，这样就奇怪了。框架接受的只有pathinfo，所以框架是不会去判断静态文件是否存在的。估计就是你的nginx配置的问题。

**Comment by AspenLuoQiang** [comment]
嗯。可能我的配置有问题！但是我的建议希望考虑下，如果是请求的静态资源的话框架没必要去实例化一个类！

**Comment by xiasf** [comment]
**你的想法我想框架是不会考虑的，这不是框架应该做的事情。**

你参考下我的nginx环境配置：
- nginx.conf 部分
~~~
location ~ [^/]\.php(/|$) {
    #fastcgi_pass remote_php_ip:9000;
    fastcgi_pass unix:/dev/shm/php-cgi.sock;
    fastcgi_index index.php;
    include fastcgi.conf;
    }
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico|mp4)$ {
    expires 30d;
    access_log off;
    }
location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
    }
}

~~~
- URL重写（伪静态部分）
~~~
location / {
    if (!-e $request_filename) {
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
    }
}
~~~

如果你的问题最终解决了，别忘了来分享你的解决的方案，并关闭此issues。

**Comment by fengwuxin** [comment]
上面这个配置并不能解决问题。如果TP5对php conf 有特殊配置，最好跟大家普及一下哦，不然真的找不到原因。
![image](https://cloud.githubusercontent.com/assets/5679152/25881150/ed503b0a-356d-11e7-8fed-483e23d79f81.png)

**Comment by Osub** [comment]
http://wp.chenyuanzhao.com/wp/2016/10/06/nginx-thinkphp5-pathinfo/    参考这个看看，能不能解决，我也遇到类似的问题，好坑呀
