### ISSUE TITLE
软删除在连贯操作->where()->delete()下无效吗？

### ISSUE THREAD

**Issue by he426100** [top-think/think#548]
前端肯定要判断记录是否属于当前客户， 那就会在model里写这样的代码，->where(['id'=>$id, 'uid'=>session('uid')])，删除的话就顺手往后面加->delete()，测了几次， delete调用后是真删， 又去看了下model的delete方法和destroy方法， destroy是先查询，再用结果去delete， 一对比大概就明白了， 连贯操作的时候是$this->db()->where()->delete()了。 这样是有点费劲哈， 难道要在model里写$model = $this->get($where); $model->delete() ？

**Comment by liu21st** [comment]
当然有效

**Comment by he426100** [comment]
额， 才发现如果不用关联模型， 直接用db()获取列表的话那个软删除排除判定也无效了， 用关联模型也不能如我所愿只获取设定的字段， 加了withField也还是所有字段， 那这个软删除还真是麻烦大过实际意义， 还不如以前就用status来表示已删除呢

**Comment by liu21st** [comment]
请你仔细测试后再来反馈，可以么？

**Comment by he426100** [comment]
![3 mpjwrz jtf a54 5mw](https://cloud.githubusercontent.com/assets/9689137/19759317/0b156064-9c5f-11e6-877a-452a592c2efc.png)
![4mp n9oqs p 3bc tf 1](https://cloud.githubusercontent.com/assets/9689137/19759320/0c66c548-9c5f-11e6-962d-dc39c5bc52c4.png)

测试了啊， 连贯操作真的是直接删了。 关联模型字段那个是我搞错了，我删掉了

**Comment by he426100** [comment]
![3 mpjwrz jtf a54 5mw](https://cloud.githubusercontent.com/assets/9689137/19759317/0b156064-9c5f-11e6-877a-452a592c2efc.png)
![4mp n9oqs p 3bc tf 1](https://cloud.githubusercontent.com/assets/9689137/19759320/0c66c548-9c5f-11e6-962d-dc39c5bc52c4.png)

测试了啊， 连贯操作真的是直接删了。 关联模型字段那个是我搞错了，我删掉了

**Comment by liu21st** [comment]
软删除是模型的功能 不是数据库的功能 所以必须使用模型提供的删除方法（一样支持条件）
