### ISSUE TITLE
软删除无法使用链式调用

### ISSUE THREAD

**Issue by ksanyu** [top-think/think#549]
分成两条测试通过
$model->where('id', 1);
$model->delete();

链式调用无法实现
$model->where('id', 1)->delete();

where()返回的对象是Query, 而traits替换的是Model中的delete，所以链式调用会直接删掉数据，而不是软删除。希望官方能修复这个问题吧。

**Comment by liu21st** [comment]
软删除本来就是模型的功能 不是数据库的功能 所以务必使用模型提供的数据删除方法（一样可以支持条件）

**Comment by he426100** [comment]
还是你说的清楚， 楼上回答我没看懂，$model不就是模型吗？
