### ISSUE TITLE
泛解析域名规则没有0下标导致错误

### ISSUE THREAD

**Issue by ksanyu** [top-think/think#553]
![qq 20161108085938](https://cloud.githubusercontent.com/assets/20432069/20082557/b2b99de0-a591-11e6-8e6e-65c0fe2a86c4.png)

\think\Url.php 文件第227行应改为
$rule = is_array($rule) ? array_shift($rule) : $rule;

**Comment by liu21st** [comment]
你的域名规则是怎么定义的？

**Comment by ksanyu** [comment]
'*.app'				=>	'index?domain=*',
