### ISSUE TITLE
imagick无法显示

### ISSUE THREAD

**Issue by sixersun** [top-think/think#557]
imagick 生成图片乱码
demo
$image = new \Imagick();
$image->newImage(100, 100, new \ImagickPixel('red'));
$image->setImageFormat('png');
ob_clean();
header('Content-type: image/png');
echo $image;
然后乱码
同样环境下thinkphp3.2环境显示正常

**Comment by liu21st** [comment]
你这样 gd也会乱码 看看验证码扩展的写法
