### ISSUE TITLE
命令行执行控制台问题

### ISSUE THREAD

**Issue by phpyii** [top-think/think#558]
因为项目中配置了config_path 是 application/config   
command.php和所有配置文件都在pplication/config下   
 然后在think里也增加config_path的配置  
执行php  think  命令    找不到命令   
取消think中的config_path配置并把command.php放到默认的application下命令就可以执行了  但是这下又加载不了配置文件   把其他配置文件从pplication/config下移动到application下才可以

**Comment by liu21st** [comment]
只有CONF_PATH 常量 没有 config_path配置

**Comment by phpyii** [comment]
@liu21st  嗯是我用手机发的  所以没大写。 这个问题你们测过没？

**Comment by phpyii** [comment]
就是常量CONF_PATH

**Comment by liu21st** [comment]
没问题 你运行的是什么命令

**Comment by phpyii** [comment]
@liu21st  我是写的自定义控制台命令   在command.php里配置的  php think 自定义命令

**Comment by phpyii** [comment]
主要是我写的控制台命令里边要读配置  如果把默认配置文件修改个地方就不行了  执行php think list 都看不到我的自定义命令了

**Comment by phpyii** [comment]
我目前的解决方案是：application下放了 command.php config.php 和 database.php

**Comment by liu21st** [comment]
是你自己自定义命令有问题

**Comment by phpyii** [comment]
应该不是命令有问题  如果项目不修改默认的CONF_PATH  没有任何问题  
修改了后 我写的控制台就有问题了  执行 think 不能加载命令也不能加载配置文件

**Comment by liu21st** [comment]
那为什么内置指令没问题呢？自己好好想想

**Comment by phpyii** [comment]
@liu21st 默认的命令里   optimize:schema命令连接数据库也有问题 读不到数据库配置文件database.php

**Comment by liu21st** [comment]
你自己搞清楚了再来反馈吧~

**Comment by phpyii** [comment]
@liu21st  不好意思 是我弄错了 没有问题了
