### ISSUE TITLE
当我要验证的值是 exp 的时候，使用alpha，alphaDash等规则，永远都通不过

### ISSUE THREAD

**Issue by birdy0815** [top-think/think#561]
规则：'name|名称'  => 'require|alpha'
验证的值：exp
总是验证不过

alpha，alphaDash，alphaNum等规则都有类似问题

**Comment by liu21st** [comment]
测试未发现你说的问题啊

**Comment by birdy0815** [comment]
我又测试了一下，还是有这问题，不过原因应该不在于验证规则，还是在  request在接收数组参数的时候 /a 做强制转换的时候，会在 exp 值后面，增加一个空格.

我直接打印 $_POST 是没有空格，但是使用 input("post.para") 发现，值为exp的项，后面增加了一个空格

**Comment by birdy0815** [comment]
我又测试了一下，还是有这问题，不过原因应该不在于验证规则，还是在 request在接收数组参数的时候 /a 做强制转换的时候，会在 exp 值后面，增加一个空格.

我直接打印 $_POST 是没有空格，但是使用 input("post.para/a") 发现，值为exp的项，后面增加了一个空格

**Comment by birdy0815** [comment]
问题应该出现在 Request 1062行 filterExp　方式

public function filterExp(&$value)
{
        // 过滤查询特殊字符
        if (is_string($value) && preg_match('/^(EXP|NEQ|GT|EGT|LT|ELT|OR|XOR|LIKE|NOTLIKE|NOT BETWEEN|NOTBETWEEN|BETWEEN|NOTIN|NOT IN|IN)$/i', $value)) {
            $value .= ' ';
        }
        // TODO 其他安全过滤
}
