### ISSUE TITLE
使用model模型更新时,当遇到一样的字段时,会自动忽略与上一次相同的数据,而使用db则不会

### ISSUE THREAD

**Issue by qwertnv** [top-think/think#562]
`数据:`
array (
    0 => 
    array (
      'id' => '4',
      'name' => '管理员更新',
      'sort' => '1',
      'parent_id' => '0',
    ),
    1 => 
    array (
      'id' => '12',
      'name' => '大神',
      'sort' => '2',
      'parent_id' => '4',
    ),
    2 => 
    array (
      'id' => '13',
      'name' => '213',
      'sort' => '3',
      'parent_id' => '4',
    ),
    3 => 
    array (
      'id' => '2',
      'name' => '管理员管理',
      'sort' => '4',
      'parent_id' => '0',
    ),
    4 => 
    array (
      'id' => '11',
      'name' => '77',
      'sort' => '5',
      'parent_id' => '2',
    ),
    5 => 
    array (
      'id' => '14',
      'name' => '666',
      'sort' => '6',
      'parent_id' => '2',
    ),
    6 => 
    array (
      'id' => '1',
      'name' => '账号',
      'sort' => '7',
      'parent_id' => '2',
    ),
    7 => 
    array (
      'id' => '3',
      'name' => '管理员列表',
      'sort' => '8',
      'parent_id' => '0',
    ),
    8 => 
    array (
      'id' => '15',
      'name' => '444',
      'sort' => '9',
      'parent_id' => '3',
    ),
`db:`
 UPDATE `hd_admin_permission`  SET `id`=4,`sort`=1,`parent_id`=0  WHERE  `id` = 4
 UPDATE `hd_admin_permission`  SET `id`=12,`sort`=2,`parent_id`=4  WHERE  `id` = 12
 UPDATE `hd_admin_permission`  SET `id`=13,`sort`=3,`parent_id`=4  WHERE  `id` = 13
UPDATE `hd_admin_permission`  SET `id`=2,`sort`=4,`parent_id`=0  WHERE  `id` = 2
UPDATE `hd_admin_permission`  SET `id`=11,`sort`=5,`parent_id`=2  WHERE  `id` = 11
 UPDATE `hd_admin_permission`  SET `id`=1,`sort`=6,`parent_id`=2  WHERE  `id` = 1
 UPDATE `hd_admin_permission`  SET `id`=3,`sort`=7,`parent_id`=0  WHERE  `id` = 3
 UPDATE `hd_admin_permission`  SET `id`=14,`sort`=8,`parent_id`=3  WHERE  `id` = 14
UPDATE` `hd_admin_permission`  SET `id`=15,`sort`=9,`parent_id`=3  WHERE  `id` = 15

`model:`

![image](https://cloud.githubusercontent.com/assets/11536014/20385549/c890bb22-acf2-11e6-8dfe-80361593f72b.png)

**Comment by qwertnv** [comment]
在模型更新后 重置$this->data 后恢复正常,是否在model 模型更新后默认清空或添加参数控制较好?

**Comment by liu21st** [comment]
每次模型更新后 当前的data数据保存的就是更新后的数据 如果再次更新就会忽略相同内容的字段，所以比较正确的方式应该是先查询后更新或者使用update方法更新 而不要在当前实例里面多次更新
