### ISSUE TITLE
为什么得自己去加载composer呢，autoload.php在有的加载时会出问题吗

### ISSUE THREAD

**Issue by kebenxiaoming** [top-think/think#566]
// Composer自动加载支持
if (is_dir(VENDOR_PATH . 'composer')) {
         self::registerComposerLoader();
}
这是核心Loader.php中的内容

**Comment by liu21st** [comment]
你以为安装了composer就是自动加载了么？

**Comment by kebenxiaoming** [comment]
不是的，我是说直接autoload.php引入也能自动加载吧...
@liu21st

**Comment by kinosang** [comment]
事实上，这个问题曾经被讨论过。

一开始我是主张取消 ThinkPHP 自己的 Loader，完全交给 composer 的，后来我放弃了我的主张。

之后我发现 用 ionCube 或者 Zend Guard 加密源码之后 composer 的 Loader 不能正常工作……

**Comment by kebenxiaoming** [comment]
哦，果然是某些情况下可能出现问题，谢啦
 @kinosang
