### ISSUE TITLE
scope带额外参数bug

### ISSUE THREAD

**Issue by fromnow** [top-think/think#569]
scope带额外参数进行链式操作只有最后1个生效，后面再接where会有绑定参数错误？

**Comment by liu21st** [comment]
给出你的示例代码看看

**Comment by fromnow** [comment]
如果scope中有闭包，则存在这个问题
`protected function scopeCity($query, $cityId = '')
	{
	     $query->where('client_id', 'in', function ($query) use ($cityId) {
	                    $query->table('client')->where('city_id', $cityId)->field('client_id');
	             });	     
	}
	
	protected function scopeClientName($query, $clientName = '')
	{
	    $query->where('client_id', 'in', function ($query) use ($clientName) {
	                $query->table('client')->where('client_name', 'like', "%$clientName%")->field('client_id');
	            });
	}
	
	public function testScope($cityId, $clientName, $term) {
	    var_dump(Contract::scope('city', $cityId)->scope('clientName', $clientName)->buildsql());
	    var_dump(Contract::scope('clientName', $clientName)->scope('city', $cityId)->buildsql());
	    var_dump(Contract::scope('city', $cityId)->scope('clientName', $clientName)->where('term', $term)->buildsql());
	    Contract::scope('city', $cityId)->scope('clientName', $clientName)->where('term', $term)->select();
	}`

结果：
string '( SELECT * FROM `contract` WHERE  `client_id` IN ( SELECT `client_id` FROM `client` WHERE  `client_name` LIKE '%myName%' ) )' (length=124)
string '( SELECT * FROM `contract` WHERE  `client_id` IN ( SELECT `client_id` FROM `client` WHERE  `city_id` = 1 ) )' (length=108)
string '( SELECT * FROM `contract` WHERE  `client_id` IN ( SELECT `client_id` FROM `client` WHERE  `client_name` LIKE '%myName%' )  AND `term` = :where_term )' (length=150)

[10501] PDOException in Connection.php line 362
SQLSTATE[HY000]: General error: 2031
            // 参数绑定
            $this->bindValue($bind);
            // 执行查询
            $result = $this->PDOStatement->execute();
            // 调试结束
            $this->debug(false);
            $procedure = in_array(strtolower(substr(trim($sql), 0, 4)), ['call', 'exec']);
            return $this->getResult($class, $procedure);
        } catch (\PDOException $e) {
            throw new PDOException($e, $this->config, $this->queryStr);
        }

**Comment by fromnow** [comment]
如果scope中有闭包，则存在这个问题

`	

	protected function scopeCity($query, $cityId = '')
	{
	     $query->where('client_id', 'in', function ($query) use ($cityId) {
	                    $query->table('client')->where('city_id', $cityId)->field('client_id');
	             });	     
	}
	protected function scopeClientName($query, $clientName = '')
	{
	    $query->where('client_id', 'in', function ($query) use ($clientName) {
	                $query->table('client')->where('client_name', 'like', "%$clientName%")->field('client_id');
	            });
	}
	
	public function testScope($cityId, $clientName, $term) {
	    var_dump(Contract::scope('city', $cityId)->scope('clientName', $clientName)->buildsql());
	    var_dump(Contract::scope('clientName', $clientName)->scope('city', $cityId)->buildsql());
	    var_dump(Contract::scope('city', $cityId)->scope('clientName', $clientName)->where('term', $term)->buildsql());
	    Contract::scope('city', $cityId)->scope('clientName', $clientName)->where('term', $term)->select();
	}
`

结果：
string '( SELECT * FROM `contract` WHERE  `client_id` IN ( SELECT `client_id` FROM `client` WHERE  `client_name` LIKE '%myName%' ) )' (length=124)
string '( SELECT * FROM `contract` WHERE  `client_id` IN ( SELECT `client_id` FROM `client` WHERE  `city_id` = 1 ) )' (length=108)
string '( SELECT * FROM `contract` WHERE  `client_id` IN ( SELECT `client_id` FROM `client` WHERE  `client_name` LIKE '%myName%' )  AND `term` = :where_term )' (length=150)

[10501] PDOException in Connection.php line 362
SQLSTATE[HY000]: General error: 2031
            // 参数绑定
            $this->bindValue($bind);
            // 执行查询
            $result = $this->PDOStatement->execute();
            // 调试结束
            $this->debug(false);
            $procedure = in_array(strtolower(substr(trim($sql), 0, 4)), ['call', 'exec']);
            return $this->getResult($class, $procedure);
        } catch (\PDOException $e) {
            throw new PDOException($e, $this->config, $this->queryStr);
        }

**Comment by liu21st** [comment]
因为你的两个查询范围方法的字段是相同的啊 当然就会覆盖了

**Comment by fromnow** [comment]
那闭包带参数scope后面接where会有PDOException？

**Comment by fromnow** [comment]
而且字段相同也不需要覆盖吧（查询角度不同）

**Comment by fromnow** [comment]
where函数的处理太简单了。。

**Comment by fromnow** [comment]
where函数的处理太简单了。。
