### ISSUE TITLE
关于where函数中调用的parseWhereExp问题

### ISSUE THREAD

**Issue by fromnow** [top-think/think#570]
采用array_merge覆盖掉同一字段的查询条件似乎太过简单了，背离了链式操作的本意。
例如 where('id', '>', 1)->where('id', '<', 3) 中后一查询条件覆盖了前一条件。

**Comment by momoca** [comment]
写法不对.没有你这么写的.看看手册中的范围查询吧.

**Comment by fromnow** [comment]
只是举例说明这个问题， where('id', '>', 1)->where('id', '<', 3)当然可以合成一个条件，但这个链式操作个人认为在语义上没有什么问题，应该把所有链式所有where都进行解析，而用array_merge对相同字段条件进行覆盖不太恰当。
在#569中提到的scope中两个"in"查询实际上也是这个问题，把业务逻辑不同的两类查询写成scope，但由于字段相同而被覆盖了。

**Comment by momoca** [comment]
你还是没理解框架中的where.如果有多条件可以使用数组传入.
你在家里.你张老师在操场叫你一声,你李老师在教师叫你一声.你可能同时去东西两个地方吗?这时你只能响应一个位置. where('id', '>', 1)->where('id', '<', 3)这就是你的写法.因为都是id所以只能响应一个.
如果两个老师都在办公室同时叫你.你过去就可以了.
以上是正常的处理事情逻辑.
像你这种写法不是问题,写法也是支持的.但问题在于你用错了方式.
1.可以直接写条件id>0 or id<3
2.使用BETWEEN语法
你自己体会一下吧.

**Comment by fromnow** [comment]
接着讨论。你的比方不太恰当。我是课代表，张老师叫我把这次考试大于60分的卷子筛选出来，又接着又叫我把小于80分再筛选出来。那结果不是应该把60-80分的筛出来吗，难道选出0-80分的？
你也不能怪张老师为什么不一次交待清楚啊，有时候查询的业务逻辑是分条件，分模块的。

**Comment by momoca** [comment]
你说的非常好.叫你拿两次应该是两个select拉.
如果他说把大于60和小于80的拿过两.哪应该BETWEEN呀.

**Comment by liu21st** [comment]
如果你还是在纠结查询范围的问题 查询范围本来就是可以被覆盖的，如果不能被覆盖 事先定义查询范围还有啥意义，查询条件的规则就是相同字段的覆盖，按照你的说法 如果你用了 where('id',1)->where('id',2) 还指望框架帮你转成 where('id = 1 or id =2 ') ？

**Comment by momoca** [comment]
老大说的是.真的没必要搞的那么复杂.

**Comment by fromnow** [comment]
只是因为查询范围看到了parseWhereExp这里，所以讨论一下where的链式操作本身的含义。
就个人的看法where('id',1)->where('id',2) 应该转成 where id = 1 and id = 2 。用户怎么写条件，就怎么push，而不merge，这样是透明的。
当然，框架可以规定merge，纯粹讨论链式操作的意义，谢谢两位老大耐心探讨 ^_^

**Comment by liu21st** [comment]
这个地方 我做了一下改进 现在可以支持一个查询字段 多次调用查询条件了 （仅限于非等查询）

**Comment by fromnow** [comment]
赞，辛苦了！
