### ISSUE TITLE
使用 助手函数 model 方法 save($data, $where) 提示 => 缺少更新条件

### ISSUE THREAD

**Issue by a1141727** [top-think/think#573]
$result = $model->allowField(true)->save($data, ['id' => $id]);

使用 助手函数 model 提示 => 缺少更新条件
使用 $user = new User() 提示 => Call to undefined method app\admin\controller\User::allowField()

**Comment by momoca** [comment]
清看看手册.你使用的方法不对.
http://www.kancloud.cn/manual/thinkphp5/135189

**Comment by a1141727** [comment]
手册里的方法我都试验过了不好使！
