### ISSUE TITLE
助手函数 model  是调用的 model.php 模型的方法吧，为什么使用 save 方法会 调用query.php 这个类里的 Save 方法 

### ISSUE THREAD

**Issue by a1141727** [top-think/think#574]
助手函数 model  是调用的 model.php 模型的方法吧，为什么使用 save 方法会 调用query.php 这个类里的 Save 方法

**Comment by momoca** [comment]
使用$user->save.这个save就query.
使用$user::save.这个save是model.
我记得之前有过相关讨论.

**Comment by a1141727** [comment]
如果石勇$user::save()  那 怎么 做其他查询 如 isUpdate()  allowField()

**Comment by a1141727** [comment]
还有就是 model 里面的save  不是静态方法！
