### ISSUE TITLE
$user = new User; // save方法第二个参数为更新条件 $user->save([ 'name' => 'thinkphp', 'email' => 'thinkphp@qq.com' ],['id' => 1]);       直接报错 提示 缺少更新条件

### ISSUE THREAD

**Issue by a1141727** [top-think/think#575]
$user = new User; // save方法第二个参数为更新条件 $user->save([ 'name' => 'thinkphp', 'email' => 'thinkphp@qq.com' ],['id' => 1]);       直接报错 提示 缺少更新条件

**Comment by momoca** [comment]
建议改了$user=model('User');然后再$user->save($row,$map);
还有你要确认不是你的数据库的问题.

**Comment by a1141727** [comment]
$user=model('User');
$user->save($row,$map);              也报错！提示 缺少更新条件
