### ISSUE TITLE
cakephp3.0 yii2.0的发布都采用了composer 的自动加载和分包机制，奈何tp还是原地踏步

### ISSUE THREAD

**Issue by slince** [top-think/think#58]
本以为5.0是一大步；现在看来除了文件名和文件夹换了个写法还有别的改变吗；一个人的目光终究看不远，tp最好成立一个开源组织，由开发组的人负责开发维护，不该再放在liu21st的个人账号下。没有嘲讽的意思，在这样下去tp只能成为新人练手的工具

**Comment by liu21st** [comment]
欢迎加入我们的团队 一起参与维护 QQ群：221895784

**Comment by kinosang** [comment]
确实，在thinkphp目录下存放第三方库，不加载 composer 的 autoloader，都是比较不太舒服的地方。在3.2时代，我就曾对thinkphp的大量代码进行修正，就是为了适配 composer。
目前 thinkphp 5 的标准还没有冻结，希望可以尽快把项目迁移到 Org 账户，并且委派数名管理员，让大家共同参与进来。

**Comment by kinosang** [comment]
参考 #44

**Comment by yunwuxin** [comment]
@kinosang 兼容composer的autoloader已经写好了  今晚会提交

**Comment by kinosang** [comment]
@yunwuxin @liu21st 真心建议transfer项目到组织账户，显得专业。

**Comment by liu21st** [comment]
@kinosang 已经迁移到 thinkphpteam/thinkphp

**Comment by kinosang** [comment]
@liu21st 应该是Transfer，新建仓库没把issue、pr等信息带过去。
算了，作为一个外人我不多说了

**Comment by liu21st** [comment]
@kinosang 就看到有 import 方式 thinkphp5 才开始没多久 之前的东西不多

**Comment by liu21st** [comment]
@kinosang 邀请你加入吧~

**Comment by Lofanmi** [comment]
一起参与维护~~ QQ群：221895784

**Comment by kinosang** [comment]
@liu21st 在当前项目的 settings 页面，有 "Transfer ownership" 选项。个人认为早期的动态对于一个项目是十分必要的。尤其是issue、fork树。

**Comment by slince** [comment]
@liu21st  建议联系下https://github.com/thinkphp  说明下情况建议他转让下thinkphp这个token
