### ISSUE TITLE
session.auto_start 配置项的值为ON导致 session_start 无法启动

### ISSUE THREAD

**Issue by ksanyu** [top-think/think#581]
![image](https://cloud.githubusercontent.com/assets/20432069/20866391/97f61b1a-ba67-11e6-9d25-fc1b551f16f6.png)

**Comment by momoca** [comment]
```php
//例子不是写的很明白吗?明显是只支持true/false你非要写'ON'还要别人支持?

    // +----------------------------------------------------------------------
    // | 会话设置
    // +----------------------------------------------------------------------
    'session'                => [
        'id'             => '',
        // SESSION_ID的提交变量,解决flash上传跨域
        'var_session_id' => '',
        // SESSION 前缀
        'prefix'         => 'think',
        // 驱动方式 支持redis memcache memcached
        'type'           => '',
        // 是否自动开启 SESSION
        'auto_start'     => true,
    ],

```

**Comment by ksanyu** [comment]
可能我没有说明清楚原因，TP的配置项是默认的，没有改，这个问题是php.ini中的配置项导致的，服务器默认session是开启的
![image](https://cloud.githubusercontent.com/assets/20432069/20870836/9caf0150-bac9-11e6-96f1-0b3a6b1676dc.png)
![image](https://cloud.githubusercontent.com/assets/20432069/20870849/d19b46c6-bac9-11e6-9ceb-9dcdc1f0d18d.png)

**Comment by momoca** [comment]
你什么版本从github.更新一下试试吧.

**Comment by momoca** [comment]
@ksanyu 
我又测试了一下.没有问题.
1.php.ini中设置session.auto_start=1
2.配置文件中也设置了auto_start=>true
最新版本没有此问题.如果你更新后还有问题.请贴出代码.

**Comment by ksanyu** [comment]
重现的方法我测出来了，
1.自定义模板标签
![image](https://cloud.githubusercontent.com/assets/20432069/21013349/ac126506-bd94-11e6-8350-47f959ad5672.png)
2.配置项里加上这个模板，自动加载
'taglib_pre_load' => 'rbac',
3.删除runtime缓存文件，使模板标签生效
4.可以看到错误提示

导致错误的原因可能是Session这个类先执行了吧，具体代码还没看。

**Comment by ksanyu** [comment]
重现的方法我测出来了，
1.自定义模板标签
![image](https://cloud.githubusercontent.com/assets/20432069/21013349/ac126506-bd94-11e6-8350-47f959ad5672.png)
2.配置项里加上这个模板，自动加载
'taglib_pre_load' => 'rbac',
3.删除runtime缓存文件，使模板标签生效
4.可以看到错误提示

导致错误的原因可能是Session这个类先执行了吧，具体代码还没看。

**Comment by ksanyu** [comment]
建议官方在调用 session_start 时加个状态检测，防止跟服务器配置冲突，导致重复开启session
![image](https://cloud.githubusercontent.com/assets/20432069/21034899/4bd99e68-bdf6-11e6-979e-76331c0695b5.png)
