### ISSUE TITLE
请问TP5里面如何自定义common模块的路径呀！

### ISSUE THREAD

**Issue by xiaoxintiaoda** [top-think/think#582]
1.在tp3.2里面可以定义COMMON_PATH 来自定义common模块的路径，tp5好像没有这个宏

2.因为我的api和manager想共用一个tp5的框架和common模块，所以我的common不能放在application里面，所以我需要自定义common模块的路径

3.如果我不把common模块放在APP_PATH的目录，那么我的common里面class，在实例化的时候全都是Class 'app\common\xxx\xxx' not found.

请问有什么方法解决吗？

**Comment by kinosang** [comment]
可以考虑如下处理方式：

1. 仅设置一个application，将api, manager, common作为同一个application的模块；
2. 设定路由或域名路由

**Comment by xiaoxintiaoda** [comment]
好吧，也就是说tp5是不支持自定义common模块路径的，谢谢你的解答 >_<
