### ISSUE TITLE
tp5关于where条件查询

### ISSUE THREAD

**Issue by yangkaiqi21** [top-think/think#583]
处理where的and或者or逻辑时，有没有类似laravel里面addNestedWhereQuery的函数可以处理啊。以前3.2时候的处理方式是用$where['_logic'] = 'or'来处理，tp5里面可以怎么处理这个关系

**Comment by liu21st** [comment]
完全不需要啊 where和whereOr都支持闭包查询，你们再来调用查询

**Comment by yangkaiqi21** [comment]
我是需要把一些查询条件全部放在一个where里面，里面包含了or和and的关系都有。而不是使用where()->whereor()->。我想达到的目的是where($map)->select().。这个map里面就封装好where的and或者or的关系

**Comment by liu21st** [comment]
你说的map就是TP5一个闭包的概念
