### ISSUE TITLE
软删除的restore有问题

### ISSUE THREAD

**Issue by simphp** [top-think/think#585]
"UPDATE `cms_menu`  SET `delete_time`=NULL,`update_time`='2016-12-11 17:49:07'  WHERE  `cms_menu`.`delete_time` IS NULL  AND `id` = 1"
使用软删除的restore时，又自动加上了 delete_time IS NULL的条件，应该去掉。

**Comment by simphp** [comment]
软删除的destroy(id,true)也有问题
先查询 "SELECT * FROM `cms_menu` WHERE  `cms_menu`.`delete_time` IS NULL  AND `id` = 2"，
这个查询条件 delete_time IS NULL应该为IS NOT NULL

**Comment by liu21st** [comment]
你是最新的git版本么？

**Comment by simphp** [comment]
测试的时候是最新的 @liu21st

**Comment by simphp** [comment]
或许 destroy(id,true) 这个用法的理解本身就有问题。
第一种情况，如果是没有软删除的记录，直接destroy(id,true)是没问题的
第二种情况，既然有软删除，更合理的流程是先软删除，再对软删除的记录从数据库中删除，这样就有问题了。
请考虑是不是要加 delete_time IS NULL 或者 IS NOT NULL 的条件。 @liu21st

**Comment by liu21st** [comment]
软删除的问题已经修正
