### ISSUE TITLE
model怎么正确从配置文件中读取配置并生效？

### ISSUE THREAD

**Issue by TIGERB** [top-think/think#588]
我看了下think\model的代码，如果不设置需要自动写入时间戳为真，实例化的时候就会执行$this->db()建立一次连接（生成缓存）

```
  /**
     * 架构函数
     * @access public
     * @param array|object $data 数
     */
    public function __construct($data = [])
    {
      ...
        if (is_null($this->autoWriteTimestamp)) {
            // 自动写入时间戳
            $this->autoWriteTimestamp = $this->db()->getConfig('auto_timestamp');
        }
      ...
    }
```

当我复写了$connection配置，执行到$this->db()返回的还是上次缓存的连接, 并没有reset掉连接配置,下面的代码

```
/**
     * 获取当前模型的数据库查询对象
     * @access public
     * @param bool $baseQuery 是否调用全局查询范围
     * @return Query
     */
    public function db($baseQuery = true)
    {
        $model = $this->class;
        if (!isset(self::$links[$model])) {
            ...
        }
        // 返回当前模型的数据库查询对象
        return self::$links[$model];
    }
```
所以，现在我怎样才能让model使用从配置文件中读取的配置？

**Comment by liu21st** [comment]
你如果定义了connection属性的话 第一次调用db方法就是使用的connection设置连接数据库

**Comment by TIGERB** [comment]
如果没设置autoWriteTimestamp，model的构造函数已经第一次调用db方法了，我再设置connection就不管用了，因为返回的是缓存

**Comment by liu21st** [comment]
你说的是你动态设置connection属性么？这是什么需求

**Comment by TIGERB** [comment]
不知道tp5如何从配置文件或者env中读取数据库配置？

**Comment by TIGERB** [comment]
model的数据库配置从配置文件读取，而不是写死到model,蛋疼的业务中有时会跨库～

**Comment by liu21st** [comment]
跨库也是在模型的属性里面设置好啊 不存在动态设置的问题

**Comment by TIGERB** [comment]
直接定义connection只能写死啊（开发/生产环境没法搞啊），如果用initialize或者init复写connection就是现在的问题～

**Comment by liu21st** [comment]
你设置配置参数 统一更改配置文件啊 哪有你这样的做法的

**Comment by TIGERB** [comment]
model里定义配置只能写死，没发现怎么读配置的，THX~

**Comment by kinosang** [comment]
准备两份 database.php 配置，在开发环境和生产环境分开使用。

**Comment by liu21st** [comment]
connection属性设置为某个配置的名称即可 手册都有说明的

**Comment by liu21st** [comment]
生产环境的数据库配置可以读取环境变量
