### ISSUE TITLE
TP5 模板主题问题

### ISSUE THREAD

**Issue by github-gage** [top-think/think#59]
TP5 设置了主题模板，如果在Chrome 下清除浏览器数据后，模板主题的Cookie数据就不会再生成。重新访问也是没有模板主题数据。在Safari 下清除缓存倒不会出现该问题。【TP3.2无此情况】

**Comment by liu21st** [comment]
你怎么设置模板主题的？

**Comment by Gage-github** [comment]
写在配置文件里

**Comment by tryfinding** [comment]
应该没主题功能了，需要自己写代码扩展一下
