### ISSUE TITLE
5.0.4聚合模型save出错

### ISSUE THREAD

**Issue by simphp** [top-think/think#592]
主表写入成功，关联表失败
[10501] PDOException in Connection.php line 405
SQLSTATE[HY000]: General error: 2031

`<?php
namespace app\index\model;

use think\model\Merge;

class User extends Merge
{

    protected $relationModel = ['Profile'];

    protected $fk = 'user_id';

    protected $mapFields = [
        'id' => 'User.id',
        'profile_id' => 'Profile.id'
    ];

}`
`<?php
namespace app\index\controller;

use app\index\model\User;

class Index
{
    public function index()
    {
        $data = [
            'name' => 'zhangsan',
            'age' => 22
        ];

        $user = new User();
        $result = $user->save($data);
    }

}
`

**Comment by liu21st** [comment]
感谢反馈 已经修正

**Comment by simphp** [comment]
destroy 也出现同样的错误 @liu21st

**Comment by simphp** [comment]
`$data = [
            'name' => 'lisi',
            'age' => 22
        ];

        $user = new User();
        $result = $user->save($data, ['id' => 1]);`

提示
 `[8] ErrorException in Merge.php line 211
未定义数组索引: id`

**Comment by simphp** [comment]
@liu21st 能确认上面这个未定义数组索引的问题存在吗？
