### ISSUE TITLE
再报告几个聚合模型的问题，请确认

### ISSUE THREAD

**Issue by simphp** [top-think/think#593]
1. destroy(id,true) 时，只删除了主表，没有删除附表
2. destroy(id,true) 时，如果使用软删除，附带了`delete_time` IS NULL的条件，无法删除已经软删除的数据
3. save($data,['id'=>$id])时，提示 未定义数组索引: id
4. 先$model::get($id)，再save($data)时，没有更新update_time
5. withTrashed和onlyTrashed后只能用db\query查询，没法用聚合模型

**Comment by liu21st** [comment]
鉴于关联模型已经支持绑定关联属性到当前模型 将来聚合模型的重要性已经降低了 而且聚合模型还有一个问题就是 不能独立使用主表模型
