### ISSUE TITLE
建议增加session安全配置

### ISSUE THREAD

**Issue by zhuyuejianke** [top-think/think#599]
### config.php

```
'session' => [
    "httponly" => true,
    "secure" => true,
]

```
### \thinkphp\library\think\Session.php line:59

```
if (isset($config['secure'])) {
    ini_set('session.cookie_secure', $config['secure']);
}

if (isset($config['httponly'])) {
    ini_set('session.cookie_httponly', $config['httponly']);
}
```

### 说明
例如httponly设置项，phpsessionid还是能够被javascript读取的。
我看到在\thinkphp\library\think\Cookie.php里有设置这一项，但我在phpinfo()中看到的是，session.cookie_httponly 没有开启。

**Comment by liu21st** [comment]
感谢反馈 已经添加
