### ISSUE TITLE
url生成错误,目录后不应该加后缀

### ISSUE THREAD

**Issue by laoshancun** [top-think/think#602]
url('guideline/') 生成的url变成了guideline/.html

**Comment by momoca** [comment]
请看手册,http://www.kancloud.cn/manual/thinkphp5/118041
你写的方法错了.

**Comment by laoshancun** [comment]
有路由规则，应该可以生成的啊
` \think\Route::rule("guideline/" =>["content/index?model_id=1&name=guideline", ['domain' => 'www']])`

**Comment by momoca** [comment]
你还是理解的不对.你应该好好看看文档.
举个例子不知道恰当不恰当:有个小孩子他妈妈给他起名叫小明,你看到这小孩就知道他叫小明.而不是看到叫小明的都是这个小孩子.
这里的:
小孩子就是你的实际地址("content/index?model_id=1&name=guideline")
路由名称就是小明('guideline/').

不知道你能不能理解.多学习一下吧.

**Comment by laoshancun** [comment]
貌似明白了的样子，url要传完整路径是吧
