### ISSUE TITLE
运行单元测试，程序抛出Command "unit" is not defined.

### ISSUE THREAD

**Issue by littlerun** [top-think/think#605]
### 遇到的问题是什么？
1）在TP5.0当中，按照文档创建UnitTest；
2）创建后，运行php think unit，脚本提示：
[InvalidArgumentException]
  Command "unit" is not defined.

### 如何重现此问题?
1）进入thinkphp项目，例如~/test-tp5
2）执行：composer require topthink/think-testing
3）创建测试用例
4）执行 php think unit

### 期望结果是什么?
执行单元测试，并显示测试结果。

### 实际结果是什么?
程序抛出异常：
[InvalidArgumentException]
  Command "unit" is not defined.

### 其他信息

| Q | A |
| --- | --- |
| ThinkPHP 版本 | 5.0 |
| PHP 版本 | 5.6.27 |
| 操作系统 | CentOS release 6.2 |

参考文档：http://www.kancloud.cn/code7/tpunit/220875

**Comment by qfsz168** [comment]
遇到同样的问题。楼主解决了吗？

**Comment by qfsz168** [comment]
@littlerun 我把应用目录名改回“application”就好了。楼主试一下

**Comment by 21-rock** [comment]
think是在ThinkPHP目录下的一个PHP文件，当运行‘php think unit’这条命令的时候，实际上会执行think文件的。而如果更改了应用目录的名字的话（即不是默认的application时）,需要将think文件中的define('APP_PATH', __DIR__ . '/application/');改成define('APP_PATH', __DIR__ . '/你的应用目录名/');
