### ISSUE TITLE
JOIN的条件为什么没有支持USING选择

### ISSUE THREAD

**Issue by LinkedDestiny** [top-think/think#606]
使用JOIN方法的时候，如果condition想使用类似“left join table_b using(filed)”这样的语法，现在的Model是不支持的，能否提供一下为什么不支持的原因。
如果只是遗留了这个问题，请知会我，我会提交一个PR解决这个问题

**Comment by liu21st** [comment]
因为并不常用 所以没支持 你可以去提交PR的

**Comment by LinkedDestiny** [comment]
提交过了  但是没有过CI检测 ，然而我怎么也找不到哪里有问题……

2017-02-10 17:16 GMT+08:00 ThinkPHP <notifications@github.com>:
