### ISSUE TITLE
行为中redirect重转向没有用

### ISSUE THREAD

**Issue by captain-zhu** [top-think/think#607]
用了(new Redirect('url'))->send();和redirect('url')->send();都没有用.

**Comment by momoca** [comment]
也没你这种用法呀.
你还是先看看手册吧.http://www.kancloud.cn/manual/thinkphp5/118051

**Comment by captain-zhu** [comment]
@momoca 在行为手册里，流年在回复中自己说的这种用法。
http://www.kancloud.cn/manual/thinkphp5/118130
在9月18号，有一个兄弟说过redirect没有用的问题，流年说后面加send方法。那人说依旧没有用。然后流年就没有反应了。
如果要批量注册行为的话，可以使用：
文档中说
Hook::add('app_init',['app\\index\\behavior\\CheckAuth','app\\index\\behavior\\CheckLang','app\\admin\\behavior\\CronRun']);
当应用运行到app_init标签位的时候，就会依次调用app\index\behavior\CheckAuth、app\index\behavior\CheckLang和app\admin\behavior\CronRun行为。如果其中一个行为中有中止代码的话则后续不会执行，如果返回false则当前标签位的后续行为将不会执行，但应用将继续运行。
我和那个人的需求就是有终止代码时，重定向。
文档中说：
。在框架的执行流程中，例如路由检测是一个行为，静态缓存是一个行为，用户权限检测也是行为，大到业务逻辑，小到浏览器检测、多语言检测等等都可以当做是一个行为，甚至说你希望给你的网站用户的第一次访问弹出Hello，world！这些都可以看成是一种行为，行为的存在让你无需改动框架和应用，而在外围通过扩展或者配置来改变或者增加一些功能。
但是我实际测试过程中，感觉到不好实现文档中说明的功能。我业务逻辑判断用户没有权限，用行为怎么做？我返回false，应用依旧会继续进行。我想重定向到首页，做不到.
