### ISSUE TITLE
where 条件 _complex _logic 可不可以同时设置whereOr

### ISSUE THREAD

**Issue by lookwi** [top-think/think#610]
这种之类的，设置where条件 or 的方式，有解决方法吗？

**Comment by lookwi** [comment]
`$this->auth();
		if ($this->where['activity_start_date'] && $this->where['activity_end_date']) {
			$this->where['activity_start_date'] = [
				['GT', $this->where['activity_start_date']],
				['LT', $this->where['activity_end_date']],
			];
			unset($this->where['activity_end_date']);
		}
		$lists = $this->model->where($this->where)->whereOr($this->whereOr)->order('activity_id', 'desc')->paginate();
		$this->assign('lists', $lists);
		return view('lists');
`
现在的使用方式是这样的，我尝试 过将or条件放入到$this->where中，

在上一个版本3.2中，where是支持_logic 以及complex 进行设置条件；
请问在TP5中，我希望在Base控制器中管理所有条件并且统一设置在where中，如何解决这个问题

**Comment by lookwi** [comment]
应用场景1：
Base控制器：获取所有filter 筛选条件 转换为where 
在所有控制器中 扩展 Base控制器：
        拥有属性 $this->where
在Article::where($this->where)->select()的使用场景中
where 函数 无法通过数组的方式设置where
在Query 类中找到源码
public function where($field, $op = null, $condition = null)
    {
        $param = func_get_args();
        array_shift($param);
        $this->parseWhereExp('AND', $field, $op, $condition, $param);
        return $this;
    }
默认设置的为AND，也就是说，我数组中的条件必然会成为AND条件

**Comment by liu21st** [comment]
利用闭包解决之前版本的_complex查询
