### ISSUE TITLE
tp5文档中的“数据库”和“模型”的区别是什么？

### ISSUE THREAD

**Issue by xiaoxintiaoda** [top-think/think#613]
我在看tp5文档的时候，看到“数据库”和“模型”这两节，感觉实现的功能上是差不多的，而且感觉模型里面的用法也比较复杂，那么请问“数据库”和“模型”的适用场景是哪些呢，什么时候要用到模型呢？

**Comment by liu21st** [comment]
http://www.kancloud.cn/thinkphp/master-database-and-model  第五章有说明

**Comment by liu21st** [comment]
数据库是属于模型的底层 分工和职责不同的

**Comment by xiaoxintiaoda** [comment]
@liu21st 谢谢大神，回复真快 0_0
