### ISSUE TITLE
最新版的tp5在使用$this->display()方法与预期不符

### ISSUE THREAD

**Issue by praglody** [top-think/think#619]
这个方法不能输出页面,而是返回页面的地址, 现在只能使用return $this->fetch();输出页面

**Comment by liu21st** [comment]
给出实际代码吧

**Comment by OJesusO** [comment]
@praglody 建议可以看一下 think\Template，，对比一下两个方法，一个是渲染文件一个是渲染内容；而 控制器的输出全部采用 return 的方式

**Comment by praglody** [comment]
@OJesusO @liu21st 看了源码之后懂了,之前以为和tp3一样的功能。感谢回答！
