### ISSUE TITLE
我想问作者再用什么做测试

### ISSUE THREAD

**Issue by xiaohome** [top-think/think#62]
这个测试文件能不能对外公开！！！
我们看到的只有文件 ，看不到 测试过程
请公开 核心类库的测试！！！

**Comment by d1webtop** [comment]
测试分为单元测试和集成测试，单元测试使用phpunit，核心流程的测试正在编写中，集成测试采用travis-ci，现在已完成。

**Comment by xiaohome** [comment]
@d1webtop  你是开发者？ 能公开一下 travis-ci 吗

**Comment by kinosang** [comment]
@xiaohome 目前 [Travis-CI](https://travis-ci.org/top-think/think) 已经绑定到本项目。 CI 配置文件正在优化。CI图标尚未添加。

**Comment by d1webtop** [comment]
我是开发者，travis-ci 其实只需要一个travis.yml文件 已经有啦

**Comment by xiaohome** [comment]
![qq 20151216112907](https://cloud.githubusercontent.com/assets/15627505/11831298/3eaf696c-a3e8-11e5-889a-1f5825d14de8.png)

这个结果你们看了吗 ，还有phpunit 现在只是一个文件 还没有做！！！

**Comment by kinosang** [comment]
@xiaohome 参见 @d1webtop 的回复 “核心流程的测试正在编写中”

**Comment by liu21st** [comment]
@xiaohome 欢迎一起参与 TP5尚未正式发布 有大家参与才能更完善

**Comment by xiaohome** [comment]
@liu21st  这个  c m i d 这个这些函数能 写全名吗 例如 model input？

**Comment by xiaohome** [comment]
@liu21st  改善一下对function 的命名 谢谢！！！

**Comment by kinosang** [comment]
@xiaohome 单个字母的方法主要是为了兼容老版本习惯，目前TP5标准还未冻结，欢迎参与开发

**Comment by xiaohome** [comment]
那也可以改成别名 去调用呀 ，

**Comment by liu21st** [comment]
@xiaohome 这些规范之前还在讨论 TP5内部并没有调用这些函数~ 完全出于升级兼容和其它需要

**Comment by Lofanmi** [comment]
@xiaohome TP5的单字母函数已经从核心剥离出来了，具体的你可以阅读一下源代码。

**Comment by xiaohome** [comment]
从目前的版本来说 tp 确实进步很多！！！ 进步还是要值得肯定的！！ 继续努力吧！！

**Comment by Lofanmi** [comment]
@xiaohome 欢迎参与开发，提交PR

**Comment by liu21st** [comment]
@xiaohome 谢谢鼓励 每一次版本 我们都是用心在做的~ 这次更是会发挥团队的力量！
