### ISSUE TITLE
url生成 设置域名有bug

### ISSUE THREAD

**Issue by sanxiaozhizi** [top-think/think#621]
手册里面这个代码
`url('index/blog/read','id=5','shtml','blog.thinkphp.cn');`

在最新版本的ThinkPHP(5.0.6)的结果是

`http://blog.thinkphp.cn.test.com/blog/read/id/5.shtml`

**Comment by liu21st** [comment]
手册中的例子是有前提的 这个前提你的主域名是thinkphp.cn

**Comment by sanxiaozhizi** [comment]
@liu21st 难道不能自定义域名？一定要为目前访问的域名？

**Comment by liu21st** [comment]
我改进了下
