### ISSUE TITLE
在Model.php中新增加的formatDateTime方法使用中报错

### ISSUE THREAD

**Issue by qumao5736** [top-think/think#623]
第356行：$time = date($format, $time);
出错信息：A non well formed numeric value encountered

**Comment by liu21st** [comment]
一般是你的使用问题导致

**Comment by qumao5736** [comment]
没升级到5.0.7之前使用时正常的，我在数据库里有日期字段格式时datetime型的，那现在只能接收整型的时间格式吗？

**Comment by qumao5736** [comment]
可以了，加上类型转换：
protected $type = [
        'create_time'  =>  'datetime',
];

**Comment by liu21st** [comment]
早先版本的时间类型字段需要手动进行格式化输出 新版会自动格式化输出 主要是这个区别 如果之前手动做了格式化的话 取消即可 尤其是整型类型的日期
