### ISSUE TITLE
标签配置存在问题

### ISSUE THREAD

**Issue by postbird** [top-think/think#626]
两个个问题如下：

<s>1. 直接修改convention.php的开始和结束标签没有任何反应，只有修改app\config.php才有反应</s>

2. 对于 {{ }} 这样的标签貌似是无效的，不知道thinkphp是如何处理这样的标签配置的。

**Comment by 3212lin** [comment]
你直接修改convention.php 这个文件里的配置项的做法就是错误的
框架的东西不要随便动
