### ISSUE TITLE
请问 where 语句可以忽略执行么？

### ISSUE THREAD

**Issue by zs1973** [top-think/think#631]
$data=Db::table('ofu_needsinfo')
                        ->alias('n')
                        ->join('ofu_user u','u.user_id=n.user_id')
                        ->join('ofu_useravatar a','u.user_id=a.user_id ')
                        ->field('u.user_id,
                                u.school_name,
                                u.education,
                                u.certified,
                                n.info_id,
                                n.subject_name,
                                n.begin_time,
                                n.price_name,
                                n.workingcycle_name,
                                n.daytime_name,
                                n.city_name,
                                n.area_name,
                                n.address_detail,
                                n.remarks,
                                a.avatar_url')
//                        ->where('n.city_name','=',$city_name)
//                        ->where('u.education','in',$education)//学历
                        ->where('n.subject_name','in',$subjects)//科目
//                        ->where('n.price_name','in',$prices)//价格
                        ->paginate(2);
例如，where语法里面的第三个参数，怎么才能让数组里面元素的数量>0时才启用where条件，其他时候忽略这个where。

**Comment by momoca** [comment]
分开写如:
$data=Db::table('ofu_needsinfo');
$data->alias('n');
$data->where('xxx');
$data->paginate(2);
在合适的位置加上你的条件...

**Comment by liu21st** [comment]
5.1会支持条件忽略功能
