### ISSUE TITLE
一对一关联更新有没有自增的方法

### ISSUE THREAD

**Issue by mutoe** [top-think/think#639]
本来以为可以这样用 (click字段在 share_profile 表里面 已经添加了关联)
``` php
model('Share')->where('share_id', $id)->profile->setInc('click', 1, 60);
```
失败了 , 想自己去源码里面增加相应的方法..
终究没看懂 TAT
现在只能凑合用关联模型来自增了

请问下 官方支持这种自增的话工作量大吗? 有没有可能出这种方法?

**Comment by momoca** [comment]
不是没有,不是你哪么用的

**Comment by mutoe** [comment]
...不好意思让你见笑了 XD
