### ISSUE TITLE
[功能建议]模型的属性获取、修改器添加动态注册方法

### ISSUE THREAD

**Issue by hkuclion** [top-think/think#643]
现阶段只能通过在model里定义方法的方式来添加获取和修改器，这样不太利于提取公共的获取修改器（虽然可以通过Trait达到），更无法通过动态方式添加。
能否考虑像模型事件一样，在init方法里注册一个callable作为获取或者修改器

当然优先级的话，可以在实际方法之前之后，或者通过参数定义都可以

**Comment by liu21st** [comment]
动态注册 不如直接获取后修改 和 写入的时候处理了
