### ISSUE TITLE
资源路由中缺少对options请求的处理

### ISSUE THREAD

**Issue by simphp** [top-think/think#646]
5.0.7中
在API跨域请求时，会发送options请求，而资源路由中没有对这类请求的处理，导致PUT '/user/:id‘这样的请求失败。

**Comment by momoca** [comment]
这个和thinkphp并没有多大关系.在使用jsonp进行跨域访问时,js会先执行option请求,服务器回应该是否许可.如果允许再进行提交.
我建议直接在入口的文件中处理一下option.如果放到路由中我感觉会有些耗费资源.真的是会浪费很多服务器资源的.

**Comment by firemanhu** [comment]
使用路由规则，rule()，可以获取到请求。

**Comment by HOBERHUNTER** [comment]
兄弟，你这个问题解决了吗？怎么解决的，我也碰到了

**Comment by HOBERHUNTER** [comment]
解决了：http://blog.csdn.net/HobHunter/article/details/76290127
