### ISSUE TITLE
模板的URL引号问题，怎么处理呀？

### ISSUE THREAD

**Issue by bigzs** [top-think/think#647]
`<a href="{:url('index/content/', 'id=$submenuVo.id')}">
会解析成
<a href="<?php echo url('index/content/', 'id=$submenuVo['id']'); ?>">
引号会有问题。不想用php标签，想用url()`

**Comment by bigzs** [comment]
`<a href="{:url('index/content/', 'id=$submenuVo.id')}">
会解析成
<a href="<?php echo url('index/content/', 'id=$submenuVo['id']'); ?>">
引号会有问题。不想用php标签，想用url()`

**Comment by momoca** [comment]
你写错了,应该是
<a href="{:url('index/content/', 'id='.$submenuVo['id'])}"> 
或
<a href="{:url('index/content/', ['id'=>$submenuVo['id']])}">
