### ISSUE TITLE
静态资源会被作为路由解析？告诉模块不存在？

### ISSUE THREAD

**Issue by kunx-edu** [top-think/think#649]
为什么静态资源会被作为路由解析？告诉模块不存在？
在public下我建立了一个a.html也是提示模块不存在
换用5.0.4版本，没有问题。
**在thinkphp.cn下载核心板、完整版
通过GitHub下载zip包或者clone，没有问题**

我看了一下这类问题，早有人提问，但是从未有人得到有效解答，还是希望社区能够有些高手能够时常转一下~~~

我来粘贴一下我搜索到的此类问题：
http://www.thinkphp.cn/topic/38732.html 
http://www.thinkphp.cn/topic/41186.html 
http://www.thinkphp.cn/topic/42967.html 
http://www.thinkphp.cn/topic/41183.html

附nginx配置文件

    server {
        listen       80;
        server_name  tp5.kunx.org;
	index index.html index.php;
        root /Users/xukun/code/thinkphp5/public;
	autoindex on;
        location / {
	    if ( !-e $request_filename){
                rewrite ^/(.*) /index.php?s=$1 last;
		break;
            }
        }

        # redirect server error pages to the static page /50x.html
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

    }

**Comment by fengwuxin** [comment]
Up

**Comment by luoandy** [comment]
四哥

**Comment by vitasapple** [comment]
同求

**Comment by zcenet** [comment]
邮箱已收到，谢谢你的支持，祝你生活愉快~~=================================杨怀桂手机:13698971401

**Comment by Greatfar** [comment]
当你在nginx设置 `root /Users/xukun/code/thinkphp5/public` 时，
在public下新建一个 a.html 
此时，访问URL应该是 `http://xxxx.com/a.html` 而不是 `http://xxxx.com/public/a.html` 
当用了后者访问，当然出现public模块不存在了，
网络基础和nginx配置知识不过关，与thinkphp没什么关系。
