### ISSUE TITLE
非debug模式下系统记录错误没有记录文件及错误所在行

### ISSUE THREAD

**Issue by he426100** [top-think/think#651]
[ 2017-04-14T06:51:30+08:00 ] [ error ] [2]Illegal string offset 'status'
这样的错误日志根本没地方去查， 为了找到它， 我只能打开debug

**Comment by momoca** [comment]
database的设置里也有个debug吧.

**Comment by he426100** [comment]
@momoca 按你那样设是可以看到执行的每一条SQL语句， 并不是我需要的， 我需要的是在非debug模式下记录错误日志能定位到出错的文件和行
