### ISSUE TITLE
默认请求资源问题xml

### ISSUE THREAD

**Issue by seakk** [top-think/think#652]
配置文件里面是 
// 默认输出类型
    'default_return_type'    => 'html',

5.0.5 full版
使用 use think\Request;

方法中代码：
    $request = Request::instance();
        echo '资源类型：' . $request->type() . '<br/>'; 

会打印出xml， 不对吧。。。。应该是 html吧 ？

**Comment by momoca** [comment]
1,我在使用5.05时并没有您说的问题
2,我推荐你使用最新版本.
3,如果你想读取default_return_type的设置可以使用config函数.
