### ISSUE TITLE
路由bug？

### ISSUE THREAD

**Issue by hey-onlybaby** [top-think/think#653]
5.0.5 full版

路由规则：
    '[topic]' => [
        ':id' => ['h5/topic/detail', ['method' => 'get'], ['id' => '\d+']],
    ],
或者

// 注册路由到h5模块的topic控制器的detail方法
//Route::rule('topic/:id','h5/topic/detail');

生成url:  http://www.domain.com/topic/3

在方法内打印： 

print_r($_GET);
$request = Request::instance();
 print_r($request->get());

都是获取不到参数的 ，经我测试 在tp5中 需要加 ?id=23 这样才能获取到。

**Comment by momoca** [comment]
使用input函数获取.?xx=这当然要在get中了.其实5以后多了很多类型你可以参考一下文档.
如果想知道你的id在哪.他应该归属于route类型.
http://www.kancloud.cn/manual/thinkphp5/118044
好好看文档再来问问题.

**Comment by Ghost-Ge** [comment]
因为图快，粗略的看了文档，直接没有看到 $request->route() ，
thanks!

**Comment by momoca** [comment]
@Ghost-Ge 亲呀.我想说的是.重点在于使用input是自动识别的.
