### ISSUE TITLE
助手函数json 在构造方法中，无法正常使用

### ISSUE THREAD

**Issue by syxuwen** [top-think/think#654]
如下图，直接在构造方法中使用json函数return 
![image](https://cloud.githubusercontent.com/assets/13964970/25159382/fea0ddd4-24e1-11e7-8f68-5d12e075bff9.png)
居然直接到解析模版，请问遇到这种情况该如何处理?
![_20170419093435](https://cloud.githubusercontent.com/assets/13964970/25159677/09662c04-24e4-11e7-8174-3473f390bdab.png)

**Comment by syxuwen** [comment]
一个典型的场景是，在登录校验的时候，如果用户身份过期，请求是来自ajax ，那么返回json，否则直接跳转到登录页面

**Comment by chuanshuo-yongyuan** [comment]
我就像问问,你在构造函数里面,想返回给谁呢?
构造函数是一个没有返回值的特殊函数，所有即使加上return也没意义，他不会执行的。

**Comment by liu21st** [comment]
控制器有初始化方法 在初始化方法中进行处理

**Comment by syxuwen** [comment]
@chuanshuo-yongyuan 不是说非要返回给谁，比如我可以选择直接输出到页面
 @liu21st  指的 _initialize 方法吗？放在里面还是一样的，直接到模版解析

**Comment by liu21st** [comment]
好好看文档教程 说的很清楚了的 如何在初始化方法中跳转

**Comment by syxuwen** [comment]
error 方法自带 ，thank you!
