### ISSUE TITLE
[功能建议]分页toArray的时候增加总页数。

### ISSUE THREAD

**Issue by enryzol** [top-think/think#656]
\thinkphp\library\think\Paginator.php

326行
return [ 
		'total' => $total,
		'per_page' => $this->listRows (),
		'current_page' => $this->currentPage (),
		'last_page' => $this->lastPage(),   //增加一个总页数
		'data' => $this->items->toArray () 
];

165行
		if ($this->simple) {
			return ;
// 			throw new \DomainException ( 'not support last' );
		}

增加一个总页数，对前端会减少一些工作量。这样改怎么样？

**Comment by momoca** [comment]
原来也有吧.使用json返回数据就有total_count的内容呀.
