### ISSUE TITLE
框架lang加载在config之后则config中如果出错会报系统错误！

### ISSUE THREAD

**Issue by gmars** [top-think/think#658]
因为框架设计的加载顺序是：
E:\mrwei\thinkfive\application\config.php ( 8.55 KB )
E:\mrwei\thinkfive\application\database.php ( 1.87 KB )
E:\mrwei\thinkfive\thinkphp\library\think\Hook.php ( 4.63 KB )
E:\mrwei\thinkfive\application\tags.php ( 0.96 KB )
E:\mrwei\thinkfive\application\common.php ( 0.60 KB )
E:\mrwei\thinkfive\thinkphp\library\think\Env.php ( 1.05 KB )
E:\mrwei\thinkfive\thinkphp\helper.php ( 17.22 KB )
E:\mrwei\thinkfive\thinkphp\library\think\Lang.php ( 6.72 KB )
E:\mrwei\thinkfive\thinkphp\library\think\Log.php ( 5.51 KB )
E:\mrwei\thinkfive\thinkphp\lang\zh-cn.php ( 3.78 KB )
也就是application的config.php是在Lang.php之前载入的，如果config.php中有错误的话错误处理模板中的lang('xxx')函数会提示找不到lang()方法。
<b>Fatal error</b>:  Call to undefined function lang() in <b>E:\mrwei\thinkfive\thinkphp\tpl\think_exception.tpl</b> on line <b>82</b><br />
所以，我觉得对于加载入lang之前的错误处理应该使用其他错误处理机制或者替换lang()函数。

**Comment by Antisunny** [comment]
Uncaught Error: Call to undefined function lang() in framework/tpl/think_exception.tpl:82

**Comment by liu21st** [comment]
这个问题最新版本修正了下
