### ISSUE TITLE
命令行模式下自动时间戳错误

### ISSUE THREAD

**Issue by he426100** [top-think/think#663]
它的值是开始运行的时间， 我用了think-queue， 然后发现相关的记录update_time全都是队列开始的时间

**Comment by he426100** [comment]
我使用了supervisor

**Comment by liu21st** [comment]
这个问题最新版本已经修正过的应该

**Comment by he426100** [comment]
的确已修正， 项目在正式运营了， 为了保证稳定我就没更新框架， 刚在本地测了， 的确更正了
