### ISSUE TITLE
我想改response的content-type怎么改不了

### ISSUE THREAD

**Issue by birdshark** [top-think/think#666]
我在action里面这样写
`return response($data,200,['Content-Type'=>$filetype,'Accept-Ranges'=>'bytes','Accept-Length'=>filesize($path),'Content-Disposition'=>"attachment; filename={$filename}"],"");`
但是不管$filetype是啥 最终总是text/html
然后我检查了代码
发现class Response的构造是不是应该这样写
       ```
$this->data($data);
        $this->code   = $code;
        if (!empty($options)) {
            $this->options = array_merge($this->options, $options);
        }
        $this->contentType($this->contentType, $this->charset);
        $this->header = $header;
```

**Comment by liu21st** [comment]
已经修正
