### ISSUE TITLE
NOTIC: [8] Undefined index: HTTP_ACCEPT /thinkphp/library/think/controller/rest.php 第 125 行.

### ISSUE THREAD

**Issue by liuzhaowei55** [top-think/think#67]
重复输出到日志,是不是检测不到我的这个header?

**Comment by Lofanmi** [comment]
那一行代码是对这个超全局变量$_SERVER的HTTP_ACCEPT做了一次读取，是不是unset了？

**Comment by liuzhaowei55** [comment]
@Lofanmi 我用postman和Paw测试api的时候会有输出,用浏览器的时候没有输出,应该是在用测试工具测试的时候没有这些header属性.这个地方是不是应该先判断一下,然后再处理.

**Comment by liuzhaowei55** [comment]
@Lofanmi 看到了，感谢
