### ISSUE TITLE
Hook不支持阻断拦截吧?

### ISSUE THREAD

**Issue by fengxiaochuang** [top-think/think#674]
比如我现在非常想把模块不存在的异常给捕获掉,现在只能从app_begin这个标签入手进行捕获,但是return是不生效的,现在采用的官方不推荐的exit退出的.

官方可能推荐使用$beforeActionList这个去扩展切面拦截,但是对于在module的异常,就不能有效捕获了.

**Comment by liu21st** [comment]
你可以抛出HttpResponseException异常会自动捕获处理的
