### ISSUE TITLE
请作者修正加载验证器异常类BUG

### ISSUE THREAD

**Issue by JunJun-Love-Amber** [top-think/think#677]
Class 'think\Exception\ValidateException' not found
ErrorException in Model.php line 1356

看了think\Model.php 的自动加载，发现

use think\Exception\ValidateException;

Exception 居然是大写！！！！
求修正！！！！！

**Comment by CmderQ** [comment]
这个没错啊！楼主你看看源代码就知道啊！在think目录下，异常类文件夹为exception，其下面有ValidateException.php方法！

**Comment by liu21st** [comment]
已经修正
