### ISSUE TITLE
关于public目录，其实是一个降低安全性的败笔

### ISSUE THREAD

**Issue by gy9** [top-think/think#679]
public目录的使用确实增加了模块化，让thinkphp更新起来简单了很多，但在安全上是缺乏考虑的。
官方给出的使用方法是讲vhost定义在public目录下，访问application目录需要采用../的方式来访问。这就导致了访问application目录是需要授权访问上级目录的权限。以前我的服务器也是这样的，其中一个子站中了webshell后整个服务器上的站点就都在黑客控制下了。
现在为了增加安全性，我限制子站只能访问自己子目录下的文件，禁止访问上级目录。然后虚拟主机无权访问上级目录，这是很正常的权限设置。而要使用thinkphp这种public目录有权访问上级目录这种设定下，就要让门户大开，让整个服务器都在子站的控制下，这显然是很不合理的。
使用public这个设定就要赋予其访问上级目录的权限，这样并不安全；
而如果需要用户手动讲public目录移动到根目录并修改入口文件，这很不友好画蛇添足；
保持现状，用户vhost目录设置在网站根目录那访问网站就需要以hostname/public的地址访问了，也不合理；
所以还是改回来吧

**Comment by kinosang** [comment]
请使用 chroot 或类似技术。

直接暴露业务源码的做法比仅暴露公开资源的方式危险性大得多。

**Comment by lobtao** [comment]
这位兄弟，应该是新手。
www.a.com
       application
        public
www.b.com
        application
        public
这样子，不是每个网站都控制域名文件夹下吗。

**Comment by tekintian** [comment]
纯新手，而且还搞不清楚权限设置问题
