### ISSUE TITLE
[TP5.0.10]验证器静态调用方法能否增加对多个验证规则合并验证的支持

### ISSUE THREAD

**Issue by sochishun** [top-think/think#687]
验证器能否增加支持单个验证的方法，比如：if(!Validate::validate($id,'number|gt:0')){$id=1}，这在以默认值替换非法参数值的时候很有用。现在验证器中有提供单个静态调用的方法，是能简化一些判断的代码逻辑，但是不支持多个验证规则合并验证，自己多敲代码是没关系，不过建议TP的验证器增加支持多个验证规则合并验证的静态调用方法，感谢。

**Comment by liu21st** [comment]
这个需求可以直接调用check方法完成验证

**Comment by liu21st** [comment]
我刚增加了一个checkRule方法可以满足你的要求
