### ISSUE TITLE
[TP5.0.10]验证码使用背景图，提示路径出错

### ISSUE THREAD

**Issue by sochishun** [top-think/think#688]
版本:TP5.0.10, 文件：\vendor\topthink\think-captcha\src\Captcha.php, 代码239行, 
private function _background()

{
    $path = dirname(__FILE__) . '/verify/bgs/'; // 这个路径是错的，下面的路径才是对的！望修正。
    $path = dirname(__FILE__) . '/../assets/bgs/';

**Comment by CmderQ** [comment]
按照你说的，应该在文件：\vendor\topthink\think-captcha\src\Captcha.php中的293行

**Comment by CmderQ** [comment]
Thinkphp5.0之后，library下没有Verify这个方法了
