### ISSUE TITLE
关于URL上带参数s时报无法加载模块:**的问题

### ISSUE THREAD

**Issue by 156640677** [top-think/think#693]
我在地址栏中输入
http://localhost/project/Teaching/Admin/getUser?u=1&dd=3
可以正常返回结果，改为
http://localhost/project/Teaching/Admin/getUser?u=1&dd=3&s=e后，报：无法加载模块:E
输入
http://localhost/project/Teaching/Admin/getUser?u=1&dd=3&s=f，报：无法加载模块:F

用的ThinkPHP 3.2.3

**Comment by liu21st** [comment]
仔细看手册
