### ISSUE TITLE
app_debug为false时，日志写入报错，导致服务器500错误。

### ISSUE THREAD

**Issue by aiyolk** [top-think/think#695]
app_debug为false时，日志写入报错，导致服务器500错误，
apache日志查到是thinkphp/library/think/log/driver/File.php 中 92行$info未定义。

**Comment by liu21st** [comment]
你是什么版本的啊

**Comment by aiyolk** [comment]
V5.0.10

**Comment by liu21st** [comment]
5.0.10版本File文件92行没有你说的代码啊
