### ISSUE TITLE
mongodb 驱动 模型使用order无效

### ISSUE THREAD

**Issue by FengData** [top-think/think#699]
$brandList=$brandModel->field('xx')->where($whereAnds)->order('create_time desc')->paginate(20,true,['page'=>$page]);

**Comment by FengData** [comment]
查了下源码 只支持指定排序 希望可以改进

    /**
     * 设置sort
     * @access public
     * @param array|string|object   $field
     * @param string                $order
     * @return $this
     */
    public function order($field, $order = '')
    {
        if (is_array($field)) {
            $this->options['sort'] = $field;
        } else {
            $this->options['sort'][$field] = 'asc' == strtolower($order) ? 1 : -1;
        }
        return $this;
    }

**Comment by FengData** [comment]
又试了一下  可以使用数组方式 1 和 -1 形式 ：
order(['is_top'=>-1,'is_recommend'=>1])

**Comment by liu21st** [comment]
order方法的排序需要第二个参数
