### ISSUE TITLE
查询构造器使用时间查询数据不对

### ISSUE THREAD

**Issue by webzhoqij** [top-think/think#700]
think_data表
id    name        create_time
1    onethink    2017-06-20 14:41:22
2    topthink    2017-08-01 14:41:22
3    kancloud    2017-07-31 00:00:05
代码：
// 查询本周添加的数据
        $result = Db::name('data')
            ->whereTime('create_time', '>', 'this week')
            ->select();
        dump($result);
只打印出
  0 => 
    array (size=4)
      'id' => int 3
      'name' => string 'topthink' (length=8)
      'status' => int 1
      'create_time' => string '2017-08-01 14:41:22' (length=19)
但是7月31号是星期一，数据并没有出现

// 查询本周添加的数据
        $result = Db::name('data')
            ->whereTime('create_time','week')
            ->select();
        dump($result);
  0 => 
    array (size=4)
      'id' => int 3
      'name' => string 'topthink' (length=8)
      'status' => int 1
      'create_time' => string '2017-08-01 14:41:22' (length=19)
  1 => 
    array (size=4)
      'id' => int 4
      'name' => string 'kancloud' (length=8)
      'status' => int 1
      'create_time' => string '2017-07-31 00:00:05' (length=19)
这样是有7月3日的数据的

**Comment by liu21st** [comment]
使用 this week 00:00:00 就可以了
