### ISSUE TITLE
开启事务时，多次调用save更新不同行，最后不执行且不报错

### ISSUE THREAD

**Issue by cnsunshine** [top-think/think#702]
![image](https://user-images.githubusercontent.com/15982803/28973541-1cd4a29e-7966-11e7-87d1-473120821e94.png)
![image](https://user-images.githubusercontent.com/15982803/28973556-261e7fdc-7966-11e7-9797-fb8b14a2c447.png)
![image](https://user-images.githubusercontent.com/15982803/28973568-2ee89616-7966-11e7-9c73-a86c8cd2f2df.png)

**Comment by yangweijie** [comment]
我5.0.10 好像也遇到了   在配xdebug 调试

**Comment by cnsunshine** [comment]
@yangweijie 看了save源码里面有个getChangedData，更新的数据相同的话，第二次不做更新，我已经改为$Model->where()->update()
