### ISSUE TITLE
数据库中datetime类型的字段读取精度不足

### ISSUE THREAD

**Issue by cnsunshine** [top-think/think#703]
数据库中datetime类型的字段读取精度不足，如datetime(6)类型，会自动精确到 时：分：秒，秒后精度丢失

**Comment by cnsunshine** [comment]
临时的解决方案，在读取相应字段时，进行字符串转换。date_format(datetime, '%Y-%m-%d %H:%i:%s.%f')

**Comment by liu21st** [comment]
修改数据库配置文件的datetime_format参数即可
