### ISSUE TITLE
打开入口文件的时候报错

### ISSUE THREAD

**Issue by batmanSix** [top-think/think#705]
Warning: require(C:\WWW\tp5\public/../thinkphp/start.php): failed to open stream: No such file or directory in C:\WWW\tp5\public\index.php on line 17

Fatal error: require(): Failed opening required 'C:\WWW\tp5\public/../thinkphp/start.php' (include_path='.;C:\php\pear') in C:\WWW\tp5\public\index.php on line 17

**Comment by batmanSix** [comment]
下载下来后，没动过打开入口文件发现报错

**Comment by liu21st** [comment]
官方手册-》安装

**Comment by ximengnaikang** [comment]
我也是，已经购买你们的官方手册了，看了安装也是一脸懵逼

**Comment by liu21st** [comment]
@ximengnaikang 官方手册不需要购买 无论是手册还是教程 都会写清楚如何安装框架的
