### ISSUE TITLE
如何关闭thinkphp5的prepare statement 模式

### ISSUE THREAD

**Issue by forestkeeper** [top-think/think#707]
因为MYSQL服务端默认禁止了prepare statement模式，导致在服务端无法使用prepare statement
在thinkphp5运行中，由于有语句执行prepare statement，导致连接被服务器报错断掉。

执行了prepare statement的语句为 ```show columns from tableName```

**Comment by xiaohuilam** [comment]
这在生产环境开启.env的APP_ENV=production可以缓存，有缓存后就不在执行show columns了
