### ISSUE TITLE
从服务器根目录执行命令think,会出现报错

### ISSUE THREAD

**Issue by yanxuehui** [top-think/think#710]
[root@iZwz98g0pbul2Z ~]# php /home/wwwroot/amax/think
PHP Warning:  require(./thinkphp/console.php): failed to open stream: No such file or directory in /home/wwwroot/amax/think on line 17
PHP Fatal error:  require(): Failed opening required './thinkphp/console.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/amax/think on line 17

改为绝对路径就好了
// 加载框架引导文件
require __DIR__.'./thinkphp/console.php';

**Comment by liu21st** [comment]
你这是很老的版本了吧 早就改进过的
