### ISSUE TITLE
前置操作bug

### ISSUE THREAD

**Issue by muunnw** [top-think/think#713]
`/**
     * 前置操作
     * @access protected
     * @param string $method  前置操作方法名
     * @param array  $options 调用参数 ['only'=>[...]] 或者['except'=>[...]]
     */
    protected function beforeAction($method, $options = [])
    {
        if (isset($options['only'])) {
            if (is_string($options['only'])) {
                $options['only'] = explode(',', $options['only']);
            }
            if (!in_array($this->request->action(), $options['only'])) {
                return;
            }
        } elseif (isset($options['except'])) {
            if (is_string($options['except'])) {
                $options['except'] = explode(',', $options['except']);
            }
            if (in_array($this->request->action(), $options['except'])) {
                return;
            }
        }

        call_user_func([$this, $method]);
    }`

if (!in_array($this->request->action(), $options['only'])) {
                return;
            }
在检查only或except时，没有考虑到大小写。

**Comment by 3212lin** [comment]
如果不养成好的命名习惯 以后会经常被坑 在linux环境下是严格区分大小写
框架为什么非要兼容大小写？
