### ISSUE TITLE
日志信息不支持数组或JSON格式

### ISSUE THREAD

**Issue by muunnw** [top-think/think#714]
/**
     * 记录调试信息
     * @param mixed  $msg  调试信息
     * @param string $type 信息类型
     * @return void
     */
    public static function record($msg, $type = 'log')
    {
        self::$log[$type][] = $msg;
        if (IS_CLI) {
            // 命令行下面日志写入改进
            self::save();
        }
    }

在批量验证时，会批量返回错误
Log::record($validate->getError(), 'error');
会报错，原因是Array转String出错。

**Comment by liu21st** [comment]
我记得日志是支持数组的啊 会采用var_export方式记录
