### ISSUE TITLE
think\Route.php中的checkRoute函数中问题(V5.0.10)

### ISSUE THREAD

**Issue by LoveCodingLife** [top-think/think#717]
private static function checkRoute($request, $rules, $url, $depr = '/', $group = '', $options = [])
     {
          。。。

        //前面部分都省略...看下面
   
        if (isset($auto)) {
            // 自动解析URL地址
            return self::parseUrl($auto['route'] . '/' . $url, $depr);
        } elseif (isset($miss)) {
            // 未匹配所有路由的路由规则处理
            return self::parseRule('', $miss['route'], $url, $miss['option']);
        }
        return false;
    }

这里的$auto前面的代码中根本就没有定义，岂不是这里的if判断根本不起作用，始终走不到第一个if里去。

**Comment by lenvs** [comment]
这个问题,我也遇到了太坑了
