### ISSUE TITLE
模型如何切换数据库

### ISSUE THREAD

**Issue by fangxingguang** [top-think/think#720]
@liu21st 有业务需求，程序会连接两个相同数据库，请问同一个模型如果切换数据库连接？
尝试了继承Model后，在initialize方法内修改$connection不行，知道Db类有connect方法，但是我不想直接用Db类操作数据库，时候还有其他更好方式？

**Comment by liu21st** [comment]
创建两个不同的模型

**Comment by fangxingguang** [comment]
假如我有更多相同结构库，创建不同模型，感觉这样model下文件过多，因为模型间只差了一个 $connection参数，所以想能不能复用。
