### ISSUE TITLE
网站从http升级成https后，入口文件出现常量重复定义

### ISSUE THREAD

**Issue by Wythehard** [top-think/think#724]
从 http 的 80 端口请求连续一百多个请求都可以正常响应，
从 https 的 443 端口请求绝大部分请求都不能正常响应。

错误日志为：

    Notice: Constant APP_PATH already defined in /data/wwwroot/fx/public/index.php on line 16

    Notice: Constant THINK_VERSION already defined in /data/wwwroot/fx/thinkphp/base.php on line 12

    Notice: Constant THINK_START_TIME already defined in /data/wwwroot/fx/thinkphp/base.php on line 13

    Notice: Constant THINK_START_MEM already defined in /data/wwwroot/fx/thinkphp/base.php on line 14

    Notice: Constant EXT already defined in /data/wwwroot/fx/thinkphp/base.php on line 15

    Notice: Constant DS already defined in /data/wwwroot/fx/thinkphp/base.php on line 16

    Notice: Constant LIB_PATH already defined in /data/wwwroot/fx/thinkphp/base.php on line 18

    Notice: Constant CORE_PATH already defined in /data/wwwroot/fx/thinkphp/base.php on line 19

    Notice: Constant TRAIT_PATH already defined in /data/wwwroot/fx/thinkphp/base.php on line 20

    Notice: Constant IS_CLI already defined in /data/wwwroot/fx/thinkphp/base.php on line 34

    Notice: Constant IS_WIN already defined in /data/wwwroot/fx/thinkphp/base.php on line 35

    Fatal error: Cannot redeclare class think\Loader in /data/wwwroot/fx/thinkphp/library/think/Loader.php on line 16

有的时候也能正常返回 TP5 的 debug 页面，但是错误内容跟上面一样：Constant APP_PATH already defined。  一般 http 的状态码是 500，如果是 200 返回的不是空文件，就是错误信息。请问各位有没有好的解决办法？我现在唯一的解决办法就是走 http , 而不走 https。

**Comment by masterZSH** [comment]
你是咋升级的，弄个证书，配下服务器不就差不多了，可能你踩了坑哈哈

**Comment by Wythehard** [comment]
主要是不应该出现这个坑啊！

**Comment by Wythehard** [comment]
用的 certbot 自动部署的。
