### ISSUE TITLE
5.0.11 model 字段映射

### ISSUE THREAD

**Issue by JHChan314** [top-think/think#731]
现在模型没有字段映射了吗？

**Comment by masterZSH** [comment]
可以试下tp5新增的模型事件
新增一个Base类继承think\Model
`class  BaseModel extends  \think\Model{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $beFunc=function ($e){
            //修改  
            $e->data('username',$e->user);
            unset($e->user);

//            echo "<pre>";
//            print_r($e);
//            echo "<pre>";
//            exit();
        };
        #注册事件
        $this::event("before_insert",$beFunc);
    }
}`

插入数据
控制器中写
`  
$member =new \app\index\model\Member();
$data=[
            'user'=>'uss23d',//表字段是 `username`
            'password'=>'pwd',
            'logintime'=>time(),
            'loginip'=>'23'
        ];
        $res= $member->insertD($data);
`

Member类 继承Base类
`
 public function insertD($data)
    {
        $res= $this->save($data);
        return $res;
    }
`
这样虽然在外面数组里是user字段，正常插入的会错误的,这里注册了事件在提交时修改了提交字段名称，相当于user ---->username  自己改下差不多有字段映射功能的影子了。还有很多其他事件完全可以满足需求啦。
