### ISSUE TITLE
thinkphp5.0.7版本的input()函数

### ISSUE THREAD

**Issue by luoandy** [top-think/think#740]
thinkphp5.0.7版本的input()函数在PHP7.2.*版本input('get.')的时候 会把路由一起获取出来

`
Array
(
    [s] => /sell/goods/index
    [title] => 1111111
)
`

**Comment by luoandy** [comment]
附：服务器环境：Nginx 1.3.*

**Comment by ww24kobe** [comment]
apache环境也会，等待解决
