### ISSUE TITLE
针对redis 长连接,多编号库情况下改进

### ISSUE THREAD

**Issue by foxiswho** [top-think/think#745]
//配置
        $options        = [// 驱动方式
                            'type'   => 'Redis',
                            // 服务器地址
                            'host'   => '127.0.0.1',
                            'port'   => '6379',
                            'password'   => '',
                            'prefix' => '',
                            'select'  => '0',// 编号 0
                            'persistent'  => true,//长连接
    ];
        //配置2
        $options2        = [// 驱动方式
                           'type'   => 'Redis',
                           // 服务器地址
                           'host'   => '127.0.0.1',
                           'port'   => '6379',
                           'password'   => '',
                           'prefix' => '',
                           'select'  => '2',// 编号 2
                           'persistent'  => true,//长连接
        ];
        $cache=Cache::init($options);
        $cache2=Cache::init($options2);
        $redis=$cache->handler();
        //================
        $redis->set('33333333333===', '22222222', 600);
        //================
        $redis2=$cache->handler();
        $redis2->set('44444444444===', '22222222', 600);

        //结果是 所有的键值都在 编号为2 的库中

改进方方法：thinkphp/library/think/cache/driver/redis.php 文件中 51 行处
```php
$this->handler->$func($this->options['host'], $this->options['port'], $this->options['timeout']);
```
改为
```php
$this->handler->$func($this->options['host'], $this->options['port'], $this->options['timeout'],$this->options['persistent']?('persistent_id_'.$this->options['select']):null);
```

完美解决这个问题

**Comment by liu21st** [comment]
感谢反馈，已经改进
