### ISSUE TITLE
composer update  有问题  

### ISSUE THREAD

**Issue by qq907274532** [top-think/think#756]
thinkphp5 composer update  下来代码回报   `Non-static method think\App::run() should not be called statically`

**Comment by liu21st** [comment]
你估计是更新到5.1版本了吧 改下composer.json 更新下依赖 然后重新update

**Comment by qq907274532** [comment]
composer 里面放的是最新的？而不是最稳定的？

**Comment by kinosang** [comment]
@qq907274532 packagist 是所有版本的 (pre)release 和 master。

具体请参阅 composer 和 packagist 手册.
