### ISSUE TITLE
最新版的框架代码报错

### ISSUE THREAD

**Issue by qq907274532** [top-think/think#757]
最新版的框架代码会报 `
Warning: require(/var/www/ylct/core/vendor/topthink/think-helper/src/helper.php): failed to open stream: No such file or directory in /var/www/ylct/core/thinkphp/library/think/Loader.php on line 656

Fatal error: require(): Failed opening required '/var/www/ylct/core/vendor/topthink/think-helper/src/helper.php' (include_path='.:/php/includes') in /var/www/ylct/core/thinkphp/library/think/Loader.php on line 656`

**Comment by aliyunqcloud** [comment]
检查是否有文件读写权限，免费提供建站咨询，另如有需要低价服务器（ 最低1元/日起 ）的请点击以下链接：
阿里云内购：http://aliyun.52it.club
腾讯云内购：http://qcloud.52it.club
