### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by qq907274532** [top-think/think#758]
不是5.1啊
`{
    "name": "topthink/think",
    "description": "the new thinkphp framework",
    "type": "project",
    "keywords": [
        "framework",
        "thinkphp",
        "ORM"
    ],
    "homepage": "http://thinkphp.cn/",
    "license": "Apache-2.0",
    "authors": [
        {
            "name": "liu21st",
            "email": "liu21st@gmail.com"
        }
    ],
     "repositories": {
    	"packagist": {
        	"type": "composer",
        	"url": "https://packagist.phpcomposer.com"
    	}
	},
    "require": {
        "php": ">=5.4.0",
        "topthink/framework": "^5.0",
        "topthink/think-image": "^1.0",
        "topthink/think-captcha": "^1.0",
        "topthink/think-mongo": "^1.0",
        "topthink/think-migration": "^1.0",
        "topthink/think-angular": "^1.0",
        "topthink/think-sae": "^1.0",
        "topthink/think-worker": "^1.0",
        "topthink/think-queue": "^1.0",
        "topthink/think-testing": "^1.0",
        "phpmailer/phpmailer": "^5.2"
    },
    "extra": {
        "think-path": "thinkphp"
    },
    "config": {
        "preferred-install": "dist"
    }
}`

**Comment by kinosang** [comment]
dup, #756
