### ISSUE TITLE
数据库更新操作没有使用cache却一直创建cache下的文件夹

### ISSUE THREAD

**Issue by phpth** [top-think/think#764]
环境主要参数配置：
` 'app_debug'              => false,
    // 应用Trace
    'app_trace'              => false,
     // 数据库调试模式
    'debug'           => false,
` 
使用mysql数据库，更新操作在where条件为数组条件且只有一个参数的时候会在
在runtime/cache文件夹一直创建0a,0b等等并无内容的文件夹，影响数据库操作性能

**Comment by liu21st** [comment]
感谢反馈，已经修正

**Comment by phpth** [comment]
已经发版本了吗？哪个版本号是修复版本？ 因为我composer update 没有更新内容

**Comment by liu21st** [comment]
指示git更新 composer 等下一个版本更新
