### ISSUE TITLE
log 类驱动为File在cli多进程模式下会造成死锁

### ISSUE THREAD

**Issue by phpth** [top-think/think#765]
调试模式的log，在cli开启多进程执行消费任务的时候回因为log文件超出配置大小的时候限制进行备份重写的时候回产生死锁。目前怀疑的代码问题为：
`` //检测日志文件大小，超过配置大小则备份日志文件重新生成
        if (is_file($destination) && floor($this->config['file_size']) <= filesize($destination)) {
            rename($destination, dirname($destination) . DS . time() . '-' . basename($destination));
            $this->writed[$destination] = false;
        }

**Comment by phpth** [comment]
已经修复了吗？还是确认没问题？

**Comment by liu21st** [comment]
已经修正
