### ISSUE TITLE
平台路径自适应 app_path appPath

### ISSUE THREAD

**Issue by yangmeishu** [top-think/think#768]
版本 5.1

请问，为何App.php
linee 166 167等
initialize方法设定path时，路径符号不设定为DIRECTORY_SEPARATOR平台自适应呢

**Comment by daocast** [comment]
入口文件确实无法使用 path 方法来设置
`
Container::get('app')->path(__DIR__ . '/app/')
`

**Comment by liu21st** [comment]
这个改进过了
