### ISSUE TITLE
🐛多对多关联插入 插入到其他的表

### ISSUE THREAD

**Issue by tyaqing** [top-think/think#770]
```
    //  关联点赞表 废弃
    public function like(){
        return $this->belongsToMany('User','xiaoan_post_like','user_id','post_id');
    }
    // 查看是否观看表
    public function viewed(){
        return $this->belongsToMany('User','xiaoan_post_viewed')->field(['nickname','headimgurl','dp_xiaoan_user.id']);
    }

```
上述都是 Post 模型下的关联方法
当我使用 `$post->viewed()->attach(USERID); `方法时 数据居然插入到`xiaoan_post_like`表中
我打印了返回数据 返回的对象 里面的表也是xiaoan_post_viewed 没错哇
惊奇的来了!
当我 用`with('viewed') `之后, `$post->viewed()->attach(USERID); `插入了正确的表.是不是字段缓存的bug呢?

**Comment by ixingjue** [comment]
狗比tp5  完全抄袭laravel  不伦不类的东西  不如干脆学laravel  国内的生态比tp都强了
