### ISSUE TITLE
内置服务器 route加载有问题

### ISSUE THREAD

**Issue by QThans** [top-think/think#773]
默认只加载了route文件夹中的第一个 route.php没有加载

**Comment by QThans** [comment]
看了下代码，都遍历出来了，但是不知道为什么 内置服务器只成功加载了第一个

**Comment by QThans** [comment]
![image](https://user-images.githubusercontent.com/18275400/35664180-d7b1661e-075b-11e8-9c76-12201508d689.png)
![image](https://user-images.githubusercontent.com/18275400/35664183-dbf3b4de-075b-11e8-80c8-5d3c83d94597.png)

**Comment by liu21st** [comment]
我修正了下 多了一个路径斜杠

**Comment by QThans** [comment]
代码在哪？我看下  O(∩_∩)O谢谢

**Comment by QThans** [comment]
看到了

**Comment by QThans** [comment]
![image](https://user-images.githubusercontent.com/18275400/35665033-5829dfee-075f-11e8-99f3-eb9f83c1ead0.png)
加载上还是有问题 和服务器的加载不一样
