### ISSUE TITLE
think\Db中的field方法报错提交

### ISSUE THREAD

**Issue by easychn** [top-think/think#777]
think\Db中，这段代码：

        if (isset($this->options['field'])) {
			dump($this->options);
			dump(getType($this->options));
			dump($field);
			dump(getType($field));
            $field = array_merge($this->options['field'], $field);
        }
，只判断了isset($this->options['field']),没有判断$this->options['field']是否是数组，
当$this->options['field'] == ‘*’时，array_merge()会报错。
在某些情况下，使用如下方式：
Db::table('think_user')->field('*')->select();
Db::table('think_user')->field(true)->select();
读取数据时，$this->options['field'] 的值为'*',
array_merge()会报错。

附：
    /**
     * 指定查询字段 支持字段排除和指定数据表
     * @access public
     * @param mixed   $field
     * @param boolean $except    是否排除
     * @param string  $tableName 数据表名
     * @param string  $prefix    字段前缀
     * @param string  $alias     别名前缀
     * @return $this
     */
    public function field($field, $except = false, $tableName = '', $prefix = '', $alias = '')
    {
        if (empty($field)) {
            return $this;
        }

        if (is_string($field)) {
            $field = array_map('trim', explode(',', $field));
        }

        if (true === $field) {
            // 获取全部字段
            $fields = $this->connection->getTableFields($tableName ?: (isset($this->options['table']) ? $this->options['table'] : $this->getTable()));
            $field  = $fields ?: ['*'];
        } elseif ($except) {
            // 字段排除
            $fields = $this->connection->getTableFields($tableName ?: (isset($this->options['table']) ? $this->options['table'] : $this->getTable()));
            $field  = $fields ? array_diff($fields, $field) : $field;
        }

        if ($tableName) {
            // 添加统一的前缀
            $prefix = $prefix ?: $tableName;
            foreach ($field as $key => $val) {
                if (is_numeric($key)) {
                    $val = $prefix . '.' . $val . ($alias ? ' AS ' . $alias . $val : '');
                }
                $field[$key] = $val;
            }
        }

        if (isset($this->options['field'])) {
			dump($this->options);
			dump(getType($this->options));
			dump($field);
			dump(getType($field));
            $field = array_merge($this->options['field'], $field);
        }

        $this->options['field'] = array_unique($field);

        return $this;
    }

**Comment by liu21st** [comment]
改进了~
