### ISSUE TITLE
tp5.1连接oracle

### ISSUE THREAD

**Issue by 8000cabbage** [top-think/think#779]
用composer安装了topthink/think-oracle:2.0库，不确定是否该用maset分支的库
配置成功后，查询可以，但是插入不顺利
请问insert默认不填写自增主键怎么处理
按照mysql方法报错General error: 1400 OCIStmtExecute: ORA-01400: 无法将 NULL 插入。
手动填写主键后可以成功插入，但是会报错
General error: 936 OCIStmtExecute: ORA-00936: 缺失表达式，sequence要手工传入吗
看起来没有拼写%LOCK%部分

**Comment by liu21st** [comment]
使用sequence方法设置自增序列名
