### ISSUE TITLE
Env alway get null

### ISSUE THREAD

**Issue by robertzengcn** [top-think/think#780]
.env文件里的一些配置，在前端异步多次请求情况下会出现获取不到配置值的问题
错误如下

[ 2018-03-09T16:37:34+08:00 ] 127.0.0.1 127.0.0.1 POST /Sales_System/htdocs/index/orders/getcurrencylist
[ error ] [1045]SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
---------------------------------------------------------------
[ 2018-03-09T16:37:34+08:00 ] 127.0.0.1 127.0.0.1 POST /Sales_System/htdocs/index/orders/getcountrylistxjson
[ error ] [1045]SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
---------------------------------------------------------------
[ 2018-03-09T16:37:34+08:00 ] 127.0.0.1 127.0.0.1 POST /Sales_System/htdocs/index/orders/queryuserattach
[ error ] [1045]SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

**Comment by liu21st** [comment]
5.1的Env类重写了
