### ISSUE TITLE
tp5.1和think-migration不兼容

### ISSUE THREAD

**Issue by tu6ge** [top-think/think#782]
return $this->getConfig('path', ROOT_PATH . 'database') . DS . 'seeds';
应该改成
return $this->getConfig('path', Env::get('root_path') . 'database') . DS . 'seeds';
但是这里的DS不知道该改成什么

**Comment by kokororin** [comment]
`DIRECTORY_SEPARATOR`了解一下

**Comment by tu6ge** [comment]
谢谢你的提醒，因为不兼容，我已经弃用了，建议官方把这个兼容性改改
就是composer.json

**Comment by liu21st** [comment]
你安装的是1.*版本 如果是5.1需要安装2.0版本
