### ISSUE TITLE
thinkphp5.1在nginx环境路由不论怎么修改路由，都只能指向index控制器index方法

### ISSUE THREAD

**Issue by heyroc** [top-think/think#783]
请问有人遇到下载think PHP之后在本地apache环境下路由正常，修改成nginx环境无法访问出了首页外的任何方法和控制器，不管在地址栏输入什么方法都跳转不过去，永远都是在首页指向index控制器index方法，在百度上找的修改nginx虚拟主机配置的方法无效：
```
if (!-e $request_filename) {
    rewrite  ^(.*)$  /index.php?s=/$1  last;
    break;
}
```
求大婶们应该怎么配置nginx或者修改thinkphp里的路由配置，抱拳了！！

**Comment by yunshu2009** [comment]
是这样配的，记得重启Nginx
