### ISSUE TITLE
模板输出 运行到$content = ob_get_clean(); 超时

### ISSUE THREAD

**Issue by QThans** [top-think/think#786]
如题。
昨晚程序正常，今天突然504超时。
经过排查，发现问题出在library/think/view.php的176行，$content = ob_get_clean(); 这边超时

**Comment by QThans** [comment]
![image](https://user-images.githubusercontent.com/18275400/38159692-7a7df1da-34e0-11e8-93bc-8262a2d2d4f4.png)

这样之后不chao's超时

**Comment by QThans** [comment]
一直fetch循环了

**Comment by liu21st** [comment]
你要从模板找问题根源
