### ISSUE TITLE
翻页 问题

### ISSUE THREAD

**Issue by ypleewood** [top-think/think#787]
在同一个方法中两次调用同一个查询，同一个表不同类型的数据，前后两次查询的offset是同一个值，但是后一个应该为0

后一次生成sql
"SELECT * FROM `t_class` WHERE ( `type` = 41 ) AND `t_class`.`delete` = '0' ORDER BY class_id DESC LIMIT 80,20"

因为首次查询type=40的列表进行翻页，导致第二次查询出错

**Comment by liu21st** [comment]
5.1每次查询后不会清空查询条件的

**Comment by ypleewood** [comment]
每次查询完需要自己手动清空上次查询条件？
需要怎么做呢

**Comment by liu21st** [comment]
基本上不需要手动清理，因为每次静态查询都是全新的查询。如果确实需要 可以使用removeOption('where')
