### ISSUE TITLE
tp5.1.8 框架中使用命令行创建控制器失败

### ISSUE THREAD

**Issue by xue-y** [top-think/think#788]
环境是php7.0.12+apache； 感觉是框架的某些语法php7不支持；请问怎么解决

D:\phpStudy\WWW\tp>php think make:controller app\index\controller\User
PHP Parse error:  syntax error, unexpected '[', expecting ')' in D:\phpStudy\WWW\tp\thinkphp\base.php on line 32
PHP Stack trace:
PHP   1. {main}() D:\phpStudy\WWW\tp\think:0

Parse error: syntax error, unexpected '[', expecting ')' in D:\phpStudy\WWW\tp\thinkphp\base.php on line 32

Call Stack:
    0.0009     323664   1. {main}() D:\phpStudy\WWW\tp\think:0

**Comment by liu21st** [comment]
不是框架不支持PHP7 是你的命令行版本根本不是7
