### ISSUE TITLE
在模块下的config.php 设置controller_auto_search参数开启自动定位控制器的做法不能生效

### ISSUE THREAD

**Issue by Liangkk** [top-think/think#789]
环境如下
tp版本:V5.0.16
php版本 7.1

application目录下的config.php 中的controller_auto_search=false
index目录下的config.php 中的controller_auto_search=true
这种情况下,http://serverName/index.php/index/one/Blog 是不可以正常访问的

**Comment by liu21st** [comment]
所有和url及路由相关的 模块配置都是无效的
