### ISSUE TITLE
redis 配置信息合并后调取是不是写错了

### ISSUE THREAD

**Issue by kbitlive** [top-think/think#79]
源代码是直接用$options 去调的
下图是我改的 不知道对不对  

![image](https://cloud.githubusercontent.com/assets/12296964/11833837/a4c5f662-a401-11e5-877a-f4726d814dd3.png)

**Comment by kbitlive** [comment]
redis 时间失效时间 有点问题

**Comment by liu21st** [comment]
@kbitlive 已经修正~谢谢反馈
