### ISSUE TITLE
ThinkPHP 5.1 的Db::execute无法执行DDL语句

### ISSUE THREAD

**Issue by cw1997** [top-think/think#795]
执行DDL会报SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP TABLE IF EXISTS `xxx`;，DDL语句是SQL中导出的，手动执行正常，说明不是DDL语句有误。

**Comment by liu21st** [comment]
PHP是不支持执行多条sql语句的

**Comment by liu21st** [comment]
所有的数据库驱动都是基于PDO的 多条sql查询提供了额外的方法 但必须传入数组
