### ISSUE TITLE
自动更新时间的问题

### ISSUE THREAD

**Issue by jin123456bat** [top-think/think#796]
使用model的时候开启了updateTime假如更新后的数据和更新前的数据一样不会更新这个时间，导致save函数返回false，这个设计感觉很鸡肋啊，跟mysql中的ON UPDATE CURRENT_TIMESTAMP一样的效果，如果期望save返回true，还需要手动填充updateTime

**Comment by liu21st** [comment]
数据一样 等于没更新 要更新时间干嘛？除非你就是为了更新时间字段，那么就请手动更新时间后save

**Comment by liu21st** [comment]
save方法的返回值不需要判断 所有的数据库操作出错都是抛出异常
