### ISSUE TITLE
5.1模型进行关联更新为什么没有使用事务啊？

### ISSUE THREAD

**Issue by cw1997** [top-think/think#799]
![r18 kmn xl7 s a 48kn s](https://user-images.githubusercontent.com/11588555/39591074-37e26b16-4f35-11e8-97d1-34c205f9a6a5.png)
![py c 12 9h9 de ft 5qcq](https://user-images.githubusercontent.com/11588555/39591086-3fa99b76-4f35-11e8-8f49-38488fd4d180.png)
看了一下save方法返回的也只是主表的写入影响行数，没有检查关联表写入是否成功。这个地方是否有待改进啊？

**Comment by leruge** [comment]
自己开启事务也不麻烦，代码中实现事务，还要引擎支持事务，

**Comment by cw1997** [comment]
@leruge 我觉得这个可以做成单个模型的配置项，让用户选择是否使用事务，不然这种关联更新太危险了，我相信大部分人都不会用物理外键把，线上要是某个关联表更新失败导致数据不一致，那就麻烦了。
