### ISSUE TITLE
where()数组方式查询报错BUG

### ISSUE THREAD

**Issue by admininfon** [top-think/think#809]
版本 5.1.14 where 查询存在问题，我本地的php7.0.12
字符串 形式的 NOT IN：
![image](https://user-images.githubusercontent.com/22093516/40571232-e41ac060-60c7-11e8-824a-432aefcf2757.png)
![image](https://user-images.githubusercontent.com/22093516/40571238-eeb21492-60c7-11e8-88b6-3ab5e984a83a.png)
数组形式的 NOT IN：
![image](https://user-images.githubusercontent.com/22093516/40571239-ff6f905c-60c7-11e8-9ef1-9dfbdc688fd6.png)
![image](https://user-images.githubusercontent.com/22093516/40571240-033b566c-60c8-11e8-8d54-6a28436db72f.png)

**Comment by zhanghaidi** [comment]
出现过类似情况，你把$where加一个[]

**Comment by admininfon** [comment]
$model->where(['key',  'not in', array(1,2,3,4)])
这个查询语句，老是解析成 in 查询。

**Comment by liu21st** [comment]
仔细看手册 如果数组不会用 就不要用数组建议
