### ISSUE TITLE
强烈要求模型静态方法增加成功与否返回值

### ISSUE THREAD

**Issue by crazys1973** [top-think/think#811]
特别是Create()，Update()方法。
这两个模型静态方法，语义清晰，用法简单，但是返回的是整个模型，无法判断成功状态，强烈要求把函数内部的save结果放在result属性中返回。
我自己改了，但总感觉官方可能有更多的考虑，不知道是不是这样。
我希望代码能写成如下的样子：

return Model::Create($data)->result ? true : false;

**Comment by JerryChaox** [comment]
你只要try catch 没有异常抛出来就是成功

**Comment by liu21st** [comment]
返回模型对象本身的设计是为了更方便后续的操作 至于是否成功这种 要么成功 要么就抛出异常了
