### ISSUE TITLE
对自定义路由支持增强

### ISSUE THREAD

**Issue by jin123456bat** [top-think/think#812]
现在的路由貌似都只能针对url中的REQUEST_URI识别并绑定模块控制器和方法，无法针对其他数据比如post中的数据来识别
一个很现实的例子：我们在对接微信的时候，微信推送的消息通常是post请求，请求体是一个xml结构，微信的异步通知接口也只有一个，假如相关业务逻辑比较复杂，很容易导致一个action中代码上千甚至上万行，而通常开发者的解决方案都是引入各种千奇百怪的函数，导致维护成本越来越高，这完全相悖与mvc模式的初衷
还拿微信举例，开发者其实更加期望能够自定义的识别请求中的任何参数，根据参数来做动态式的绑定，
比如：建立一个wechat模块，微信推送点击事件的时候，可以自定义到click控制器中，当推送扫码事件的时候，可以自定义绑定到event控制器中，当推送文字可以自定义到message控制器中，开发者又可以根据消息类型执行text方法或者image方法等等

**Comment by jin123456bat** [comment]
现阶段我们都是在路由中间件中来做这个事情，但是这种做法感觉很奇怪。

**Comment by leruge** [comment]
这个人提了很多奇怪的问题，而且大部分问题表达都不清楚，你问问题前，我觉得先去问下旁边的人，旁边的人觉得你表达的没问题了，问题描述清楚了再来问吧，看你问的这几十个问题，我都想不关注tp了

**Comment by liu21st** [comment]
路由参数有一个自定义路由验证的功能，可以解决你的问题

**Comment by jin123456bat** [comment]
@leruge 你脑子有问题吗？这么简单的问题所有人都看明白了就你没看明白，看来问题挺严重的。。。

**Comment by jin123456bat** [comment]
@liu21st 3Q

**Comment by leruge** [comment]
对了，傻逼，就说你这个问题吧，不同请求参数访问不同控制器方法，先不说你表达问题，就你说什么什么违背mvc，代码成千上万行，你到底是什么脑子能说出这种话？

**Comment by leruge** [comment]
流年，给框架再加一个接受json,xml数据的方法吧，不然以后还是会有想这个脑残一样，问一些脑残问题

**Comment by leruge** [comment]
流年你可能理解错了，这个脑残要的不是验证功能，他要的是比如请求参数中name可能的值有a,b,c,abc分别对应不同控制器方法，这个脑残的表达，我是真的服气，他前面的问题也是类似的情况，说不明白话

**Comment by jin123456bat** [comment]
请大家无视这个@leruge 猪，我问的问题我都没说啥，你倒bb一大堆，你要是说你不是脑残估计连你妈都不信吧

**Comment by leruge** [comment]
哈哈，看看你问问题的描述表达，真替你智商堪忧，问问题能把自己问迷糊了也是很厉害的。
