### ISSUE TITLE
Debug模式下，每次修改模版替换字符串都要手动删除缓存，

### ISSUE THREAD

**Issue by cw1997** [top-think/think#814]
也就是这个tpl_replace_string，如果模版替换字符串需要频繁修改，那么开发起来会比较麻烦。
如果能够在debug模式下自动读取配置文件，更新模版缓存就好啦！

**Comment by liu21st** [comment]
5.0 调试模式是每次重新生成模板缓存的
5.1 不建议用这个 而是用控制器的filter方法处理

**Comment by cw1997** [comment]
谢谢，明白了！
