### ISSUE TITLE
5.0的验证器方法今天放到5.1里不生效了

### ISSUE THREAD

**Issue by orchie** [top-think/think#819]
我之前用5.0时写的一种通用验证器方法
在common模块写一个基类，里面判断场景验证
`        $this->r=request()->param();
        $this->c=request()->controller();
        $this->a=request()->action();
        //表单验证
        if(request()->isPost()){
            $v=validate($this->c);
            if($v->hasScene($this->a)){
                $res=$this->validate($this->r,$this->c.'.'. $this->a);
                if(true!==$res)$this->error($res);
            }
        }
`
其他模块的都继承这个类
然后在common的validate中定义验证器的基类，把常用的rules都放进去
然后其他模块的validate中对应控制器的验证器继承这个类

这样可以高效复用代码，在5.0中也是可行的

但在5.16中 验证器不应该通过的 
$this->validate($this->r,$this->c.'.'. $this->a);
这句也通过了 
hasScene是有效的可以判断是否存在该场景
但验证无效，不管rule是啥 参数对不对 都返回true

看了下更新日志 
跟validate相关的只有 RC3版本（2017-11-6）
改进App类的controller和validate方法支持多层

**Comment by orchie** [comment]
看了下更新日志 
跟validate相关的只有 RC3版本（2017-11-6）
改进App类的controller和validate方法支持多层

**Comment by leruge** [comment]
看了你写的验证器验证数据，没有发现你那里实现了代码复用了，明明是增加了很多代码量和代码复用的更少了，你这种写法需要每个控制器都得有一个验证类，明明很多控制器可以共用一个验证类的，还有就是，直接指定请求的验证器类，而不用控制器名字判断验证器类，会让程序更快运行

**Comment by orchie** [comment]
1.**验证失效原因**
今天在对比5.0与5.1验证器文档时发现关于验证器 有一段文档 在5.1没了 [手动笑哭]
> 验证规则和提示信息一起定义
>5.0文档 https://www.kancloud.cn/manual/thinkphp5/129321
>5.1文档 https://www.kancloud.cn/manual/thinkphp5_1/354103
而我为了简洁 之前是用的 验证规则和提示信息一起定义 的方式去写的 rules
然后在5.1失效了

2.更蛋疼的问题 **不管数据是否符合规则都验证失败**
把验证规则分开写之后，验证器生效 并且 一直 都验证失败
而且提示的报错信息 并不是我设置的信息【也不是tp例子中的信息 如 age只能在 1 - 120 之间】
是这样的

<img src="http://wx2.sinaimg.cn/mw690/91e65219ly1fs4xstxkqlj208p07fa9z.jpg"  />

3.关于代码复用 (_不重要_)
我最初写的时候肯定也想着少写些代码，不知道为啥写成了一个控制器一个validate，刚试了把一个模块的验证器集中到一个validate是没问题的，用当前模块判断。不过场景还是用控制器+场景来判断的，这样才能实现对应验证啊，不然每个方法里去调用验证就没有这个复用的意义了。

4.**代码见附件**
看到issue里把贴的代码弄成一行了 就不粘贴了，贴个主图，然后其他代码传附件里。
这个代码是我更新后的 (只是更新了复用方式)

[application.zip](https://github.com/top-think/think/files/2086725/application.zip)

感谢大佬百忙中解答 @liu21st @leruge

**Comment by hongweipeng** [comment]
5.1的验证规则定义方式有所改变，在从5.0升级到5.1文档中没有说明，这是文档的缺失。
