### ISSUE TITLE
开启了请求缓存以后，有办法让数据不使用缓存吗？

### ISSUE THREAD

**Issue by 305530751** [top-think/think#820]
做了一个博客系统，文章内容基本是不会发生变化的，就想使用缓存，但是还想让用户点击一次文章的阅读量就加一次，有办法实现吗？

**Comment by liu21st** [comment]
请求缓存也是有有效期的 又不是一直缓存

**Comment by leruge** [comment]
在缓存有效期内，是不能操作数据库的吧？

**Comment by liu21st** [comment]
请求缓存只是get有效

**Comment by 305530751** [comment]
@liu21st 我觉得我问的很清楚了，我问的是有没有办法能让表中的阅读量字段加1，你咋老是回答请求缓存有效期，请求缓存get有效，难道别人都是傻子？不知道这个情况，还是你理解不了我要实现的功能，第一次说什么有效期我就忍了，再说get有效，你是来恶心tp用户的吗？

**Comment by 305530751** [comment]
你不想回答，想恶心tp用户，可以，但是可以不要恶心完了还关闭问题吗？

**Comment by liu21st** [comment]
@305530751 很抱歉 我有些回复可能不是针对你的。让表中的阅读量加1 看你怎么设计了 如果是异步的就没什么问题
