### ISSUE TITLE
命令行生成缓存文件异常报错

### ISSUE THREAD

**Issue by saybabi** [top-think/think#826]
#### 执行环境
php-version: 7.1.16
tp-version:    5.1.14
#### Step1 执行
~~~ bash
php think optimize:config
~~~
>结果: Succeed!
#### Step2  执行
~~~bash
php think optimize:autoload
~~~
>Fatal error: Cannot use think\Container as Container because the name is already in use in C:\Program Files (x86)\Jenkins\workspace\dev\runtime\init.php on line 39
>Call Stack:
    0.2010     353720   1. {main}() C:\Program Files (x86)\Jenkins\workspace\dev\think:0
    0.2080     679048   2. think\App->initialize() C:\Program Files (x86)\Jenkins\workspace\dev\think:19
    0.2110     746392   3. think\App->init(???) C:\Program Files (x86)\Jenkins\workspace\dev\thinkphp\library\think\App.php:234
[think\exception\ErrorException]
  Cannot use think\Container as Container because the name is already in use
Exception trace:
 () at C:\Program Files (x86)\Jenkins\workspace\dev\runtime\init.php:39
 think\Error::appShutdown() at n/a:n/a

**Comment by QThans** [comment]
你自己的自定义命令行有类用Container这个名称吗？
看报错是名称重复使用  建议仔细检查下

**Comment by saybabi** [comment]
在 common.php 下使用了
~~~
use think\Container;

Container::getInstance()->bindTo('http', '\GuzzleHttp\Client');
Container::getInstance()->bindTo('redis', '\Predis\Client');
~~~

**Comment by liu21st** [comment]
@saybabi 不需要这样设置，直接配置provider.php 文件 返回数组即可

**Comment by saybabi** [comment]
哦，这样子。 没问题了
