### ISSUE TITLE
关于框架更新的问题

### ISSUE THREAD

**Issue by guigui0326** [top-think/think#828]
更新核心框架是比较方便的，直接同步就行。
但更新应用项目时一般都怎么更新呢，因为本身的一些配置以及项目文件都被调整。
求大佬指点。万分感谢~

**Comment by liu21st** [comment]
应用一般不需要更新，配置文件你可以拷贝或者自己设置

**Comment by guigui0326** [comment]
嗯嗯 好的 谢谢。但是如果想更新应用的话还是需要自己手动去调整的吧

**Comment by liu21st** [comment]
只要不是大版本更新，应用的架构和代码不会调整，主要是配置的增加，这块自己调整就行了~
