### ISSUE TITLE
批量删除出现bug

### ISSUE THREAD

**Issue by JackLeeCH** [top-think/think#829]
目的：通过id在项目表中批量删除数据，控制器代码：
`$id = input('post.id');
        // $result = model('Project')->where($where)->delete();

        $projects = model('Project')->where('id', 'in', $id);
        $result = $projects->delete();
        echo model('Project')->getLastSql();
        if($result){
            $this->success('项目删除成功', 'project/projectlist');
        }else {
            $this->error('项目删除失败！');
        }`
查看执行的sql语句为：
UPDATE `tp_project`  SET `tp_project`.`delete_time` = NULL  WHERE  `id` IN (1,2,3)
是我的写法有问题，只能单独删除，还是说这里确实是个bug？

**Comment by momoca** [comment]
请先看看文档.
https://www.kancloud.cn/manual/thinkphp5_1/354044
用法不对.

**Comment by liu21st** [comment]
这个问题修正过的 可以用最新的git版本测试下

**Comment by JackLeeCH** [comment]
确实改过了，但是改成这样了：
DELETE FROM `tp_project` WHERE (  `id` IN (7,8) ) AND `tp_project`.`delete_time` IS NULL
我自己看着改吧……

**Comment by liu21st** [comment]
既然用了软删除 就遵循统一的规范操作删除，最佳的实践要么直接Db类删除 要么就用模型的删除方法
