### ISSUE TITLE
ThinkPHP V5.1.18 跨模块调用作用域问题

### ISSUE THREAD

**Issue by kl521516** [top-think/think#830]
1、分别有a模块和b模块，它们都有各自数据库配置文件

2、我在a模块里调用b模块控制器中的函数，该函数却使用了a模块的数据库配置

3、我怎么才能让它使用b模块中的数据库配置文件

**Comment by liu21st** [comment]
换个设计思路吧 把需要跨模块或者全站调用的东西 独立出来
