### ISSUE TITLE
tp5 远远不如tp3.2

### ISSUE THREAD

**Issue by aqnaruto** [top-think/think#831]
居然抄laravel这种垃圾框架，难道是作者二本生的局限性？
tp5代码量更多，更复杂，性能更低。

可否告诉我 tp5这样严重退步的初心是什么？

**Comment by momoca** [comment]
如果你在进步,就不会认为tp5在退步
tp5进步的.这是无疑的.更专业,也更易读.用tp5进行api编写真的方便很多.
再有laravel和tp5只是有一些地方像.但这怎么能叫抄.
.tp3和tp5确实可以说各有各的优点,

最后举两个生活的例子帮你理解吧:
**关于laravel**,你能说,别人也有双手双脚就是抄你的了?所有哺乳动物都是互相抄的?
**关于tp3和tp5**,古代人认为天方地圆,但如果你活到现在,还认为天方地圆.那不是世界的问题了.

**Comment by aqnaruto** [comment]
抄没什么大不了的，我可以换个文雅的词：借鉴。只是laravel这种糟粕真的没有价值。
@momoca 你告诉我tp5哪个地方比tp3.2好？

**Comment by momoca** [comment]
哎...
坚持认为天圆地方的人.别人怎么说地球是圆的你也不会信的.
我可不想变成乔尔丹诺．布鲁诺...

**Comment by aqnaruto** [comment]
@momoca 那你就撤退吧，你这种phper 我见的多了。除了跟风“优雅”，要他说个 优点123456 来，结果一个都说不出。

**Comment by aqnaruto** [comment]
@kinosang 有本事你敢过一会再关，等你们说出tp5的优势来？

**Comment by kinosang** [comment]
Issue is not a function to blame, it's for bugs, problems, and questions.

**Comment by kinosang** [comment]
Though I've close this issue, I didn't lock it, you can still comment on, and reopen this issue if you want.

But please DO NOT abuse issue, or we'll lock it or block you from this repo.

**Comment by aqnaruto** [comment]
@kinosang  也可以for enhancement 。提出了你这个是退步 ，算不算bug？

**Comment by kinosang** [comment]
@aqnaruto If you found any faults or shortcoming please point them out **clearly**.

**Comment by aqnaruto** [comment]
@kinosang 我来例举一下  对比tp3.2的缺点
1、完成同样的功能编码量增多了。1.1 本来我只需要一个M(),现在我要引入一个db类，我是不是多写了一个引入的代码，1.2还有我熟悉的那些字母也没有了，抛弃以前的用户习惯就不说了，就说多打几个字母，我代码量也增加了。1.3 路由，路由变得还需要手动写了  1.4 .....
2、性能降低了，自己去看评测 不用我多说。
3、复杂性提高，冗余代码多。冗余代码是指，有些东西根本永远不可能用上，想db里面的那么多方法，你真以为用户会全部用上吗？还什么whereNotNull 之类的各种方法都能搞出来，有这个闲心 别人早就原生sql写出来了，照着你这上的写，可读性降低还以后不好改造，你确定你们真的在think吗？用户用你这个activeRecord 就是为了省心不是为了 看一下你文档写一行代码的

**Comment by liu21st** [comment]
1 之前的M('user') 现在用 db('user') 没有任何区别 升级指导也写清楚了，至于单字母函数，你是可以随便定义的，路由也一样有默认规则；
2 性能不重要，要性能你直接用原生，况且在同类主流框架里面 TP5性能依然领先；
3 你不要用你的需求去理解别人的需求；

在我看来，其实抱怨没有意义，TP十多年的初衷是为了让开发变得更简单，历史的车轮在滚滚前进，不会因为某些人的排斥和不能接受就保持原状，官方也没说过3.2不好。但是，不进则退！新的版本已经是大势~

**Comment by aqnaruto** [comment]
@liu21st 欣赏这种【不会因为某些人的排斥和不能接受，抱怨没有意义】，要坚持自己，不要去跟风。
当开始有人抱怨tp的字母可读性不好，我却觉得这给我带来了便利。

速度差个百分之二三十的确不重要，一两倍则是可以感受到的差距了。

开始国内的拥戴者支持tp，是因为tp足够简单，够用，好用，冗余低，有人在鼓吹laravel时，我一口盐汽水呛死他。
tp5，好多方法 像数据库里的操作 和laravel，像ioc 基本上百分之八十类似，不说抄了，至少给人的感觉是tp摈弃了自己原有的特性 迎合了laravel的思想。

什么是大势，  只有开发者自己去选择适合自己的。就像鸟哥要做yaf，张根硕要做swoole 都不是迎合大势，而是创造了独特的价值，最终开发者认可他们，接纳了他们。

**Comment by QThans** [comment]
我们也认可tp，觉得tp适合自己 更认可tp5 @aqnaruto

**Comment by aqnaruto** [comment]
呵呵，不用说了，思想已经分道扬镳，这周我写个框架，基于tp3.2 您们要是情愿 就给我开个分支。名字我已经想好了，叫mozart.php

**Comment by QThans** [comment]
非主流

**Comment by QThans** [comment]
出来了@一下 前来学习

**Comment by momoca** [comment]
@aqnaruto 
一, 优雅当然不是跟风跟出来的.要需要沉淀和积累的.
二, 自己应该已经很注意言辞了,尽量避免出现"你"字.但没到还是让大家都激动了起来.早知道这样就不应该回复的.
三, 我不回复tp5哪好,是因为哪好readme里都说了.而还在问的人,再说什么也自然有千百句话在等着.哪不如不说喽...
四, 还有希望大家多接触一些语言,多看一些框架,不光是php的.还有其它的.眼界放开了,世界自然就大了,也自然会发现它的好处在哪...
五, tp5是在进步的...

btw:对于**拿着锤子的人看所有的东西永远都是"钉子"**

大家共勉.希望tp越来越好吧...

ps:希望你[mozart.php](https://github.com/aqnaruto/mozart.php)也有发展.点了第一个星星的我会一直关注的.
