### ISSUE TITLE
数据莫名重复插入

### ISSUE THREAD

**Issue by yufeixuan** [top-think/think#832]
执行操作后页面没有输出信息的话，mysql数据库会被插入两个完全相同的数据，不知道是什么原因引起的

**Comment by liu21st** [comment]
这个肯定不是框架的原因导致的 你跟踪下你的请求 在浏览器里面查看network

**Comment by yufeixuan** [comment]
你可以用360急速浏览器试试，network里面只有一个请求，google浏览器就没有问题，感觉很诡异

**Comment by skj198568** [comment]
这个是ajax的bug吧？是浏览器的问题，重写ajax方法，判定是否是重复请求，即可解决。

**Comment by jin123456bat** [comment]
有可能是请求favicon.ico的时候执行了代码
