### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by weika520** [top-think/think#836]
有个想法，应用模块整个剥离放入到composer里面去，通过composer来加载,测试了可行，但有一个小问题，就是app应用目录下面如果没有模块目录名称，这里（下图）就会提示错误，这校验了目录是否存在，希望这个地方可否增加一个配置，类似拒绝访问配置（deny_module_list），这样即使在app应用目录下没有这个模块目录也不会报错，应用里面的模块就可以完全抽离，做成模块开发，往采纳，谢谢
![image](https://user-images.githubusercontent.com/15397254/43674749-da4f0b34-980a-11e8-8711-70571ee91af0.png)

**Comment by weika520** [comment]
![image](https://user-images.githubusercontent.com/15397254/43674878-d7a81144-980c-11e8-8963-65e1455d5761.png)

**Comment by liu21st** [comment]
这个地方不仅仅是一个目录判断的问题 还涉及到模块的路径和配置读取

**Comment by weika520** [comment]
嗯 是的，模块的路径加载走composer的自动加载，这个没问题，配置读取这个就和拒绝访问模块哪样加一个配置，可允许访问模块（扩展模块）属于扩展模块就跳过不判断是应用目录下的模块，你看可好？像下面哪有
![image](https://user-images.githubusercontent.com/15397254/43687670-a34df620-990b-11e8-8186-f5f1d7e6cf81.png)

![image](https://user-images.githubusercontent.com/15397254/43687674-ceaf436e-990b-11e8-993c-d3e102d5a238.png)

**Comment by ixingjue** [comment]
抄袭狗  去你妹的  不如学laravel
