### ISSUE TITLE
Query.value方法缓存以及转int类型有bug

### ISSUE THREAD

**Issue by skj198568** [top-think/think#837]
`$result = $pdo->fetchColumn();
            if ($force) {
                $result += 0;
            }

            if (isset($cache)) {
                // 缓存数据
                $this->cacheData($key, $result, $cache);
            }`
439行，当
`$result  !== false`
才应该执行$force和缓存方法，否则空数据也缓存起来了。

**Comment by liu21st** [comment]
什么版本的？

**Comment by skj198568** [comment]
你好，是5.0.20，其他版本是否也有这个问题我不确定。

**Comment by liu21st** [comment]
已经改进
