### ISSUE TITLE
Yaconf  BUG

### ISSUE THREAD

**Issue by weika520** [top-think/think#838]
1、调用的时候没有加“\”会报错
![image](https://user-images.githubusercontent.com/15397254/43727730-5c512ae2-99d5-11e8-9d27-c45915dcc127.png)

2、这个get方法写法有问题，只要安装有yaconf这个扩展，配置都只读Yaconf了，不读config文件下的配置了，核心框架里面配置参数获取不到就报错了，demo都跑不通
![image](https://user-images.githubusercontent.com/15397254/43727884-d529f1ba-99d5-11e8-91bf-87f6756e50ad.png)

**Comment by liu21st** [comment]
已经改进 感谢反馈
