### ISSUE TITLE
tp  赤裸裸的抄袭laravel  真的要脸吗

### ISSUE THREAD

**Issue by ixingjue** [top-think/think#840]

**Comment by phpyii** [comment]
哥们，过激了！

**Comment by liu21st** [comment]
这是issue 不是你发泄情绪的地方

**Comment by kinosang** [comment]
ThinkPHP 5 is an open-sourced project, it is a successor to ThinkPHP 3.2, inspired by Laravel, Symfony, and other popular PHP MVC frameworks.

There's so many similar PHP projects that are inspired by modular programming, and also coded under the PSR standards, I don't think they are plagiarism, especially their codes have so many difference to each other.

Just reinvent the wheel if you don't like this one, blame does not help. This is one of the rules for open-source.
