### ISSUE TITLE
PHP7.3 bate2环境报错 switch中使用contine THINK版本v5.1.22

### ISSUE THREAD

**Issue by first236108** [top-think/think#847]
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
Template.php line 1053
`// 模板函数过滤
                $fun = trim($args[0]);
                if (in_array($fun, $template_deny_funs)) {
                    continue;
                }

                switch (strtolower($fun)) {
                    case 'raw':
                        continue;
                    case 'date':
                        $name = 'date(' . $args[1] . ',!is_numeric(' . $name . ')? strtotime(' . $name . ') : ' . $name . ')';
                        break;
                    case 'first':
                        $name = 'current(' . $name . ')';
                        break;
                    case 'last':
                        $name = 'end(' . $name . ')';
                        break;`

**Comment by liu21st** [comment]
感谢反馈，已经改进
