### ISSUE TITLE
请问路由中间分组是否支持命名空间、前缀分组

### ISSUE THREAD

**Issue by xue-y** [top-think/think#856]
请问路由中间分组是否支持命名空间、前缀分组，例如 这种方式，（这个是laravel 框架的）
![qq 20180924114724](https://user-images.githubusercontent.com/31383501/45937140-31998100-bff0-11e8-8a27-93ca2a1d351f.png)

![2345 20180924114846](https://user-images.githubusercontent.com/31383501/45937132-234b6500-bff0-11e8-896c-24a4ea7bd9f4.png)

**Comment by liu21st** [comment]
你说的prefix就是分组的名称，而namespace就是分组的prefix方法来设置

**Comment by xue-y** [comment]
prefix 不是前缀吗，namespace 不是命名空间吗？namespace就是分组的prefix方法来设置 什么意思？

**Comment by liu21st** [comment]
```
Route::group('admin',function(){
    // 路由定义
})->prefix('Admin');
```

**Comment by liu21st** [comment]
prefix方法表示路由地址使用的统一前缀标识，不一定是命名空间

**Comment by xue-y** [comment]
请问如果要分组统一的 前缀、命名空间,请问可以这样定义吗？
5.1的文档上没有 统一命名空间，不知支持不支持定义统一命名空间
Route::group('admin',function(){
    // 路由定义
})->prefix('Admin')->namespace('Admin');
