### ISSUE TITLE
Thinkphp 5.1.24 delete函数设计缺陷建议修改

### ISSUE THREAD

**Issue by ghost** [top-think/think#858]
分析的是5.1.24版本。例如，有一个删除的场景，代码简化如下。
![image](https://user-images.githubusercontent.com/11409328/46071066-cc8d8900-c1b1-11e8-8673-0ba736869f91.png)

在delete时，如果where中参数值可控，可能会造成sql注入的分析。详细分析参考下面文档。
[Thinkphp 5.1.24 可能导致注入分析.docx](https://github.com/top-think/think/files/2419072/Thinkphp.5.1.24.docx)

**Comment by Aoiujz** [comment]
这明显是你用的不对啊， 是谁告诉你where是这么拼接查询条件的？

**Comment by Aoiujz** [comment]
写成 `->where('nickname',  $nickname) ` 你注入了我看看 ？

**Comment by liu21st** [comment]
手册明确写了 如果使用字符串查询条件 请使用手动参数绑定

**Comment by wachman** [comment]
感觉上述主要是基于$filed不可控的情况下。根据代码注释可知 $field为查询字段。在有一些场景中，可能可以通过多个字段匹配值来操作可能会造成$field可控，那么可能就会存在问题了。例如一下。这个还是得跟场景有关。
public function hello(){
//	$key = " age =  20) or (select sleep(if('' = :aa,10,5))) ;# ";
//	$value = 'aa';
	$key = input('key');
	$value = input('value');
	$ids = ['id','password','birthday','place'];
	if(in_array($key,$ids)){
		echo 'failed';
	}else{
		$retult = Db::table("user")->where($key,$value)->delete();
	}
}
上述执行得是DELETE FROM `user` WHERE ( age = 20) or (select sleep(if('' = '',10,5)));#)所以得看情况吧、没有那么通用罢了。如果将$field作为列名那么可能在where中加一个判断，就像一些操作会检测表名是否存在一样。

**Comment by liu21st** [comment]
@wachman 你这个不可能成功的 不是规范的field不可能作为查询field

**Comment by 5up3rc** [comment]
活久见。这都能cve

**Comment by Balis0ng** [comment]
用假洞骗CVE是最骚的。大哥你很缺么（手动狗头）

**Comment by Lucifaer** [comment]
这是cve被黑的最惨的一次，真的是服了

**Comment by pcilkle** [comment]
> 感觉上述主要是基于$filed不可控的情况下。根据代码注释可知 $field为查询字段。在有一些场景中，可能可以通过多个字段匹配值来操作可能会造成$field可控，那么可能就会存在问题了。例如一下。这个还是得跟场景有关。
> public function hello(){
> //	$key = " age = 20) or (select sleep(if('' = :aa,10,5))) ;# ";
> //	$value = 'aa';
> $key = input('key');
> $value = input('value');
> $ids = ['id','password','birthday','place'];
> if(in_array($key,$ids)){
> echo 'failed';
> }else{
> $retult = Db::table("user")->where($key,$value)->delete();
> }
> }
> 上述执行得是DELETE FROM `user` WHERE ( age = 20) or (select sleep(if('' = '',10,5)));#)所以得看情况吧、没有那么通用罢了。如果将$field作为列名那么可能在where中加一个判断，就像一些操作会检测表名是否存在一样。



> 感觉上述主要是基于$filed不可控的情况下。根据代码注释可知 $field为查询字段。在有一些场景中，可能可以通过多个字段匹配值来操作可能会造成$field可控，那么可能就会存在问题了。例如一下。这个还是得跟场景有关。
> public function hello(){
> //	$key = " age = 20) or (select sleep(if('' = :aa,10,5))) ;# ";
> //	$value = 'aa';
> $key = input('key');
> $value = input('value');
> $ids = ['id','password','birthday','place'];
> if(in_array($key,$ids)){
> echo 'failed';
> }else{
> $retult = Db::table("user")->where($key,$value)->delete();
> }
> }
> 上述执行得是DELETE FROM `user` WHERE ( age = 20) or (select sleep(if('' = '',10,5)));#)所以得看情况吧、没有那么通用罢了。如果将$field作为列名那么可能在where中加一个判断，就像一些操作会检测表名是否存在一样。


注册时间、评论时间、键盘拼写习惯（retult)等等判断，老弟你就是发起issue申请cve的那位吧。。。为啥把老github账号注销了

**Comment by pcilkle** [comment]
注册时间、评论时间、键盘拼写习惯（retult)等等判断，@wachman 你就是发起issue申请cve的那位吧.
为什么把老github账号注销了

**Comment by perhaps542** [comment]
666,这都CVE了

**Comment by kinosang** [comment]
因超出话题，锁定本 issue，如需继续讨论“delete函数设计缺陷”问题请开新 issue
