### ISSUE TITLE
think\Collection 获取不到数据

### ISSUE THREAD

**Issue by microlazy** [top-think/think#859]
BUG重现：通过 Model 层读取数据列表之后，使用 think\Collection::column方法获取指定字段，获取不到数据，返回一个空数组
代码如下：
```php
$user = (new User)->where('status',1)->field('id,username,create_time...')->select();
print_r($user->column('username', 'id'));
//返回结果：[]
```
环境：
topthink/framework：5.1.24
PHP：5.6.27-nts
系统：Window10 版本1607（OS 14393.2485）

**Comment by momoca** [comment]
这种用户还真是第一次见.哈哈.厉害!!!
建议你看一下例程.
https://www.kancloud.cn/manual/thinkphp5_1/354000

**Comment by microlazy** [comment]
> 这种用户还真是第一次见.哈哈.厉害!!!
> 建议你看一下例程.
> https://www.kancloud.cn/manual/thinkphp5_1/354000
