### ISSUE TITLE
5.0.12 模型一对一取不到关联数据

### ISSUE THREAD

**Issue by fengxinyhyl** [top-think/think#860]
- 设置关联
public function shop()
    {
        return $this->belongsTo(Shop::class, 'shop_id', 'id');
    }

think\model\relation\BelongsTo.php的第54行获取关联模型的方法：
$relationModel = $this->query
            ->where($this->localKey, $this->parent->$foreignKey)
            ->relation($subRelation)
            ->find();
在文档中https://www.kancloud.cn/manual/thinkphp5/135191，提示如果你是在模型内部，请不要使用$this->name的方式来获取数据，请使用$this->getAttr('name') 替代。

当我把代码改成：
$relationModel = $this->query
            ->where($this->localKey, $this->parent->getAttr($foreignKey)）
            ->relation($subRelation)
            ->find();
是可以正常获取的

这是版本bug??

**Comment by liu21st** [comment]
关联对象和模型是两个不同的对象 不存在内部的问题
