### ISSUE TITLE
【数据库/模型】join方法，在where中含有关联表字段的between time条件时，无法识别关联表的别名

### ISSUE THREAD

**Issue by KiddoLin** [top-think/think#861]
tp版本：v5.1.19
【数据库】或【模型】的join方法使用'不带数据表前缀的表名 别名'的写法，在where中有between time条件时无法识别关联表的别名。此时关联表的别名会被识别出table，导致生成SQL报错。
例如，在查询order表（关联表）的条件时，普通查询还能正常查询，但出现between time条件时：
$data = User::alias('u')->join('order o','o.user_id= u.user_id')
    ->where([ ['o.create_time', 'between time', ['2018-10-01 00:00:00','2018-10-15 23:59:59'] ])
    ->buildSql();
或
$data = Db::table('user')->alias('u')->join('order o','o.user_id= u.user_id')
    ->where([ ['o.create_time', 'between time', ['2018-10-01 00:00:00','2018-10-15 23:59:59'] ])
    ->buildSql();
错误信息
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'datebase.o' doesn't exist

**Comment by linxiaojialin** [comment]
用 写法1：[ '完整表名或者子查询'=>'别名' ] 也是一样会以上报错

**Comment by linxiaojialin** [comment]
@momoca 我就是想用between time。你说的是时间“快捷查询”的用法，我说的是“查询表达式”的用法。
详情请看手册 [https://www.kancloud.cn/manual/thinkphp5_1/354004]
【between】是区间查询，【between time】是时间区间比较，2者都是查询表达式。

我遇到的问题是，在主表使用between time可以正常生成SQL，在关联表使用between time会报错。
例如，$data = User::alias('u')->join('order o','o.user_id= u.user_id')
->where([ ['u.register_time', 'between time', ['2018-01-01 00:00:00','2018-10-15 23:59:59'] ])
->buildSql();
是可以生成SQL，正常查询的。

**Comment by momoca** [comment]
你在哪看到有【between time】这么用的呀。我是没见过。举个例子。让我学习一下。
