### ISSUE TITLE
5.1.25版本，使用文件缓存，在自定义指令中使用 Cache::set 方法，生成的缓存文件路径不对

### ISSUE THREAD

**Issue by humengcn** [top-think/think#862]
代码如下：`
namespace app\common\command;

...

    protected function execute(Input $input, Output $output)
    {
        // ...
            Cache::set('test_key', '测试', 1000);
        // ...
    }
}
`
生成的缓存文件跳到项目的上级目录了

**Comment by liu21st** [comment]
命令行下面是没有模块的概念的 所以也不会加载模块的配置，你的缓存配置路径是什么？

**Comment by humengcn** [comment]
路径是：`'path'   => '../runtime/cache/'`，明白了，这个路径要配置成绝对路径，对吧

**Comment by liu21st** [comment]
嗯 如果是命令行运行的 最好是设置为绝对路径
