### ISSUE TITLE
tp5的模型查询（model）和数据库查询（Db类）返回对象实例

### ISSUE THREAD

**Issue by xue-y** [top-think/think#870]
请问为什么要设计成返回对象实例，不返回数组； 或者添加一个配置项可以让用户选择返回类型；虽然手册有个 toArray  可以转为数组，感觉有些麻烦，有时返回的数据只需要数据即可，其他的都不需要，返回对象在转为数组有点浪费资源消耗性能

**Comment by liu21st** [comment]
ORM 模型查询始终返回对象 Db查询返回数组 其实对象和数组一样用 干嘛非要转换成数组呢？

**Comment by xue-y** [comment]
你们手册5.1上说：模型查询除了使用自身的查询方法外，一样可以使用数据库的查询构造器，返回的都是模型对象实例。

5.1.28 版本 Db 查询现在返回的是数组吗？如果返回是对象的话没法判断是否查询到数据，时间数据是否为空
