### ISSUE TITLE
配置文件 中 url_controller_layer 发生改变,后缀也会一起改变

### ISSUE THREAD

**Issue by duchao1990** [top-think/think#871]
### **配置文件中修改如下:**

`'url_controller_layer'   => 'home',`
`'controller_suffix'      => 'Controller',`

错误信息如下
**[0] HttpException in Module.php line 100
控制器不存在:app\index\home\ThisHome**

控制器后缀发生了变化

**Comment by liu21st** [comment]
为什么会有这样的需求

**Comment by duchao1990** [comment]
不同的模块,后台管理,web前端页面,以及api进入各自的控制器文件夹下边
