### ISSUE TITLE
模型内方法调用setInc错误

### ISSUE THREAD

**Issue by augushong** [top-think/think#873]
在模型里使用setInc会有错误,
错误如下:
![default](https://user-images.githubusercontent.com/31880431/48458066-bd18dc80-e7ff-11e8-928b-8714a5c62de7.png)
我的用法:
![default](https://user-images.githubusercontent.com/31880431/48458095-d7eb5100-e7ff-11e8-841e-ceb5b0d7d84f.png)
![default](https://user-images.githubusercontent.com/31880431/48458103-e0dc2280-e7ff-11e8-9004-010e244c205c.png)
这样在模型里会报错,似乎在模型里调用inc,"hits"就不会添加到model->data的数组里.
还是说就不该这样用,或者以后会更新能够这样用.

版本:define('THINK_VERSION', '5.0.21');

**Comment by liu21st** [comment]
不建议这样的用法的，建议先查询后更新 或者干脆直接走Db类吧
