### ISSUE TITLE
5.0.22版本 链式操作 count() 方法返回值类型问题

### ISSUE THREAD

**Issue by huguoliang** [top-think/think#875]
最近升级到 5.0.22 版本发现列表里的页码全没了，经过排查发现 返回的总记录数，也就是 Query类 count() 方法返回值全部变成了字符类型，由于项目是前后端分离的，前端VUE框架通过返回的总记录数计算页数时，总记录数必须是整型，建议count() 方法加第二参数用于返回类型的转换。

**Comment by zong86** [comment]
在php里面主动转一下类型比较好把

**Comment by liu21st** [comment]
这个问题后来有修正过
