### ISSUE TITLE
mysql 取别名’AS‘ 中文 报错BUG解决方法

### ISSUE THREAD

**Issue by xiaoxigithub** [top-think/think#876]
在think\db\Builder.php下的parseField()方法下
212行原：  $array[] = $this->parseKey($query, $key) . ' AS ' . $this->parseKey($query, $field,true);
212行应该改成：
  $array[] = $this->parseKey($query, $key,true) . ' AS ' . $this->parseKey($query, $field);
‘AS’ 后parseKey()不用开启严格检测。

**Comment by liu21st** [comment]
你直接用Db::raw 就行 否则存在安全问题的
