### ISSUE TITLE
TP5.1应加会TP5.0中app_status配置属性以适应开发/生产/测试多场景部署的配置切换

### ISSUE THREAD

**Issue by aihua** [top-think/think#880]
TP5.1应加会TP5.0中app_status配置属性以适应开发/生产/测试多场景部署的配置切换，特别是自动化部署时配置文件的切换。

**Comment by aihua** [comment]
如题  @liu21st

**Comment by HFLeon** [comment]
不是有env

**Comment by liu21st** [comment]
环境变量的作用就是这个

**Comment by aihua** [comment]
@liu21st @HFLeon 对应的环境变量名称是？能详细说下吗，TP5.1开发手册中https://www.kancloud.cn/manual/thinkphp5_1/content好像没对这块有描述。

**Comment by momoca** [comment]
https://www.kancloud.cn/manual/thinkphp5_1/353951
环境变量定义
你也没搜素呀。

**Comment by aihua** [comment]
https://www.kancloud.cn/manual/thinkphp5_1/353951 这页文档是看过的，但是并没看到app_status变量配置说明。假设测试库192.168.0.1，生产库192.168.0.2，test.php保存测试库的配置项db.host=192.168.0.1，product.php保存生产库的配置项db.host=192.168.0.2。之前在TP5.0中，在app.php中设置app_status=test时会加载test.php中配置项，设置app_status=product会加载product.php中的配置项。即TP5.0手册 https://www.kancloud.cn/manual/thinkphp5/118024 中“场景配置”一节。这种“场景配置”在TP5.1中如何配置？ @momoca @HFLeon @liu21st @dseguy
