### ISSUE TITLE
在5.0.23中使用$request->param()无法获取urlencode()的参数

### ISSUE THREAD

**Issue by capping** [top-think/think#884]
我的url中的一个参数是 `desc=%2A%3C%3E`，`%2A%3C%3E` 是`urlencode('*<>')`之后的结果,但是我通过$request->param()获取到的desc的结果为`*`

**Comment by wmwyyx** [comment]
htmlspecialchars("*<>");
index.php/desc/* & l t ; & g t ;

**Comment by hongweipeng** [comment]
`$request->param()` 获取的数据是经过过滤的。获取原始数据可以用 `$request->param(false)`。

**Comment by capping** [comment]
close

**Comment by capping** [comment]
> `$request->param()` 获取的数据是经过过滤的。获取原始数据可以用 `$request->param(false)`。

Thinks, 我已经解决这个问题，用你说的这种方法。
