### ISSUE TITLE
5.2 下载无法使用

### ISSUE THREAD

**Issue by zoujingli** [top-think/think#891]
![image](https://user-images.githubusercontent.com/4349951/52943208-9989a300-33a7-11e9-85bb-d8855af16f22.png)

**Comment by zoujingli** [comment]
Response:create 第二个参数是 字符串类型，而在内核调用的时候传的是null

**Comment by liu21st** [comment]
你应该是更新了核心框架 但是今天应用仓库有调整 配置文件分离了 所以你需要重新配置下 或者重新安装下5.2应用

**Comment by zoujingli** [comment]
Dispatch.php
这个变量$this->rule->config为null
![image](https://user-images.githubusercontent.com/4349951/52983779-a8b03580-3427-11e9-80ae-0d3a22567c6e.png)

**Comment by zoujingli** [comment]
我先不用了，等正式出来了再来。
非常期待tp5.2真正的组件化框架...

**Comment by liu21st** [comment]
null就是因为你没有配置 配置文件变化了的
