### ISSUE TITLE
添加数据时,传的字段为空值时写入数据会默认变成0而不是null

### ISSUE THREAD

**Issue by firekeeper76** [top-think/think#902]
数据库字段可以为null的情况下,
接收的数据:
```
{
  "status": ""
} 
```
请问在save添加数据时 生成的sql语句为什么是
INSERT INTO \`test\` (\`status\`) VALUES (0)
而不是下面这个呢
INSERT INTO \`test\` (\`status\`) VALUES (null)

**Comment by liu21st** [comment]
只要不是null 其它值都会根据字段类型 进行自动参数绑定（转换）

**Comment by firekeeper76** [comment]
> 只要不是null 其它值都会根据字段类型 进行自动参数绑定（转换）

可以请问一下这样设计的原因是什么吗
