### ISSUE TITLE
php think make:controller 异常

### ISSUE THREAD

**Issue by ZhangGuangHuiCoder** [top-think/think#908]
D:\wuliu>php think -version
version 6.0.0RC1

D:\wuliu>php -v
PHP 7.1.26 (cli) (built: Jan  9 2019 21:51:08) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

D:\wuliu>php think make:controller Token

  [TypeError]
  call_user_func_array() expects parameter 1 to be a valid callback, class 'think\cache\driver\File' does not have a
  method 'config'

Exception trace:
 () at D:\wuliu\vendor\topthink\framework\src\think\Cache.php:295
 call_user_func_array() at D:\wuliu\vendor\topthink\framework\src\think\Cache.php:295
 think\Cache->__call() at D:\wuliu\vendor\topthink\framework\src\think\console\command\Make.php:62
 think\console\command\Make->buildClass() at D:\wuliu\vendor\topthink\framework\src\think\console\command\Make.php:47
 think\console\command\Make->execute() at D:\wuliu\vendor\topthink\framework\src\think\console\Command.php:210
 think\console\Command->run() at D:\wuliu\vendor\topthink\framework\src\think\Console.php:618
 think\Console->doRunCommand() at D:\wuliu\vendor\topthink\framework\src\think\Console.php:267
 think\Console->doRun() at D:\wuliu\vendor\topthink\framework\src\think\Console.php:204
 think\Console->run() at D:\wuliu\think:19

**Comment by liu21st** [comment]
已经修正
