### ISSUE TITLE
5.1使用软删除时，软删除字段的类型绑定有误

### ISSUE THREAD

**Issue by MrCJJW** [top-think/think#914]
我的软删除字段为is_delete,0表示未删除,1表示已删除,字段类型为tinyint
构造出来的sql语句is_delete会变成is_delete='0'，类型不匹配
![image](https://user-images.githubusercontent.com/15009827/56094928-409f3c80-5f0a-11e9-95a7-aeb8bd478e44.png)
因为软删除的field为__TABLE__.is_delete,所以$binds里面不存在此字段，类型解析为PDO::PARAM_STR，和5.0比对发现，5.0会使用array_key_exists判断filed是否存在才进行类型绑定
![image](https://user-images.githubusercontent.com/15009827/56094979-ae4b6880-5f0a-11e9-9daf-ec0ee6549c37.png)
5.1此处是否有问题？如果没问题，字段类型又如何处理？

**Comment by liu21st** [comment]
规范起见，软删除字段用时间字段即可

**Comment by MrCJJW** [comment]
ok
