### ISSUE TITLE
Hook 中结束流程直接返回数据应该如何操作？ 

### ISSUE THREAD

**Issue by jmluang** [top-think/think#925]
是否只能抛出 HttpResponseException 异常？
version：5.0.24

**Comment by momoca** [comment]
abort

**Comment by jmluang** [comment]
> abort

abort 也是抛出异常，框架似乎没考虑到这种情况。。要执行其他的操作只能手动执行，尴尬

**Comment by momoca** [comment]
abort+view呀亲。

**Comment by jmluang** [comment]
> abort+view呀亲。

abort+view 也是返回 HttpResponseException 呀。
如果当前 abort 是在 module_init 的 Hook 中，绑定在这个 Hook 后面执行的所有 Hook 都需要手动去触发了。我想要的场景是 Hook 中终止可以当作一个正常的 Response对象返回，而不是一个 HttpResponseException 这样。

**Comment by liu21st** [comment]
用中间件

**Comment by momoca** [comment]
他是5.0版本。哪时好像还没有中间件的概念吧。
https://www.kancloud.cn/manual/thinkphp5/122950
