### ISSUE TITLE
请不要再composer.json 中 "topthink/framework": "5.1.*"，请每个版本改成对应的版本

### ISSUE THREAD

**Issue by liuruidong1994** [top-think/think#927]
新更新的5.1.36 会对我的代码造成影响，
于是我把我的composer.json   锁定为 "topthink/think": "5.1.35"
但是你这个think 项目里用的 "topthink/framework": "5.1.*" 
搞得我这个版本锁定一点用都没用！
始终只能用最新的topthink/framework！
你们这样搞直接阉割了composer 的功能啊！

**Comment by liuruidong1994** [comment]
请不要使用 5.1.* 这种版本号，请使用准确的版本号，每次打tag就更新一次，保证 think 项目和 framework 项目的版本完全准确统一，不然我这种项目和你们版本更新不兼容的真的很痛苦啊。真的不敢随便跟着你们升啊，都是锁定版本的。
我每次发版都要手动composer require topthink/framework: 5.1.35，很难受啊

**Comment by liu21st** [comment]
奇怪的是你干嘛要升级think包呢

**Comment by declandragon** [comment]
请在版本库中维护 `composer.lock`
