### ISSUE TITLE
当请求参数是json数组时，控制器参数的注入有一些问题

### ISSUE THREAD

**Issue by kingzcheung** [top-think/think#931]
路由：

定义：/users/:id

调用：
PUT /users/123
Accept: application/json
Content-Type: application/json
Accept-Language: zh-CN
Authorization: Bearer {{token}}

[
  {"username":"foo","age":13},
  {"username":"bar","age":17},
]

控制器：
```
public function read(Request $request,int $id) {
      dump($id)
}
```
此时$id的参数不是123，而是
```json
[
  {"username":"foo","age":13},
  {"username":"bar","age":17},
]
```

**Comment by zcenet** [comment]
邮箱已收到，谢谢你的支持，祝你生活愉快~~=================================杨怀桂手机:13698971401
