### ISSUE TITLE
6.0.3 新项目 执行完php think optimize:config 后别的命令行都报错

### ISSUE THREAD

**Issue by tongjuhua** [top-think/think#937]
F:\phpproject\six>php think optimize:schema
PHP Notice:  unserialize(): Error at offset 6 of 3338 bytes in F:\phpproject\six\vendor\topthink\framework\src\think\App.php on line 635

Notice: unserialize(): Error at offset 6 of 3338 bytes in F:\phpproject\six\vendor\topthink\framework\src\think\App.php on line 635
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to think\Config::set() must be of the type array, boolean given in F:\phpproject\six\vendor\topthink\framework\src\think\Config
.php:175
Stack trace:
#0 [internal function]: think\Config->set(false)
#1 F:\phpproject\six\vendor\topthink\framework\src\think\Facade.php(99): call_user_func_array(Array, Array)
#2 F:\phpproject\six\runtime\init.php(9): think\Facade::__callStatic('set', Array)
#3 F:\phpproject\six\vendor\topthink\framework\src\think\App.php(366): include('F:\\phpproject\\s...')
#4 F:\phpproject\six\vendor\topthink\framework\src\think\Console.php(101): think\App->initialize()
#5 [internal function]: think\Console->__construct(Object(think\App))
#6 F:\phpproject\six\vendor\topthink\framework\src\think\Container.php(395): ReflectionClass->newInstanceArgs(Array)
#7 F:\phpproject\six\vendor\topthink\framework\src\think\Container.php(255): think\Container->invokeClass('think\\Console', Array)
#8 F:\phpproject\six\vendor\topthink\framework\src\think\Container.php(252):  in F:\phpproject\six\vendor\topthink\framework\src\think\Config.php on line 175

Fatal error: Uncaught TypeError: Argument 1 passed to think\Config::set() must be of the type array, boolean given in F:\phpproject\six\vendor\topthink\framework\src\think\Config.php:
175
Stack trace:
#0 [internal function]: think\Config->set(false)
#1 F:\phpproject\six\vendor\topthink\framework\src\think\Facade.php(99): call_user_func_array(Array, Array)
#2 F:\phpproject\six\runtime\init.php(9): think\Facade::__callStatic('set', Array)
#3 F:\phpproject\six\vendor\topthink\framework\src\think\App.php(366): include('F:\\phpproject\\s...')
#4 F:\phpproject\six\vendor\topthink\framework\src\think\Console.php(101): think\App->initialize()
#5 [internal function]: think\Console->__construct(Object(think\App))
#6 F:\phpproject\six\vendor\topthink\framework\src\think\Container.php(395): ReflectionClass->newInstanceArgs(Array)
#7 F:\phpproject\six\vendor\topthink\framework\src\think\Container.php(255): think\Container->invokeClass('think\\Console', Array)
#8 F:\phpproject\six\vendor\topthink\framework\src\think\Container.php(252):  in F:\phpproject\six\vendor\topthink\framework\src\think\Config.php on line 175

**Comment by tongjuhua** [comment]
全新的项目，不知道什么情况

**Comment by liu21st** [comment]
这个指令已经被废弃了
