### ISSUE TITLE
数据集转换为array报错

### ISSUE THREAD

**Issue by 2pgcn** [top-think/think#942]
![image](https://user-images.githubusercontent.com/32252481/60072440-0f37be00-9750-11e9-89ab-54b46fa054a0.png)
![image](https://user-images.githubusercontent.com/32252481/60072453-1bbc1680-9750-11e9-8be8-8c73d3e3c57a.png)
之前是好的,今天更新了下代码就报错了

**Comment by 2pgcn** [comment]
拿时间字段会报错

**Comment by 2pgcn** [comment]
![image](https://user-images.githubusercontent.com/32252481/60072561-79506300-9750-11e9-9bbc-bff2fd2dacea.png)

**Comment by liu21st** [comment]
你设置了时间字段类型么？

**Comment by 2pgcn** [comment]
忘记关闭了,后来看源码你这边加了创建时间,更新时间。自己前面改好了
