### ISSUE TITLE
请问一下 TP6 正式版本什么时候发布？

### ISSUE THREAD

**Issue by conero** [top-think/think#944]
> 我看到 git 代码仓库中已经发布了几个 **tp6** 的 RC 版本，因此很好奇什么时候会发布 TP6 的正式版本。在官网以及网上找了一下，没有发现相关的发布计划，因此问一下。

*TP6 正式发布一定是一个激动人心的时候！*
- [x] 加油!
- [x] 加油!
- [x] 加油!
- [x] 加油!

**Comment by liu21st** [comment]
正式发布取决于版本的测试和反馈情况 官方目前的版本发布是每隔2个月左右出一个版本，如果达到标准就会发布

**Comment by conero** [comment]
@liu21st 谢谢
