### ISSUE TITLE
路由跨域配置allowCrossDomain不生效

### ISSUE THREAD

**Issue by goofy-he** [top-think/think#947]
->header('Access-Control-Allow-Origin', '*')
->header('Access-Control-Allow-Headers', 'Authorization, x-city, x_requested_with, X-Requested-With, Content-Type,  If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since')
    ->allowCrossDomain();
然而并不请作用,OPTIONS还是500,请求更新

**Comment by sunmking** [comment]
应该在入口文件配置

**Comment by goofy-he** [comment]
> 应该在入口文件配置

要allowCrossDomain()做什么呢

**Comment by liu21st** [comment]
反馈问题最好说清楚具体版本

**Comment by sunmking** [comment]
> > 应该在入口文件配置
> 
> 要allowCrossDomain()做什么呢

http://www.thinkphp.cn/topic/63383.html 这个问题有具体的解决方法和原因

**Comment by goofy-he** [comment]
6.0的开发板呀

**Comment by liu21st** [comment]
@goofy-he 6.0根本就不支持header方法的 仔细参考手册的路由-》跨域请求章节

**Comment by goofy-he** [comment]
要allowCrossDomain()做什么呢

Route::get('new/:id', 'News/read')
    ->ext('html')
    ->allowCrossDomain([
        'Access-Control-Allow-Origin'        => '*',
        'Access-Control-Allow-Credentials'   => 'true'
    ]);

写到里面也不能正常呀,  只能写到index.php入口去吗?那allowCrossDomain()的存在意义呢
