### ISSUE TITLE
TP5 模板引擎可以实现对字符串模板的解析吗(非文件模板)

### ISSUE THREAD

**Issue by conero** [top-think/think#953]
> *由于有时候需要对字符串模板进行解析，比如数据库内部的短信模板或者其他配置模板解析，再使用解析后的字符串*

<br />
<br />
<br />

我看了一下 TP5 的 View 代码，发现没有这种解决方法！因此想在这儿确认是否自己忽略一些东西。以及后期的版本内部是否已经存在这样的解决方案?

**Comment by liu21st** [comment]
支持的 使用display方法替代fetch方法

**Comment by conero** [comment]
@liu21st 谢谢
