### ISSUE TITLE
tp5.1使用指定数据库进行表操作如何支持事务回滚

### ISSUE THREAD

**Issue by yangpanyao** [top-think/think#956]
`//测试1        测试Db::connect  失败 不可回滚

     Db::startTrans();
        try {
            $role_id=Db::connect('db_shop_merchant')->name('auth_role')->insertGetId($role_array);
            $menu_res = [];
            foreach ($menu_list as $k => $v) {
                $menu_res[]=[
                    'role_id'=>$role_id,
                    'menu_id'=>$v
                ];
            }
            $insertall=Db::connect('db_shop_merchant')->name('auth_rolelist')->insertAll($menu_res);//这里故意写错
           
            // 提交事务
            Db::commit();
        } catch (\Exception $e) {
            echo '1';
            Db::rollback();
        }
`
`//测试Db::name  成功  可以回滚

        // 启动事务
         Db::startTrans();
        try {
             $role_id=Db::name('store')->insert($store_res);

             $insertall=Db::name('basketss')->insert($banner_res);//这里故意写错
           
             // 提交事务
            Db::commit();
         } catch (\Exception $e) {
             echo '1';
             Db::rollback();
         }`
` //测试 db   失败  不能回滚

       // 启动事务
         Db::startTrans();
        try {
            $role_id=db('store')->insert($store_res);

            $insertall=db('basketss')->insert($banner_res);//这里故意写错
           
            // 提交事务
            Db::commit();
        } catch (\Exception $e) {
            echo '1';
            Db::rollback();
        }`

**Comment by liu21st** [comment]
事务回滚的前提是在同一个数据库连接（实例）中，你的第一和第三种情况都不满足 当然无法回滚

**Comment by yangpanyao** [comment]
由于我们的数据库设计的是多库 会出现跨库多表操作的场景
