### ISSUE TITLE
单应用与多应用路由逻辑有点乱

### ISSUE THREAD

**Issue by sclswin** [top-think/think#959]
多应用测试
config/app.php文件中
**这个自动多路由的叫法就不对**，应该 叫开启多应用模式，并且在路由文档开头应该说明单路由与多路由只能选 择一种。并且多路由模式必须要删除app目录下的单路由文件。
[我详细的踩坑路](https://xcwmoon.com/post/106)

**Comment by liu21st** [comment]
手册一再强调 路由是针对应用的

**Comment by sclswin** [comment]
> 手册一再强调 路由是针对应用的

> 路由定义和检测是针对应用的，因此如果你采用的是多应用模式，每个应用的路由都是完全独立的，并且路由地址不能跨应用

是说的这一句描述么，文 档里的确是有，但是当时我的理解是，路由当然是针对应用，单应用与多应用都叫应用吧，那么我单应用路由对应单应用，多应用路由对应多应用，如果开启自动多应用模式，那它应该自动寻找我的其他应用才对啊，但是他没有自动寻找，而是进了单应用的命名空间寻找控制器。就是单应用与多应用不能同时并存，并且单应用的文件也不能存在。

**Comment by anydson** [comment]
> > 手册一再强调 路由是针对应用的
> 
> > 路由定义和检测是针对应用的，因此如果你采用的是多应用模式，每个应用的路由都是完全独立的，并且路由地址不能跨应用
> 
> 是说的这一句描述么，文 档里的确是有，但是当时我的理解是，路由当然是针对应用，单应用与多应用都叫应用吧，那么我单应用路由对应单应用，多应用路由对应多应用，如果开启自动多应用模式，那它应该自动寻找我的其他应用才对啊，但是他没有自动寻找，而是进了单应用的命名空间寻找控制器。就是单应用与多应用不能同时并存，并且单应用的文件也不能存在。

单应用与多应用目录结构不一样，因此单应用与多应用路由不能同时配置
