### ISSUE TITLE
有兴趣重构推翻重来吗

### ISSUE THREAD

**Issue by slince** [top-think/think#96]
cake和symfony、yii都经历过

**Comment by Lofanmi** [comment]
@slince 欢迎进群讨论~~很多东西都打算重构呢

**Comment by liu21st** [comment]
@slince 欢迎加入我们一起完善 虽然不一定会推翻重来 但可以多交流~

**Comment by lubiao39699492** [comment]
我目前的建议是：
把library独立成包，命名空间Think\*，thinkphp目录作为启动文件，以后更新只要用composer更新包就可以了。

**Comment by lloydzhou** [comment]
@lubiao39699492 支持

**Comment by liu21st** [comment]
@lubiao39699492 上次内部有聊过这个问题的
