### ISSUE TITLE
关于url函数生成链接的问题

### ISSUE THREAD

**Issue by guigui0326** [top-think/think#960]
如何用url生成函数生成api模块的完整链接？因为api模块的目录结构是api/controller/v1(版本号)/控制器文件。
![image](https://user-images.githubusercontent.com/30816908/62408730-eed90a00-b5ff-11e9-858f-367dfc09a2c3.png) 而直接解析里好像没有对其进行处理，所以想请教一下该如何生成呢？

**Comment by anydson** [comment]
> 如何用url生成函数生成api模块的完整链接？因为api模块的目录结构是api/controller/v1(版本号)/控制器文件。
> ![image](https://user-images.githubusercontent.com/30816908/62408730-eed90a00-b5ff-11e9-858f-367dfc09a2c3.png) 而直接解析里好像没有对其进行处理，所以想请教一下该如何生成呢？

url('api/v1.控制器');

**Comment by anydson** [comment]
> 如何用url生成函数生成api模块的完整链接？因为api模块的目录结构是api/controller/v1(版本号)/控制器文件。
> ![image](https://user-images.githubusercontent.com/30816908/62408730-eed90a00-b5ff-11e9-858f-367dfc09a2c3.png) 而直接解析里好像没有对其进行处理，所以想请教一下该如何生成呢？

url('api/v1.控制器');
