### ISSUE TITLE
2.0.* 版本报 think\facade\Env 找不到的错误

### ISSUE THREAD

**Issue by stone009** [top-think/think#966]
请官方修复一下，主要原因是以下两个文件引入的路径错误导致的。
以下文件中：

vendor/topthink/think-migration/src/command/Seed.php
vendor/topthink/think-migration/src/command/Migrate.php

将 ```use think\facade\Env;``` 修改为 ```use think\Env;``` 即可。

TP版本："5.0.*
think-migration 版本：2.0.*
系统：win10

**Comment by liu21st** [comment]
5.0版本你要安装1.*版本 2.0版本是针对5.1框架的
