### ISSUE TITLE
ThinkPHP6.0RC4 路由失效

### ISSUE THREAD

**Issue by DYH89** [top-think/think#974]
ThinkPHP6.0RC4 路由失效刚刚安装,路由是好多,给的例子可以访问.
添加路由之后,路由全部失效.
控制器不存在.

**Comment by isszz** [comment]
并不是失效;你估计是开启多应用模式
首先你要在config/app.php里面配置domain_bind
例如:
```
    // 域名绑定（自动多应用模式有效）
    'domain_bind'      => [
        '*' => 'home', // home应用, *指的是默认域名绑定的app,需要修改default_app=home,默认是index
        'admin.test.io' => 'admin', // admin应用
    ],
```
模式1
在对应app目录新建例如

> admin/route/web.php
> home/route/web.php

模式2
在根目录route目录下新建
> route/home/web.php
> route/admin/web.php
在这里面写队友的路由即可

**Comment by DYH89** [comment]
@isszz 搞定了,谢谢.

**Comment by isszz** [comment]
> @isszz 搞定了,谢谢.

其实还是有bug的...多应用模式下...你可以看我的issues
