### ISSUE TITLE
app 目录下文件太乱

### ISSUE THREAD

**Issue by ghost** [top-think/think#978]
TP6之前的版本存在太多所谓的灵活性，tp6的目标是简化。
**模块**
关于多模块和单模块，保留一种就可以了。单一模块可采用显式路由（大项目效率低）；多模块下保留TP的特色，使用自动路由（推荐）。
**应用**
目前app目录下文件太乱，最好按文件作用子目录归类。

**Comment by liu21st** [comment]
app目录下的文件主要是全局定义文件 ，其它文件是你随便处理的 。至于单应用和多应用的设计问题，其实默认就是单应用 很多人不是特别理解新版的多应用 尤其是路由的使用，多应用的设计就是各个应用完全独立的，之前的多模块概念 其实一样可以支持 在单应用下面使用控制器分级

**Comment by isszz** [comment]
6.0R4的路由bug有点多- -...

希望能好用,我对比了laravel感觉还是think比较好上手...而且laravel现在性能堪忧...

**Comment by liu21st** [comment]
@isszz 路由有啥bug？

**Comment by ghost** [comment]
TP6在开发的过程中与TP5还是有不少的差异
比如 layout 不能跨应用（模块）调用了。

既然有多应用模式，还是支持下跨应用 layout 比较好。
或者参考其他框架，基于组件推出两个 scaffold，如下：

- 多应用：
全栈针对传统Web开发，这块TP的优势及开发者用户数量较多，目前还没有其他框架丢下view应用，包括以`微服务`著称的lumen，保证 TP5 -> TP6 的顺滑升级至关重要。

- 单应用：
API优先支持下JWT扩展，再加上swoole加持，性能必定很强。


PS
- laravel & lumen
- yii-console & yii-web & yii-rest

**Comment by liu21st** [comment]
@typeu 因为新版的模板引擎已经独立了 所以对于模板引擎来说 是没有多应用的概念的 本身多应用也是一个扩展 跨应用layout这个需求是项目的设计规范要避免的,TP6的应用之间是相互独立的 如果需要跨应该在应用里面跨,鉴于很多方面的原因,TP5->TP6的平滑升级已经不太可行了

单应用的swoole支持是完善了的 至于JWT扩展 这个已经有很多,也没必要内置, TP也不会走Laravel的路线 TP6的规范和核心设计都是为了让扩展生态更丰富而考虑的
