### ISSUE TITLE
模板缓存监听是否改动的bug

### ISSUE THREAD

**Issue by yangweijie** [top-think/think#99]
现在模板文件监听的是fetch的父文件的修改时间，如果该文件里有include 或者 继承block， 也应该更新缓存，而不是读之前换存的主文件时间

**Comment by amiter** [comment]
模板 A中有include B，如果每次都要检测A里的include之类标签，那就每次都要读模板文件A、解析、编译模板，并没有做到不用编译A就返回，失去A文件编译缓存的意义了。
