### ISSUE TITLE
Command 'DELETE' is not a registered Redis command.

### ISSUE THREAD

**Issue by sinhang** [top-think/think#996]
使用redis在清除缓存的时候提示：
Command 'DELETE' is not a registered Redis command.

thinkphp/library/think/cache/driver/Redis.php

第143行
`return $this->handler->delete($this->getCacheKey($name));`
需要改成
`return $this->handler->del($this->getCacheKey($name));`

第158行
`$this->handler->delete($key);`
需要改成
`$this->handler->del($key);`

**Comment by liu21st** [comment]
哪个版本的？除了5.0 其它版本都已经改进过

**Comment by sinhang** [comment]
> 哪个版本的？除了5.0 其它版本都已经改进过

5.1.22

**Comment by liu21st** [comment]
> > 哪个版本的？除了5.0 其它版本都已经改进过
> 
> 5.1.22

最新版本是5.1.38

**Comment by sinhang** [comment]
> > > 哪个版本的？除了5.0 其它版本都已经改进过
> > 
> > 
> > 5.1.22
> 
> 最新版本是5.1.38

已升级。
